/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export type ReadAppVariablesRequest = {
    id: string;
    pageNumber?: number | undefined;
    pageSize?: number | undefined;
};

export type ReadAppVariablesResponse = components.ReadVariablesResponse | components.ErrorT;

/** @internal */
export const ReadAppVariablesRequest$inboundSchema: z.ZodType<
    ReadAppVariablesRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    id: z.string(),
    pageNumber: z.number().int().optional(),
    pageSize: z.number().int().optional(),
});

/** @internal */
export type ReadAppVariablesRequest$Outbound = {
    id: string;
    pageNumber?: number | undefined;
    pageSize?: number | undefined;
};

/** @internal */
export const ReadAppVariablesRequest$outboundSchema: z.ZodType<
    ReadAppVariablesRequest$Outbound,
    z.ZodTypeDef,
    ReadAppVariablesRequest
> = z.object({
    id: z.string(),
    pageNumber: z.number().int().optional(),
    pageSize: z.number().int().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ReadAppVariablesRequest$ {
    /** @deprecated use `ReadAppVariablesRequest$inboundSchema` instead. */
    export const inboundSchema = ReadAppVariablesRequest$inboundSchema;
    /** @deprecated use `ReadAppVariablesRequest$outboundSchema` instead. */
    export const outboundSchema = ReadAppVariablesRequest$outboundSchema;
    /** @deprecated use `ReadAppVariablesRequest$Outbound` instead. */
    export type Outbound = ReadAppVariablesRequest$Outbound;
}

/** @internal */
export const ReadAppVariablesResponse$inboundSchema: z.ZodType<
    ReadAppVariablesResponse,
    z.ZodTypeDef,
    unknown
> = z.union([components.ReadVariablesResponse$inboundSchema, components.ErrorT$inboundSchema]);

/** @internal */
export type ReadAppVariablesResponse$Outbound =
    | components.ReadVariablesResponse$Outbound
    | components.ErrorT$Outbound;

/** @internal */
export const ReadAppVariablesResponse$outboundSchema: z.ZodType<
    ReadAppVariablesResponse$Outbound,
    z.ZodTypeDef,
    ReadAppVariablesResponse
> = z.union([components.ReadVariablesResponse$outboundSchema, components.ErrorT$outboundSchema]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ReadAppVariablesResponse$ {
    /** @deprecated use `ReadAppVariablesResponse$inboundSchema` instead. */
    export const inboundSchema = ReadAppVariablesResponse$inboundSchema;
    /** @deprecated use `ReadAppVariablesResponse$outboundSchema` instead. */
    export const outboundSchema = ReadAppVariablesResponse$outboundSchema;
    /** @deprecated use `ReadAppVariablesResponse$Outbound` instead. */
    export type Outbound = ReadAppVariablesResponse$Outbound;
}
