/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { SDKHooks } from "../hooks/hooks.js";
import { SDKOptions, serverURLFromOptions } from "../lib/config.js";
import {
    encodeFormQuery as encodeFormQuery$,
    encodeJSON as encodeJSON$,
    encodeSimple as encodeSimple$,
} from "../lib/encodings.js";
import { HTTPClient } from "../lib/http.js";
import * as schemas$ from "../lib/schemas.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { extractSecurity } from "../lib/security.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";

export class SDKOrchestrationV1 extends ClientSDK {
    private readonly options$: SDKOptions & { hooks?: SDKHooks };

    constructor(options: SDKOptions = {}) {
        const opt = options as unknown;
        let hooks: SDKHooks;
        if (
            typeof opt === "object" &&
            opt != null &&
            "hooks" in opt &&
            opt.hooks instanceof SDKHooks
        ) {
            hooks = opt.hooks;
        } else {
            hooks = new SDKHooks();
        }

        super({
            client: options.httpClient || new HTTPClient(),
            baseURL: serverURLFromOptions(options),
            hooks,
        });

        this.options$ = { ...options, hooks };
        void this.options$;
    }

    /**
     * Get server info
     */
    async flowsgetServerInfo(
        options?: RequestOptions
    ): Promise<operations.FlowsgetServerInfoResponse> {
        const path$ = this.templateURLComponent("/api/orchestration/_info")();

        const query$ = "";

        const headers$ = new Headers({
            Accept: "application/json",
        });

        const security$ = await extractSecurity(this.options$.security);
        const context = {
            operationID: "flowsgetServerInfo",
            oAuth2Scopes: ["auth:read", "orchestration:read"],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const response = await this.do$(request$, {
            context,
            errorCodes: ["4XX", "5XX"],
            retryConfig: options?.retries || this.options$.retryConfig,
            retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
        });

        const [result$] = await this.matcher<operations.FlowsgetServerInfoResponse>()
            .json(200, operations.FlowsgetServerInfoResponse$inboundSchema)
            .fail(["4XX", "5XX"])
            .json("default", operations.FlowsgetServerInfoResponse$inboundSchema)
            .match(response);

        return result$;
    }

    /**
     * List triggers
     *
     * @remarks
     * List triggers
     */
    async listTriggers(
        request: operations.ListTriggersRequest,
        options?: RequestOptions
    ): Promise<operations.ListTriggersResponse> {
        const input$ = typeof request === "undefined" ? {} : request;

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.ListTriggersRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const path$ = this.templateURLComponent("/api/orchestration/triggers")();

        const query$ = encodeFormQuery$({
            name: payload$.name,
        });

        const headers$ = new Headers({
            Accept: "application/json",
        });

        const security$ = await extractSecurity(this.options$.security);
        const context = {
            operationID: "listTriggers",
            oAuth2Scopes: ["auth:read", "orchestration:read"],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const response = await this.do$(request$, {
            context,
            errorCodes: ["4XX", "5XX"],
            retryConfig: options?.retries || this.options$.retryConfig,
            retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
        });

        const [result$] = await this.matcher<operations.ListTriggersResponse>()
            .json(200, operations.ListTriggersResponse$inboundSchema)
            .fail(["4XX", "5XX"])
            .json("default", operations.ListTriggersResponse$inboundSchema)
            .match(response);

        return result$;
    }

    /**
     * Create trigger
     *
     * @remarks
     * Create trigger
     */
    async createTrigger(
        request?: components.TriggerData | undefined,
        options?: RequestOptions
    ): Promise<operations.CreateTriggerResponse> {
        const input$ = request;

        const payload$ = schemas$.parse(
            input$,
            (value$) => components.TriggerData$outboundSchema.optional().parse(value$),
            "Input validation failed"
        );
        const body$ =
            payload$ === undefined ? null : encodeJSON$("body", payload$, { explode: true });

        const path$ = this.templateURLComponent("/api/orchestration/triggers")();

        const query$ = "";

        const headers$ = new Headers({
            "Content-Type": "application/json",
            Accept: "application/json",
        });

        const security$ = await extractSecurity(this.options$.security);
        const context = {
            operationID: "createTrigger",
            oAuth2Scopes: ["auth:read", "orchestration:write"],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "POST",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const response = await this.do$(request$, {
            context,
            errorCodes: ["4XX", "5XX"],
            retryConfig: options?.retries || this.options$.retryConfig,
            retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
        });

        const [result$] = await this.matcher<operations.CreateTriggerResponse>()
            .json(201, operations.CreateTriggerResponse$inboundSchema)
            .fail(["4XX", "5XX"])
            .json("default", operations.CreateTriggerResponse$inboundSchema)
            .match(response);

        return result$;
    }

    /**
     * Read trigger
     *
     * @remarks
     * Read trigger
     */
    async readTrigger(
        request: operations.ReadTriggerRequest,
        options?: RequestOptions
    ): Promise<operations.ReadTriggerResponse> {
        const input$ = request;

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.ReadTriggerRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            triggerID: encodeSimple$("triggerID", payload$.triggerID, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent("/api/orchestration/triggers/{triggerID}")(
            pathParams$
        );

        const query$ = "";

        const headers$ = new Headers({
            Accept: "application/json",
        });

        const security$ = await extractSecurity(this.options$.security);
        const context = {
            operationID: "readTrigger",
            oAuth2Scopes: ["auth:read", "orchestration:read"],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const response = await this.do$(request$, {
            context,
            errorCodes: ["4XX", "5XX"],
            retryConfig: options?.retries || this.options$.retryConfig,
            retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
        });

        const [result$] = await this.matcher<operations.ReadTriggerResponse>()
            .json(200, operations.ReadTriggerResponse$inboundSchema)
            .fail(["4XX", "5XX"])
            .json("default", operations.ReadTriggerResponse$inboundSchema)
            .match(response);

        return result$;
    }

    /**
     * Delete trigger
     *
     * @remarks
     * Read trigger
     */
    async deleteTrigger(
        request: operations.DeleteTriggerRequest,
        options?: RequestOptions
    ): Promise<components.ErrorT | undefined> {
        const input$ = request;

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.DeleteTriggerRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            triggerID: encodeSimple$("triggerID", payload$.triggerID, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent("/api/orchestration/triggers/{triggerID}")(
            pathParams$
        );

        const query$ = "";

        const headers$ = new Headers({
            Accept: "application/json",
        });

        const security$ = await extractSecurity(this.options$.security);
        const context = {
            operationID: "deleteTrigger",
            oAuth2Scopes: ["auth:read", "orchestration:write"],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "DELETE",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const response = await this.do$(request$, {
            context,
            errorCodes: ["4XX", "5XX"],
            retryConfig: options?.retries || this.options$.retryConfig,
            retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
        });

        const [result$] = await this.matcher<components.ErrorT | undefined>()
            .void(204, components.ErrorT$inboundSchema.optional())
            .fail(["4XX", "5XX"])
            .json("default", components.ErrorT$inboundSchema.optional())
            .match(response);

        return result$;
    }

    /**
     * List triggers occurrences
     *
     * @remarks
     * List triggers occurrences
     */
    async listTriggersOccurrences(
        request: operations.ListTriggersOccurrencesRequest,
        options?: RequestOptions
    ): Promise<operations.ListTriggersOccurrencesResponse> {
        const input$ = request;

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.ListTriggersOccurrencesRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            triggerID: encodeSimple$("triggerID", payload$.triggerID, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent(
            "/api/orchestration/triggers/{triggerID}/occurrences"
        )(pathParams$);

        const query$ = "";

        const headers$ = new Headers({
            Accept: "application/json",
        });

        const security$ = await extractSecurity(this.options$.security);
        const context = {
            operationID: "listTriggersOccurrences",
            oAuth2Scopes: ["auth:read", "orchestration:read"],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const response = await this.do$(request$, {
            context,
            errorCodes: ["4XX", "5XX"],
            retryConfig: options?.retries || this.options$.retryConfig,
            retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
        });

        const [result$] = await this.matcher<operations.ListTriggersOccurrencesResponse>()
            .json(200, operations.ListTriggersOccurrencesResponse$inboundSchema)
            .fail(["4XX", "5XX"])
            .json("default", operations.ListTriggersOccurrencesResponse$inboundSchema)
            .match(response);

        return result$;
    }

    /**
     * List registered workflows
     *
     * @remarks
     * List registered workflows
     */
    async listWorkflows(options?: RequestOptions): Promise<operations.ListWorkflowsResponse> {
        const path$ = this.templateURLComponent("/api/orchestration/workflows")();

        const query$ = "";

        const headers$ = new Headers({
            Accept: "application/json",
        });

        const security$ = await extractSecurity(this.options$.security);
        const context = {
            operationID: "listWorkflows",
            oAuth2Scopes: ["auth:read", "orchestration:read"],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const response = await this.do$(request$, {
            context,
            errorCodes: ["4XX", "5XX"],
            retryConfig: options?.retries || this.options$.retryConfig,
            retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
        });

        const [result$] = await this.matcher<operations.ListWorkflowsResponse>()
            .json(200, operations.ListWorkflowsResponse$inboundSchema)
            .fail(["4XX", "5XX"])
            .json("default", operations.ListWorkflowsResponse$inboundSchema)
            .match(response);

        return result$;
    }

    /**
     * Create workflow
     *
     * @remarks
     * Create a workflow
     */
    async createWorkflow(
        request?: components.CreateWorkflowRequest | undefined,
        options?: RequestOptions
    ): Promise<operations.CreateWorkflowResponse> {
        const input$ = request;

        const payload$ = schemas$.parse(
            input$,
            (value$) => components.CreateWorkflowRequest$outboundSchema.optional().parse(value$),
            "Input validation failed"
        );
        const body$ =
            payload$ === undefined ? null : encodeJSON$("body", payload$, { explode: true });

        const path$ = this.templateURLComponent("/api/orchestration/workflows")();

        const query$ = "";

        const headers$ = new Headers({
            "Content-Type": "application/json",
            Accept: "application/json",
        });

        const security$ = await extractSecurity(this.options$.security);
        const context = {
            operationID: "createWorkflow",
            oAuth2Scopes: ["auth:read", "orchestration:write"],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "POST",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const response = await this.do$(request$, {
            context,
            errorCodes: ["4XX", "5XX"],
            retryConfig: options?.retries || this.options$.retryConfig,
            retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
        });

        const [result$] = await this.matcher<operations.CreateWorkflowResponse>()
            .json(201, operations.CreateWorkflowResponse$inboundSchema)
            .fail(["4XX", "5XX"])
            .json("default", operations.CreateWorkflowResponse$inboundSchema)
            .match(response);

        return result$;
    }

    /**
     * Get a flow by id
     *
     * @remarks
     * Get a flow by id
     */
    async getWorkflow(
        request: operations.GetWorkflowRequest,
        options?: RequestOptions
    ): Promise<operations.GetWorkflowResponse> {
        const input$ = request;

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.GetWorkflowRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            flowId: encodeSimple$("flowId", payload$.flowId, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent("/api/orchestration/workflows/{flowId}")(
            pathParams$
        );

        const query$ = "";

        const headers$ = new Headers({
            Accept: "application/json",
        });

        const security$ = await extractSecurity(this.options$.security);
        const context = {
            operationID: "getWorkflow",
            oAuth2Scopes: ["auth:read", "orchestration:read"],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const response = await this.do$(request$, {
            context,
            errorCodes: ["4XX", "5XX"],
            retryConfig: options?.retries || this.options$.retryConfig,
            retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
        });

        const [result$] = await this.matcher<operations.GetWorkflowResponse>()
            .json(200, operations.GetWorkflowResponse$inboundSchema)
            .fail(["4XX", "5XX"])
            .json("default", operations.GetWorkflowResponse$inboundSchema)
            .match(response);

        return result$;
    }

    /**
     * Delete a flow by id
     *
     * @remarks
     * Delete a flow by id
     */
    async deleteWorkflow(
        request: operations.DeleteWorkflowRequest,
        options?: RequestOptions
    ): Promise<components.ErrorT | undefined> {
        const input$ = request;

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.DeleteWorkflowRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            flowId: encodeSimple$("flowId", payload$.flowId, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent("/api/orchestration/workflows/{flowId}")(
            pathParams$
        );

        const query$ = "";

        const headers$ = new Headers({
            Accept: "application/json",
        });

        const security$ = await extractSecurity(this.options$.security);
        const context = {
            operationID: "deleteWorkflow",
            oAuth2Scopes: ["auth:read", "orchestration:write"],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "DELETE",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const response = await this.do$(request$, {
            context,
            errorCodes: ["4XX", "5XX"],
            retryConfig: options?.retries || this.options$.retryConfig,
            retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
        });

        const [result$] = await this.matcher<components.ErrorT | undefined>()
            .void(204, components.ErrorT$inboundSchema.optional())
            .fail(["4XX", "5XX"])
            .json("default", components.ErrorT$inboundSchema.optional())
            .match(response);

        return result$;
    }

    /**
     * Run workflow
     *
     * @remarks
     * Run workflow
     */
    async runWorkflow(
        request: operations.RunWorkflowRequest,
        options?: RequestOptions
    ): Promise<operations.RunWorkflowResponse> {
        const input$ = request;

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.RunWorkflowRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = encodeJSON$("body", payload$.RequestBody, { explode: true });

        const pathParams$ = {
            workflowID: encodeSimple$("workflowID", payload$.workflowID, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent(
            "/api/orchestration/workflows/{workflowID}/instances"
        )(pathParams$);

        const query$ = encodeFormQuery$({
            wait: payload$.wait,
        });

        const headers$ = new Headers({
            "Content-Type": "application/json",
            Accept: "application/json",
        });

        const security$ = await extractSecurity(this.options$.security);
        const context = {
            operationID: "runWorkflow",
            oAuth2Scopes: ["auth:read", "orchestration:write"],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "POST",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const response = await this.do$(request$, {
            context,
            errorCodes: ["4XX", "5XX"],
            retryConfig: options?.retries || this.options$.retryConfig,
            retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
        });

        const [result$] = await this.matcher<operations.RunWorkflowResponse>()
            .json(201, operations.RunWorkflowResponse$inboundSchema)
            .fail(["4XX", "5XX"])
            .json("default", operations.RunWorkflowResponse$inboundSchema)
            .match(response);

        return result$;
    }

    /**
     * List instances of a workflow
     *
     * @remarks
     * List instances of a workflow
     */
    async listInstances(
        request: operations.ListInstancesRequest,
        options?: RequestOptions
    ): Promise<operations.ListInstancesResponse> {
        const input$ = typeof request === "undefined" ? {} : request;

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.ListInstancesRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const path$ = this.templateURLComponent("/api/orchestration/instances")();

        const query$ = encodeFormQuery$({
            running: payload$.running,
            workflowID: payload$.workflowID,
        });

        const headers$ = new Headers({
            Accept: "application/json",
        });

        const security$ = await extractSecurity(this.options$.security);
        const context = {
            operationID: "listInstances",
            oAuth2Scopes: ["auth:read", "orchestration:read"],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const response = await this.do$(request$, {
            context,
            errorCodes: ["4XX", "5XX"],
            retryConfig: options?.retries || this.options$.retryConfig,
            retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
        });

        const [result$] = await this.matcher<operations.ListInstancesResponse>()
            .json(200, operations.ListInstancesResponse$inboundSchema)
            .fail(["4XX", "5XX"])
            .json("default", operations.ListInstancesResponse$inboundSchema)
            .match(response);

        return result$;
    }

    /**
     * Get a workflow instance by id
     *
     * @remarks
     * Get a workflow instance by id
     */
    async getInstance(
        request: operations.GetInstanceRequest,
        options?: RequestOptions
    ): Promise<operations.GetInstanceResponse> {
        const input$ = request;

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.GetInstanceRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            instanceID: encodeSimple$("instanceID", payload$.instanceID, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent("/api/orchestration/instances/{instanceID}")(
            pathParams$
        );

        const query$ = "";

        const headers$ = new Headers({
            Accept: "application/json",
        });

        const security$ = await extractSecurity(this.options$.security);
        const context = {
            operationID: "getInstance",
            oAuth2Scopes: ["auth:read", "orchestration:read"],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const response = await this.do$(request$, {
            context,
            errorCodes: ["4XX", "5XX"],
            retryConfig: options?.retries || this.options$.retryConfig,
            retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
        });

        const [result$] = await this.matcher<operations.GetInstanceResponse>()
            .json(200, operations.GetInstanceResponse$inboundSchema)
            .fail(["4XX", "5XX"])
            .json("default", operations.GetInstanceResponse$inboundSchema)
            .match(response);

        return result$;
    }

    /**
     * Send an event to a running workflow
     *
     * @remarks
     * Send an event to a running workflow
     */
    async sendEvent(
        request: operations.SendEventRequest,
        options?: RequestOptions
    ): Promise<components.ErrorT | undefined> {
        const input$ = request;

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.SendEventRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = encodeJSON$("body", payload$.RequestBody, { explode: true });

        const pathParams$ = {
            instanceID: encodeSimple$("instanceID", payload$.instanceID, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent("/api/orchestration/instances/{instanceID}/events")(
            pathParams$
        );

        const query$ = "";

        const headers$ = new Headers({
            "Content-Type": "application/json",
            Accept: "application/json",
        });

        const security$ = await extractSecurity(this.options$.security);
        const context = {
            operationID: "sendEvent",
            oAuth2Scopes: ["auth:read", "orchestration:write"],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "POST",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const response = await this.do$(request$, {
            context,
            errorCodes: ["4XX", "5XX"],
            retryConfig: options?.retries || this.options$.retryConfig,
            retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
        });

        const [result$] = await this.matcher<components.ErrorT | undefined>()
            .void(204, components.ErrorT$inboundSchema.optional())
            .fail(["4XX", "5XX"])
            .json("default", components.ErrorT$inboundSchema.optional())
            .match(response);

        return result$;
    }

    /**
     * Cancel a running workflow
     *
     * @remarks
     * Cancel a running workflow
     */
    async cancelEvent(
        request: operations.CancelEventRequest,
        options?: RequestOptions
    ): Promise<components.ErrorT | undefined> {
        const input$ = request;

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.CancelEventRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            instanceID: encodeSimple$("instanceID", payload$.instanceID, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent("/api/orchestration/instances/{instanceID}/abort")(
            pathParams$
        );

        const query$ = "";

        const headers$ = new Headers({
            Accept: "application/json",
        });

        const security$ = await extractSecurity(this.options$.security);
        const context = {
            operationID: "cancelEvent",
            oAuth2Scopes: ["auth:read", "orchestration:write"],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "PUT",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const response = await this.do$(request$, {
            context,
            errorCodes: ["4XX", "5XX"],
            retryConfig: options?.retries || this.options$.retryConfig,
            retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
        });

        const [result$] = await this.matcher<components.ErrorT | undefined>()
            .void(204, components.ErrorT$inboundSchema.optional())
            .fail(["4XX", "5XX"])
            .json("default", components.ErrorT$inboundSchema.optional())
            .match(response);

        return result$;
    }

    /**
     * Get a workflow instance history by id
     *
     * @remarks
     * Get a workflow instance history by id
     */
    async getInstanceHistory(
        request: operations.GetInstanceHistoryRequest,
        options?: RequestOptions
    ): Promise<operations.GetInstanceHistoryResponse> {
        const input$ = request;

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.GetInstanceHistoryRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            instanceID: encodeSimple$("instanceID", payload$.instanceID, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent(
            "/api/orchestration/instances/{instanceID}/history"
        )(pathParams$);

        const query$ = "";

        const headers$ = new Headers({
            Accept: "application/json",
        });

        const security$ = await extractSecurity(this.options$.security);
        const context = {
            operationID: "getInstanceHistory",
            oAuth2Scopes: ["auth:read", "orchestration:read"],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const response = await this.do$(request$, {
            context,
            errorCodes: ["4XX", "5XX"],
            retryConfig: options?.retries || this.options$.retryConfig,
            retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
        });

        const [result$] = await this.matcher<operations.GetInstanceHistoryResponse>()
            .json(200, operations.GetInstanceHistoryResponse$inboundSchema)
            .fail(["4XX", "5XX"])
            .json("default", operations.GetInstanceHistoryResponse$inboundSchema)
            .match(response);

        return result$;
    }

    /**
     * Get a workflow instance stage history
     *
     * @remarks
     * Get a workflow instance stage history
     */
    async getInstanceStageHistory(
        request: operations.GetInstanceStageHistoryRequest,
        options?: RequestOptions
    ): Promise<operations.GetInstanceStageHistoryResponse> {
        const input$ = request;

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.GetInstanceStageHistoryRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            instanceID: encodeSimple$("instanceID", payload$.instanceID, {
                explode: false,
                charEncoding: "percent",
            }),
            number: encodeSimple$("number", payload$.number, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent(
            "/api/orchestration/instances/{instanceID}/stages/{number}/history"
        )(pathParams$);

        const query$ = "";

        const headers$ = new Headers({
            Accept: "application/json",
        });

        const security$ = await extractSecurity(this.options$.security);
        const context = {
            operationID: "getInstanceStageHistory",
            oAuth2Scopes: ["auth:read", "orchestration:read"],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const response = await this.do$(request$, {
            context,
            errorCodes: ["4XX", "5XX"],
            retryConfig: options?.retries || this.options$.retryConfig,
            retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
        });

        const [result$] = await this.matcher<operations.GetInstanceStageHistoryResponse>()
            .json(200, operations.GetInstanceStageHistoryResponse$inboundSchema)
            .fail(["4XX", "5XX"])
            .json("default", operations.GetInstanceStageHistoryResponse$inboundSchema)
            .match(response);

        return result$;
    }
}
