export const OAUTH_CLIENTS_ACTION_CREATE_CLIENT = 'CREATE_CLIENT_FORM';
export const OAUTH_CLIENTS_ACTION_DELETE_CLIENT = 'DELETE_CLIENT_FORM';
export const OAUTH_CLIENTS_ACTION_CREATE_SECRET = 'CREATE_SECRET_FORM';
export const OAUTH_CLIENTS_ACTION_DELETE_SECRET = 'DELETE_SECRET_FORM';
