/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type ConnectorsTransferRequest = {
    /**
     * The name of the connector.
     */
    connector: components.Connector;
    transferRequest: components.TransferRequest;
};

export type ConnectorsTransferResponse =
    | components.TransferResponse
    | components.PaymentsErrorResponse;

/** @internal */
export const ConnectorsTransferRequest$inboundSchema: z.ZodType<
    ConnectorsTransferRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        connector: components.Connector$inboundSchema,
        TransferRequest: components.TransferRequest$inboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            TransferRequest: "transferRequest",
        });
    });

/** @internal */
export type ConnectorsTransferRequest$Outbound = {
    connector: string;
    TransferRequest: components.TransferRequest$Outbound;
};

/** @internal */
export const ConnectorsTransferRequest$outboundSchema: z.ZodType<
    ConnectorsTransferRequest$Outbound,
    z.ZodTypeDef,
    ConnectorsTransferRequest
> = z
    .object({
        connector: components.Connector$outboundSchema,
        transferRequest: components.TransferRequest$outboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            transferRequest: "TransferRequest",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConnectorsTransferRequest$ {
    /** @deprecated use `ConnectorsTransferRequest$inboundSchema` instead. */
    export const inboundSchema = ConnectorsTransferRequest$inboundSchema;
    /** @deprecated use `ConnectorsTransferRequest$outboundSchema` instead. */
    export const outboundSchema = ConnectorsTransferRequest$outboundSchema;
    /** @deprecated use `ConnectorsTransferRequest$Outbound` instead. */
    export type Outbound = ConnectorsTransferRequest$Outbound;
}

/** @internal */
export const ConnectorsTransferResponse$inboundSchema: z.ZodType<
    ConnectorsTransferResponse,
    z.ZodTypeDef,
    unknown
> = z.union([
    components.TransferResponse$inboundSchema,
    components.PaymentsErrorResponse$inboundSchema,
]);

/** @internal */
export type ConnectorsTransferResponse$Outbound =
    | components.TransferResponse$Outbound
    | components.PaymentsErrorResponse$Outbound;

/** @internal */
export const ConnectorsTransferResponse$outboundSchema: z.ZodType<
    ConnectorsTransferResponse$Outbound,
    z.ZodTypeDef,
    ConnectorsTransferResponse
> = z.union([
    components.TransferResponse$outboundSchema,
    components.PaymentsErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConnectorsTransferResponse$ {
    /** @deprecated use `ConnectorsTransferResponse$inboundSchema` instead. */
    export const inboundSchema = ConnectorsTransferResponse$inboundSchema;
    /** @deprecated use `ConnectorsTransferResponse$outboundSchema` instead. */
    export const outboundSchema = ConnectorsTransferResponse$outboundSchema;
    /** @deprecated use `ConnectorsTransferResponse$Outbound` instead. */
    export type Outbound = ConnectorsTransferResponse$Outbound;
}
