/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as errors from "../errors/index.js";
import * as z from "zod";

export type CountAccountsRequest = {
    /**
     * Name of the ledger.
     */
    ledger: string;
    /**
     * Filter accounts by address pattern (regular expression placed between ^ and $).
     */
    address?: string | undefined;
    /**
     * Filter accounts by metadata key value pairs. The filter can be used like this metadata[key]=value1&metadata[a.nested.key]=value2
     */
    metadata?: { [k: string]: any } | undefined;
};

export type CountAccountsResponse = {
    headers: { [k: string]: Array<string> };
    result: errors.ErrorResponse;
};

/** @internal */
export const CountAccountsRequest$inboundSchema: z.ZodType<
    CountAccountsRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    ledger: z.string(),
    address: z.string().optional(),
    metadata: z.record(z.any()).optional(),
});

/** @internal */
export type CountAccountsRequest$Outbound = {
    ledger: string;
    address?: string | undefined;
    metadata?: { [k: string]: any } | undefined;
};

/** @internal */
export const CountAccountsRequest$outboundSchema: z.ZodType<
    CountAccountsRequest$Outbound,
    z.ZodTypeDef,
    CountAccountsRequest
> = z.object({
    ledger: z.string(),
    address: z.string().optional(),
    metadata: z.record(z.any()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CountAccountsRequest$ {
    /** @deprecated use `CountAccountsRequest$inboundSchema` instead. */
    export const inboundSchema = CountAccountsRequest$inboundSchema;
    /** @deprecated use `CountAccountsRequest$outboundSchema` instead. */
    export const outboundSchema = CountAccountsRequest$outboundSchema;
    /** @deprecated use `CountAccountsRequest$Outbound` instead. */
    export type Outbound = CountAccountsRequest$Outbound;
}

/** @internal */
export const CountAccountsResponse$inboundSchema: z.ZodType<
    CountAccountsResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        Headers: z.record(z.array(z.string())),
        Result: errors.ErrorResponse$inboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            Headers: "headers",
            Result: "result",
        });
    });

/** @internal */
export type CountAccountsResponse$Outbound = {
    Headers: { [k: string]: Array<string> };
    Result: errors.ErrorResponse$Outbound;
};

/** @internal */
export const CountAccountsResponse$outboundSchema: z.ZodType<
    CountAccountsResponse$Outbound,
    z.ZodTypeDef,
    CountAccountsResponse
> = z
    .object({
        headers: z.record(z.array(z.string())),
        result: errors.ErrorResponse$outboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            headers: "Headers",
            result: "Result",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CountAccountsResponse$ {
    /** @deprecated use `CountAccountsResponse$inboundSchema` instead. */
    export const inboundSchema = CountAccountsResponse$inboundSchema;
    /** @deprecated use `CountAccountsResponse$outboundSchema` instead. */
    export const outboundSchema = CountAccountsResponse$outboundSchema;
    /** @deprecated use `CountAccountsResponse$Outbound` instead. */
    export type Outbound = CountAccountsResponse$Outbound;
}
