/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type DebitWalletRequest = {
    id: string;
    /**
     * Use an idempotency key
     */
    idempotencyKey?: string | undefined;
    debitWalletRequest?: components.DebitWalletRequest | undefined;
};

export type DebitWalletResponse = components.DebitWalletResponse | components.WalletsErrorResponse;

/** @internal */
export const DebitWalletRequest$inboundSchema: z.ZodType<
    DebitWalletRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        id: z.string(),
        "Idempotency-Key": z.string().optional(),
        DebitWalletRequest: components.DebitWalletRequest$inboundSchema.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            "Idempotency-Key": "idempotencyKey",
            DebitWalletRequest: "debitWalletRequest",
        });
    });

/** @internal */
export type DebitWalletRequest$Outbound = {
    id: string;
    "Idempotency-Key"?: string | undefined;
    DebitWalletRequest?: components.DebitWalletRequest$Outbound | undefined;
};

/** @internal */
export const DebitWalletRequest$outboundSchema: z.ZodType<
    DebitWalletRequest$Outbound,
    z.ZodTypeDef,
    DebitWalletRequest
> = z
    .object({
        id: z.string(),
        idempotencyKey: z.string().optional(),
        debitWalletRequest: components.DebitWalletRequest$outboundSchema.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            idempotencyKey: "Idempotency-Key",
            debitWalletRequest: "DebitWalletRequest",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DebitWalletRequest$ {
    /** @deprecated use `DebitWalletRequest$inboundSchema` instead. */
    export const inboundSchema = DebitWalletRequest$inboundSchema;
    /** @deprecated use `DebitWalletRequest$outboundSchema` instead. */
    export const outboundSchema = DebitWalletRequest$outboundSchema;
    /** @deprecated use `DebitWalletRequest$Outbound` instead. */
    export type Outbound = DebitWalletRequest$Outbound;
}

/** @internal */
export const DebitWalletResponse$inboundSchema: z.ZodType<
    DebitWalletResponse,
    z.ZodTypeDef,
    unknown
> = z.union([
    components.DebitWalletResponse$inboundSchema,
    components.WalletsErrorResponse$inboundSchema,
]);

/** @internal */
export type DebitWalletResponse$Outbound =
    | components.DebitWalletResponse$Outbound
    | components.WalletsErrorResponse$Outbound;

/** @internal */
export const DebitWalletResponse$outboundSchema: z.ZodType<
    DebitWalletResponse$Outbound,
    z.ZodTypeDef,
    DebitWalletResponse
> = z.union([
    components.DebitWalletResponse$outboundSchema,
    components.WalletsErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DebitWalletResponse$ {
    /** @deprecated use `DebitWalletResponse$inboundSchema` instead. */
    export const inboundSchema = DebitWalletResponse$inboundSchema;
    /** @deprecated use `DebitWalletResponse$outboundSchema` instead. */
    export const outboundSchema = DebitWalletResponse$outboundSchema;
    /** @deprecated use `DebitWalletResponse$Outbound` instead. */
    export type Outbound = DebitWalletResponse$Outbound;
}
