/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteTriggerRequest = {
    /**
     * The trigger id
     */
    triggerID: string;
};

/** @internal */
export const DeleteTriggerRequest$inboundSchema: z.ZodType<
    DeleteTriggerRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    triggerID: z.string(),
});

/** @internal */
export type DeleteTriggerRequest$Outbound = {
    triggerID: string;
};

/** @internal */
export const DeleteTriggerRequest$outboundSchema: z.ZodType<
    DeleteTriggerRequest$Outbound,
    z.ZodTypeDef,
    DeleteTriggerRequest
> = z.object({
    triggerID: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteTriggerRequest$ {
    /** @deprecated use `DeleteTriggerRequest$inboundSchema` instead. */
    export const inboundSchema = DeleteTriggerRequest$inboundSchema;
    /** @deprecated use `DeleteTriggerRequest$outboundSchema` instead. */
    export const outboundSchema = DeleteTriggerRequest$outboundSchema;
    /** @deprecated use `DeleteTriggerRequest$Outbound` instead. */
    export type Outbound = DeleteTriggerRequest$Outbound;
}
