/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export type GetHoldRequest = {
    /**
     * The hold ID
     */
    holdID: string;
};

export type GetHoldResponse = components.GetHoldResponse | components.WalletsErrorResponse;

/** @internal */
export const GetHoldRequest$inboundSchema: z.ZodType<GetHoldRequest, z.ZodTypeDef, unknown> =
    z.object({
        holdID: z.string(),
    });

/** @internal */
export type GetHoldRequest$Outbound = {
    holdID: string;
};

/** @internal */
export const GetHoldRequest$outboundSchema: z.ZodType<
    GetHoldRequest$Outbound,
    z.ZodTypeDef,
    GetHoldRequest
> = z.object({
    holdID: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetHoldRequest$ {
    /** @deprecated use `GetHoldRequest$inboundSchema` instead. */
    export const inboundSchema = GetHoldRequest$inboundSchema;
    /** @deprecated use `GetHoldRequest$outboundSchema` instead. */
    export const outboundSchema = GetHoldRequest$outboundSchema;
    /** @deprecated use `GetHoldRequest$Outbound` instead. */
    export type Outbound = GetHoldRequest$Outbound;
}

/** @internal */
export const GetHoldResponse$inboundSchema: z.ZodType<GetHoldResponse, z.ZodTypeDef, unknown> =
    z.union([
        components.GetHoldResponse$inboundSchema,
        components.WalletsErrorResponse$inboundSchema,
    ]);

/** @internal */
export type GetHoldResponse$Outbound =
    | components.GetHoldResponse$Outbound
    | components.WalletsErrorResponse$Outbound;

/** @internal */
export const GetHoldResponse$outboundSchema: z.ZodType<
    GetHoldResponse$Outbound,
    z.ZodTypeDef,
    GetHoldResponse
> = z.union([
    components.GetHoldResponse$outboundSchema,
    components.WalletsErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetHoldResponse$ {
    /** @deprecated use `GetHoldResponse$inboundSchema` instead. */
    export const inboundSchema = GetHoldResponse$inboundSchema;
    /** @deprecated use `GetHoldResponse$outboundSchema` instead. */
    export const outboundSchema = GetHoldResponse$outboundSchema;
    /** @deprecated use `GetHoldResponse$Outbound` instead. */
    export type Outbound = GetHoldResponse$Outbound;
}
