/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export type GetHoldsRequest = {
    /**
     * The maximum number of results to return per page
     */
    pageSize?: number | undefined;
    /**
     * The wallet to filter on
     */
    walletID?: string | undefined;
    /**
     * Filter holds by metadata key value pairs. Nested objects can be used as seen in the example below.
     */
    metadata?: { [k: string]: string } | undefined;
    /**
     * Parameter used in pagination requests.
     *
     * @remarks
     * Set to the value of next for the next page of results.
     * Set to the value of previous for the previous page of results.
     * No other parameters can be set when the pagination token is set.
     *
     */
    cursor?: string | undefined;
};

export type GetHoldsResponse = components.GetHoldsResponse | components.WalletsErrorResponse;

/** @internal */
export const GetHoldsRequest$inboundSchema: z.ZodType<GetHoldsRequest, z.ZodTypeDef, unknown> =
    z.object({
        pageSize: z.number().int().default(15),
        walletID: z.string().optional(),
        metadata: z.record(z.string()).optional(),
        cursor: z.string().optional(),
    });

/** @internal */
export type GetHoldsRequest$Outbound = {
    pageSize: number;
    walletID?: string | undefined;
    metadata?: { [k: string]: string } | undefined;
    cursor?: string | undefined;
};

/** @internal */
export const GetHoldsRequest$outboundSchema: z.ZodType<
    GetHoldsRequest$Outbound,
    z.ZodTypeDef,
    GetHoldsRequest
> = z.object({
    pageSize: z.number().int().default(15),
    walletID: z.string().optional(),
    metadata: z.record(z.string()).optional(),
    cursor: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetHoldsRequest$ {
    /** @deprecated use `GetHoldsRequest$inboundSchema` instead. */
    export const inboundSchema = GetHoldsRequest$inboundSchema;
    /** @deprecated use `GetHoldsRequest$outboundSchema` instead. */
    export const outboundSchema = GetHoldsRequest$outboundSchema;
    /** @deprecated use `GetHoldsRequest$Outbound` instead. */
    export type Outbound = GetHoldsRequest$Outbound;
}

/** @internal */
export const GetHoldsResponse$inboundSchema: z.ZodType<GetHoldsResponse, z.ZodTypeDef, unknown> =
    z.union([
        components.GetHoldsResponse$inboundSchema,
        components.WalletsErrorResponse$inboundSchema,
    ]);

/** @internal */
export type GetHoldsResponse$Outbound =
    | components.GetHoldsResponse$Outbound
    | components.WalletsErrorResponse$Outbound;

/** @internal */
export const GetHoldsResponse$outboundSchema: z.ZodType<
    GetHoldsResponse$Outbound,
    z.ZodTypeDef,
    GetHoldsResponse
> = z.union([
    components.GetHoldsResponse$outboundSchema,
    components.WalletsErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetHoldsResponse$ {
    /** @deprecated use `GetHoldsResponse$inboundSchema` instead. */
    export const inboundSchema = GetHoldsResponse$inboundSchema;
    /** @deprecated use `GetHoldsResponse$outboundSchema` instead. */
    export const outboundSchema = GetHoldsResponse$outboundSchema;
    /** @deprecated use `GetHoldsResponse$Outbound` instead. */
    export type Outbound = GetHoldsResponse$Outbound;
}
