/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as errors from "../errors/index.js";
import * as z from "zod";

export type GetLedgerInfoRequest = {
    /**
     * Name of the ledger.
     */
    ledger: string;
};

export type GetLedgerInfoResponse = components.LedgerInfoResponse | errors.ErrorResponse;

/** @internal */
export const GetLedgerInfoRequest$inboundSchema: z.ZodType<
    GetLedgerInfoRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    ledger: z.string(),
});

/** @internal */
export type GetLedgerInfoRequest$Outbound = {
    ledger: string;
};

/** @internal */
export const GetLedgerInfoRequest$outboundSchema: z.ZodType<
    GetLedgerInfoRequest$Outbound,
    z.ZodTypeDef,
    GetLedgerInfoRequest
> = z.object({
    ledger: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetLedgerInfoRequest$ {
    /** @deprecated use `GetLedgerInfoRequest$inboundSchema` instead. */
    export const inboundSchema = GetLedgerInfoRequest$inboundSchema;
    /** @deprecated use `GetLedgerInfoRequest$outboundSchema` instead. */
    export const outboundSchema = GetLedgerInfoRequest$outboundSchema;
    /** @deprecated use `GetLedgerInfoRequest$Outbound` instead. */
    export type Outbound = GetLedgerInfoRequest$Outbound;
}

/** @internal */
export const GetLedgerInfoResponse$inboundSchema: z.ZodType<
    GetLedgerInfoResponse,
    z.ZodTypeDef,
    unknown
> = z.union([components.LedgerInfoResponse$inboundSchema, errors.ErrorResponse$inboundSchema]);

/** @internal */
export type GetLedgerInfoResponse$Outbound =
    | components.LedgerInfoResponse$Outbound
    | errors.ErrorResponse$Outbound;

/** @internal */
export const GetLedgerInfoResponse$outboundSchema: z.ZodType<
    GetLedgerInfoResponse$Outbound,
    z.ZodTypeDef,
    GetLedgerInfoResponse
> = z.union([components.LedgerInfoResponse$outboundSchema, errors.ErrorResponse$outboundSchema]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetLedgerInfoResponse$ {
    /** @deprecated use `GetLedgerInfoResponse$inboundSchema` instead. */
    export const inboundSchema = GetLedgerInfoResponse$inboundSchema;
    /** @deprecated use `GetLedgerInfoResponse$outboundSchema` instead. */
    export const outboundSchema = GetLedgerInfoResponse$outboundSchema;
    /** @deprecated use `GetLedgerInfoResponse$Outbound` instead. */
    export type Outbound = GetLedgerInfoResponse$Outbound;
}
