/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export type GetPoolRequest = {
    /**
     * The pool ID.
     */
    poolId: string;
};

export type GetPoolResponse = components.PoolResponse | components.PaymentsErrorResponse;

/** @internal */
export const GetPoolRequest$inboundSchema: z.ZodType<GetPoolRequest, z.ZodTypeDef, unknown> =
    z.object({
        poolId: z.string(),
    });

/** @internal */
export type GetPoolRequest$Outbound = {
    poolId: string;
};

/** @internal */
export const GetPoolRequest$outboundSchema: z.ZodType<
    GetPoolRequest$Outbound,
    z.ZodTypeDef,
    GetPoolRequest
> = z.object({
    poolId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPoolRequest$ {
    /** @deprecated use `GetPoolRequest$inboundSchema` instead. */
    export const inboundSchema = GetPoolRequest$inboundSchema;
    /** @deprecated use `GetPoolRequest$outboundSchema` instead. */
    export const outboundSchema = GetPoolRequest$outboundSchema;
    /** @deprecated use `GetPoolRequest$Outbound` instead. */
    export type Outbound = GetPoolRequest$Outbound;
}

/** @internal */
export const GetPoolResponse$inboundSchema: z.ZodType<GetPoolResponse, z.ZodTypeDef, unknown> =
    z.union([
        components.PoolResponse$inboundSchema,
        components.PaymentsErrorResponse$inboundSchema,
    ]);

/** @internal */
export type GetPoolResponse$Outbound =
    | components.PoolResponse$Outbound
    | components.PaymentsErrorResponse$Outbound;

/** @internal */
export const GetPoolResponse$outboundSchema: z.ZodType<
    GetPoolResponse$Outbound,
    z.ZodTypeDef,
    GetPoolResponse
> = z.union([
    components.PoolResponse$outboundSchema,
    components.PaymentsErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPoolResponse$ {
    /** @deprecated use `GetPoolResponse$inboundSchema` instead. */
    export const inboundSchema = GetPoolResponse$inboundSchema;
    /** @deprecated use `GetPoolResponse$outboundSchema` instead. */
    export const outboundSchema = GetPoolResponse$outboundSchema;
    /** @deprecated use `GetPoolResponse$Outbound` instead. */
    export type Outbound = GetPoolResponse$Outbound;
}
