/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export type GetTransferInitiationRequest = {
    /**
     * The transfer ID.
     */
    transferId: string;
};

export type GetTransferInitiationResponse =
    | components.TransferInitiationResponse
    | components.PaymentsErrorResponse;

/** @internal */
export const GetTransferInitiationRequest$inboundSchema: z.ZodType<
    GetTransferInitiationRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    transferId: z.string(),
});

/** @internal */
export type GetTransferInitiationRequest$Outbound = {
    transferId: string;
};

/** @internal */
export const GetTransferInitiationRequest$outboundSchema: z.ZodType<
    GetTransferInitiationRequest$Outbound,
    z.ZodTypeDef,
    GetTransferInitiationRequest
> = z.object({
    transferId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTransferInitiationRequest$ {
    /** @deprecated use `GetTransferInitiationRequest$inboundSchema` instead. */
    export const inboundSchema = GetTransferInitiationRequest$inboundSchema;
    /** @deprecated use `GetTransferInitiationRequest$outboundSchema` instead. */
    export const outboundSchema = GetTransferInitiationRequest$outboundSchema;
    /** @deprecated use `GetTransferInitiationRequest$Outbound` instead. */
    export type Outbound = GetTransferInitiationRequest$Outbound;
}

/** @internal */
export const GetTransferInitiationResponse$inboundSchema: z.ZodType<
    GetTransferInitiationResponse,
    z.ZodTypeDef,
    unknown
> = z.union([
    components.TransferInitiationResponse$inboundSchema,
    components.PaymentsErrorResponse$inboundSchema,
]);

/** @internal */
export type GetTransferInitiationResponse$Outbound =
    | components.TransferInitiationResponse$Outbound
    | components.PaymentsErrorResponse$Outbound;

/** @internal */
export const GetTransferInitiationResponse$outboundSchema: z.ZodType<
    GetTransferInitiationResponse$Outbound,
    z.ZodTypeDef,
    GetTransferInitiationResponse
> = z.union([
    components.TransferInitiationResponse$outboundSchema,
    components.PaymentsErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTransferInitiationResponse$ {
    /** @deprecated use `GetTransferInitiationResponse$inboundSchema` instead. */
    export const inboundSchema = GetTransferInitiationResponse$inboundSchema;
    /** @deprecated use `GetTransferInitiationResponse$outboundSchema` instead. */
    export const outboundSchema = GetTransferInitiationResponse$outboundSchema;
    /** @deprecated use `GetTransferInitiationResponse$Outbound` instead. */
    export type Outbound = GetTransferInitiationResponse$Outbound;
}
