/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export type GetWorkflowRequest = {
    /**
     * The flow id
     */
    flowId: string;
};

export type GetWorkflowResponse = components.GetWorkflowResponse | components.ErrorT;

/** @internal */
export const GetWorkflowRequest$inboundSchema: z.ZodType<
    GetWorkflowRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    flowId: z.string(),
});

/** @internal */
export type GetWorkflowRequest$Outbound = {
    flowId: string;
};

/** @internal */
export const GetWorkflowRequest$outboundSchema: z.ZodType<
    GetWorkflowRequest$Outbound,
    z.ZodTypeDef,
    GetWorkflowRequest
> = z.object({
    flowId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetWorkflowRequest$ {
    /** @deprecated use `GetWorkflowRequest$inboundSchema` instead. */
    export const inboundSchema = GetWorkflowRequest$inboundSchema;
    /** @deprecated use `GetWorkflowRequest$outboundSchema` instead. */
    export const outboundSchema = GetWorkflowRequest$outboundSchema;
    /** @deprecated use `GetWorkflowRequest$Outbound` instead. */
    export type Outbound = GetWorkflowRequest$Outbound;
}

/** @internal */
export const GetWorkflowResponse$inboundSchema: z.ZodType<
    GetWorkflowResponse,
    z.ZodTypeDef,
    unknown
> = z.union([components.GetWorkflowResponse$inboundSchema, components.ErrorT$inboundSchema]);

/** @internal */
export type GetWorkflowResponse$Outbound =
    | components.GetWorkflowResponse$Outbound
    | components.ErrorT$Outbound;

/** @internal */
export const GetWorkflowResponse$outboundSchema: z.ZodType<
    GetWorkflowResponse$Outbound,
    z.ZodTypeDef,
    GetWorkflowResponse
> = z.union([components.GetWorkflowResponse$outboundSchema, components.ErrorT$outboundSchema]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetWorkflowResponse$ {
    /** @deprecated use `GetWorkflowResponse$inboundSchema` instead. */
    export const inboundSchema = GetWorkflowResponse$inboundSchema;
    /** @deprecated use `GetWorkflowResponse$outboundSchema` instead. */
    export const outboundSchema = GetWorkflowResponse$outboundSchema;
    /** @deprecated use `GetWorkflowResponse$Outbound` instead. */
    export type Outbound = GetWorkflowResponse$Outbound;
}
