/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export type InsertConfigResponse = components.ConfigResponse | components.WebhooksErrorResponse;

/** @internal */
export const InsertConfigResponse$inboundSchema: z.ZodType<
    InsertConfigResponse,
    z.ZodTypeDef,
    unknown
> = z.union([
    components.ConfigResponse$inboundSchema,
    components.WebhooksErrorResponse$inboundSchema,
]);

/** @internal */
export type InsertConfigResponse$Outbound =
    | components.ConfigResponse$Outbound
    | components.WebhooksErrorResponse$Outbound;

/** @internal */
export const InsertConfigResponse$outboundSchema: z.ZodType<
    InsertConfigResponse$Outbound,
    z.ZodTypeDef,
    InsertConfigResponse
> = z.union([
    components.ConfigResponse$outboundSchema,
    components.WebhooksErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InsertConfigResponse$ {
    /** @deprecated use `InsertConfigResponse$inboundSchema` instead. */
    export const inboundSchema = InsertConfigResponse$inboundSchema;
    /** @deprecated use `InsertConfigResponse$outboundSchema` instead. */
    export const outboundSchema = InsertConfigResponse$outboundSchema;
    /** @deprecated use `InsertConfigResponse$Outbound` instead. */
    export type Outbound = InsertConfigResponse$Outbound;
}
