/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type SendEventRequestBody = {
    name: string;
};

export type SendEventRequest = {
    /**
     * The instance id
     */
    instanceID: string;
    requestBody?: SendEventRequestBody | undefined;
};

/** @internal */
export const SendEventRequestBody$inboundSchema: z.ZodType<
    SendEventRequestBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    name: z.string(),
});

/** @internal */
export type SendEventRequestBody$Outbound = {
    name: string;
};

/** @internal */
export const SendEventRequestBody$outboundSchema: z.ZodType<
    SendEventRequestBody$Outbound,
    z.ZodTypeDef,
    SendEventRequestBody
> = z.object({
    name: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SendEventRequestBody$ {
    /** @deprecated use `SendEventRequestBody$inboundSchema` instead. */
    export const inboundSchema = SendEventRequestBody$inboundSchema;
    /** @deprecated use `SendEventRequestBody$outboundSchema` instead. */
    export const outboundSchema = SendEventRequestBody$outboundSchema;
    /** @deprecated use `SendEventRequestBody$Outbound` instead. */
    export type Outbound = SendEventRequestBody$Outbound;
}

/** @internal */
export const SendEventRequest$inboundSchema: z.ZodType<SendEventRequest, z.ZodTypeDef, unknown> = z
    .object({
        instanceID: z.string(),
        RequestBody: z.lazy(() => SendEventRequestBody$inboundSchema).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            RequestBody: "requestBody",
        });
    });

/** @internal */
export type SendEventRequest$Outbound = {
    instanceID: string;
    RequestBody?: SendEventRequestBody$Outbound | undefined;
};

/** @internal */
export const SendEventRequest$outboundSchema: z.ZodType<
    SendEventRequest$Outbound,
    z.ZodTypeDef,
    SendEventRequest
> = z
    .object({
        instanceID: z.string(),
        requestBody: z.lazy(() => SendEventRequestBody$outboundSchema).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            requestBody: "RequestBody",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SendEventRequest$ {
    /** @deprecated use `SendEventRequest$inboundSchema` instead. */
    export const inboundSchema = SendEventRequest$inboundSchema;
    /** @deprecated use `SendEventRequest$outboundSchema` instead. */
    export const outboundSchema = SendEventRequest$outboundSchema;
    /** @deprecated use `SendEventRequest$Outbound` instead. */
    export type Outbound = SendEventRequest$Outbound;
}
