/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type UpdateBankAccountMetadataRequest = {
    /**
     * The bank account ID.
     */
    bankAccountId: string;
    updateBankAccountMetadataRequest: components.UpdateBankAccountMetadataRequest;
};

/** @internal */
export const UpdateBankAccountMetadataRequest$inboundSchema: z.ZodType<
    UpdateBankAccountMetadataRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        bankAccountId: z.string(),
        UpdateBankAccountMetadataRequest: components.UpdateBankAccountMetadataRequest$inboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            UpdateBankAccountMetadataRequest: "updateBankAccountMetadataRequest",
        });
    });

/** @internal */
export type UpdateBankAccountMetadataRequest$Outbound = {
    bankAccountId: string;
    UpdateBankAccountMetadataRequest: components.UpdateBankAccountMetadataRequest$Outbound;
};

/** @internal */
export const UpdateBankAccountMetadataRequest$outboundSchema: z.ZodType<
    UpdateBankAccountMetadataRequest$Outbound,
    z.ZodTypeDef,
    UpdateBankAccountMetadataRequest
> = z
    .object({
        bankAccountId: z.string(),
        updateBankAccountMetadataRequest:
            components.UpdateBankAccountMetadataRequest$outboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            updateBankAccountMetadataRequest: "UpdateBankAccountMetadataRequest",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateBankAccountMetadataRequest$ {
    /** @deprecated use `UpdateBankAccountMetadataRequest$inboundSchema` instead. */
    export const inboundSchema = UpdateBankAccountMetadataRequest$inboundSchema;
    /** @deprecated use `UpdateBankAccountMetadataRequest$outboundSchema` instead. */
    export const outboundSchema = UpdateBankAccountMetadataRequest$outboundSchema;
    /** @deprecated use `UpdateBankAccountMetadataRequest$Outbound` instead. */
    export type Outbound = UpdateBankAccountMetadataRequest$Outbound;
}
