/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type V2DeleteLedgerMetadataRequest = {
    /**
     * Name of the ledger.
     */
    ledger: string;
    /**
     * Key to remove.
     */
    key: string;
};

/** @internal */
export const V2DeleteLedgerMetadataRequest$inboundSchema: z.ZodType<
    V2DeleteLedgerMetadataRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    ledger: z.string(),
    key: z.string(),
});

/** @internal */
export type V2DeleteLedgerMetadataRequest$Outbound = {
    ledger: string;
    key: string;
};

/** @internal */
export const V2DeleteLedgerMetadataRequest$outboundSchema: z.ZodType<
    V2DeleteLedgerMetadataRequest$Outbound,
    z.ZodTypeDef,
    V2DeleteLedgerMetadataRequest
> = z.object({
    ledger: z.string(),
    key: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2DeleteLedgerMetadataRequest$ {
    /** @deprecated use `V2DeleteLedgerMetadataRequest$inboundSchema` instead. */
    export const inboundSchema = V2DeleteLedgerMetadataRequest$inboundSchema;
    /** @deprecated use `V2DeleteLedgerMetadataRequest$outboundSchema` instead. */
    export const outboundSchema = V2DeleteLedgerMetadataRequest$outboundSchema;
    /** @deprecated use `V2DeleteLedgerMetadataRequest$Outbound` instead. */
    export type Outbound = V2DeleteLedgerMetadataRequest$Outbound;
}
