/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as errors from "../errors/index.js";
import * as z from "zod";

export type V2GetAccountRequest = {
    /**
     * Name of the ledger.
     */
    ledger: string;
    /**
     * Exact address of the account. It must match the following regular expressions pattern:
     *
     * @remarks
     * ```
     * ^\w+(:\w+)*$
     * ```
     *
     */
    address: string;
    expand?: string | undefined;
    pit?: Date | undefined;
};

export type V2GetAccountResponse = components.V2AccountResponse | errors.V2ErrorResponse;

/** @internal */
export const V2GetAccountRequest$inboundSchema: z.ZodType<
    V2GetAccountRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    ledger: z.string(),
    address: z.string(),
    expand: z.string().optional(),
    pit: z
        .string()
        .datetime({ offset: true })
        .transform((v) => new Date(v))
        .optional(),
});

/** @internal */
export type V2GetAccountRequest$Outbound = {
    ledger: string;
    address: string;
    expand?: string | undefined;
    pit?: string | undefined;
};

/** @internal */
export const V2GetAccountRequest$outboundSchema: z.ZodType<
    V2GetAccountRequest$Outbound,
    z.ZodTypeDef,
    V2GetAccountRequest
> = z.object({
    ledger: z.string(),
    address: z.string(),
    expand: z.string().optional(),
    pit: z
        .date()
        .transform((v) => v.toISOString())
        .optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2GetAccountRequest$ {
    /** @deprecated use `V2GetAccountRequest$inboundSchema` instead. */
    export const inboundSchema = V2GetAccountRequest$inboundSchema;
    /** @deprecated use `V2GetAccountRequest$outboundSchema` instead. */
    export const outboundSchema = V2GetAccountRequest$outboundSchema;
    /** @deprecated use `V2GetAccountRequest$Outbound` instead. */
    export type Outbound = V2GetAccountRequest$Outbound;
}

/** @internal */
export const V2GetAccountResponse$inboundSchema: z.ZodType<
    V2GetAccountResponse,
    z.ZodTypeDef,
    unknown
> = z.union([components.V2AccountResponse$inboundSchema, errors.V2ErrorResponse$inboundSchema]);

/** @internal */
export type V2GetAccountResponse$Outbound =
    | components.V2AccountResponse$Outbound
    | errors.V2ErrorResponse$Outbound;

/** @internal */
export const V2GetAccountResponse$outboundSchema: z.ZodType<
    V2GetAccountResponse$Outbound,
    z.ZodTypeDef,
    V2GetAccountResponse
> = z.union([components.V2AccountResponse$outboundSchema, errors.V2ErrorResponse$outboundSchema]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2GetAccountResponse$ {
    /** @deprecated use `V2GetAccountResponse$inboundSchema` instead. */
    export const inboundSchema = V2GetAccountResponse$inboundSchema;
    /** @deprecated use `V2GetAccountResponse$outboundSchema` instead. */
    export const outboundSchema = V2GetAccountResponse$outboundSchema;
    /** @deprecated use `V2GetAccountResponse$Outbound` instead. */
    export type Outbound = V2GetAccountResponse$Outbound;
}
