/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export type V2GetServerInfoResponse = components.V2ServerInfo | components.V2Error;

/** @internal */
export const V2GetServerInfoResponse$inboundSchema: z.ZodType<
    V2GetServerInfoResponse,
    z.ZodTypeDef,
    unknown
> = z.union([components.V2ServerInfo$inboundSchema, components.V2Error$inboundSchema]);

/** @internal */
export type V2GetServerInfoResponse$Outbound =
    | components.V2ServerInfo$Outbound
    | components.V2Error$Outbound;

/** @internal */
export const V2GetServerInfoResponse$outboundSchema: z.ZodType<
    V2GetServerInfoResponse$Outbound,
    z.ZodTypeDef,
    V2GetServerInfoResponse
> = z.union([components.V2ServerInfo$outboundSchema, components.V2Error$outboundSchema]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2GetServerInfoResponse$ {
    /** @deprecated use `V2GetServerInfoResponse$inboundSchema` instead. */
    export const inboundSchema = V2GetServerInfoResponse$inboundSchema;
    /** @deprecated use `V2GetServerInfoResponse$outboundSchema` instead. */
    export const outboundSchema = V2GetServerInfoResponse$outboundSchema;
    /** @deprecated use `V2GetServerInfoResponse$Outbound` instead. */
    export type Outbound = V2GetServerInfoResponse$Outbound;
}
