/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export type V2GetInstanceHistoryRequest = {
    /**
     * The instance id
     */
    instanceID: string;
};

export type V2GetInstanceHistoryResponse =
    | components.V2GetWorkflowInstanceHistoryResponse
    | components.V2Error;

/** @internal */
export const V2GetInstanceHistoryRequest$inboundSchema: z.ZodType<
    V2GetInstanceHistoryRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    instanceID: z.string(),
});

/** @internal */
export type V2GetInstanceHistoryRequest$Outbound = {
    instanceID: string;
};

/** @internal */
export const V2GetInstanceHistoryRequest$outboundSchema: z.ZodType<
    V2GetInstanceHistoryRequest$Outbound,
    z.ZodTypeDef,
    V2GetInstanceHistoryRequest
> = z.object({
    instanceID: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2GetInstanceHistoryRequest$ {
    /** @deprecated use `V2GetInstanceHistoryRequest$inboundSchema` instead. */
    export const inboundSchema = V2GetInstanceHistoryRequest$inboundSchema;
    /** @deprecated use `V2GetInstanceHistoryRequest$outboundSchema` instead. */
    export const outboundSchema = V2GetInstanceHistoryRequest$outboundSchema;
    /** @deprecated use `V2GetInstanceHistoryRequest$Outbound` instead. */
    export type Outbound = V2GetInstanceHistoryRequest$Outbound;
}

/** @internal */
export const V2GetInstanceHistoryResponse$inboundSchema: z.ZodType<
    V2GetInstanceHistoryResponse,
    z.ZodTypeDef,
    unknown
> = z.union([
    components.V2GetWorkflowInstanceHistoryResponse$inboundSchema,
    components.V2Error$inboundSchema,
]);

/** @internal */
export type V2GetInstanceHistoryResponse$Outbound =
    | components.V2GetWorkflowInstanceHistoryResponse$Outbound
    | components.V2Error$Outbound;

/** @internal */
export const V2GetInstanceHistoryResponse$outboundSchema: z.ZodType<
    V2GetInstanceHistoryResponse$Outbound,
    z.ZodTypeDef,
    V2GetInstanceHistoryResponse
> = z.union([
    components.V2GetWorkflowInstanceHistoryResponse$outboundSchema,
    components.V2Error$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2GetInstanceHistoryResponse$ {
    /** @deprecated use `V2GetInstanceHistoryResponse$inboundSchema` instead. */
    export const inboundSchema = V2GetInstanceHistoryResponse$inboundSchema;
    /** @deprecated use `V2GetInstanceHistoryResponse$outboundSchema` instead. */
    export const outboundSchema = V2GetInstanceHistoryResponse$outboundSchema;
    /** @deprecated use `V2GetInstanceHistoryResponse$Outbound` instead. */
    export type Outbound = V2GetInstanceHistoryResponse$Outbound;
}
