/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as errors from "../errors/index.js";
import * as z from "zod";

export type V2ListAccountsRequest = {
    /**
     * Name of the ledger.
     */
    ledger: string;
    /**
     * The maximum number of results to return per page.
     *
     * @remarks
     *
     */
    pageSize?: number | undefined;
    /**
     * Parameter used in pagination requests. Maximum page size is set to 15.
     *
     * @remarks
     * Set to the value of next for the next page of results.
     * Set to the value of previous for the previous page of results.
     * No other parameters can be set when this parameter is set.
     *
     */
    cursor?: string | undefined;
    expand?: string | undefined;
    pit?: Date | undefined;
    /**
     * Sort results using a field name and order (ascending or descending).
     *
     * @remarks
     * Format: `<field>:<order>`, where `<field>` is the field name and `<order>` is either `asc` or `desc`.
     *
     */
    sort?: string | undefined;
    query?: { [k: string]: any } | undefined;
};

export type V2ListAccountsResponse = components.V2AccountsCursorResponse | errors.V2ErrorResponse;

/** @internal */
export const V2ListAccountsRequest$inboundSchema: z.ZodType<
    V2ListAccountsRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    ledger: z.string(),
    pageSize: z.number().int().optional(),
    cursor: z.string().optional(),
    expand: z.string().optional(),
    pit: z
        .string()
        .datetime({ offset: true })
        .transform((v) => new Date(v))
        .optional(),
    sort: z.string().optional(),
    query: z.record(z.any()).optional(),
});

/** @internal */
export type V2ListAccountsRequest$Outbound = {
    ledger: string;
    pageSize?: number | undefined;
    cursor?: string | undefined;
    expand?: string | undefined;
    pit?: string | undefined;
    sort?: string | undefined;
    query?: { [k: string]: any } | undefined;
};

/** @internal */
export const V2ListAccountsRequest$outboundSchema: z.ZodType<
    V2ListAccountsRequest$Outbound,
    z.ZodTypeDef,
    V2ListAccountsRequest
> = z.object({
    ledger: z.string(),
    pageSize: z.number().int().optional(),
    cursor: z.string().optional(),
    expand: z.string().optional(),
    pit: z
        .date()
        .transform((v) => v.toISOString())
        .optional(),
    sort: z.string().optional(),
    query: z.record(z.any()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2ListAccountsRequest$ {
    /** @deprecated use `V2ListAccountsRequest$inboundSchema` instead. */
    export const inboundSchema = V2ListAccountsRequest$inboundSchema;
    /** @deprecated use `V2ListAccountsRequest$outboundSchema` instead. */
    export const outboundSchema = V2ListAccountsRequest$outboundSchema;
    /** @deprecated use `V2ListAccountsRequest$Outbound` instead. */
    export type Outbound = V2ListAccountsRequest$Outbound;
}

/** @internal */
export const V2ListAccountsResponse$inboundSchema: z.ZodType<
    V2ListAccountsResponse,
    z.ZodTypeDef,
    unknown
> = z.union([
    components.V2AccountsCursorResponse$inboundSchema,
    errors.V2ErrorResponse$inboundSchema,
]);

/** @internal */
export type V2ListAccountsResponse$Outbound =
    | components.V2AccountsCursorResponse$Outbound
    | errors.V2ErrorResponse$Outbound;

/** @internal */
export const V2ListAccountsResponse$outboundSchema: z.ZodType<
    V2ListAccountsResponse$Outbound,
    z.ZodTypeDef,
    V2ListAccountsResponse
> = z.union([
    components.V2AccountsCursorResponse$outboundSchema,
    errors.V2ErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2ListAccountsResponse$ {
    /** @deprecated use `V2ListAccountsResponse$inboundSchema` instead. */
    export const inboundSchema = V2ListAccountsResponse$inboundSchema;
    /** @deprecated use `V2ListAccountsResponse$outboundSchema` instead. */
    export const outboundSchema = V2ListAccountsResponse$outboundSchema;
    /** @deprecated use `V2ListAccountsResponse$Outbound` instead. */
    export type Outbound = V2ListAccountsResponse$Outbound;
}
