/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as errors from "../errors/index.js";
import * as z from "zod";

export type V2ListExportersResponse = components.V2ListExportersResponse | errors.V2ErrorResponse;

/** @internal */
export const V2ListExportersResponse$inboundSchema: z.ZodType<
    V2ListExportersResponse,
    z.ZodTypeDef,
    unknown
> = z.union([
    components.V2ListExportersResponse$inboundSchema,
    errors.V2ErrorResponse$inboundSchema,
]);

/** @internal */
export type V2ListExportersResponse$Outbound =
    | components.V2ListExportersResponse$Outbound
    | errors.V2ErrorResponse$Outbound;

/** @internal */
export const V2ListExportersResponse$outboundSchema: z.ZodType<
    V2ListExportersResponse$Outbound,
    z.ZodTypeDef,
    V2ListExportersResponse
> = z.union([
    components.V2ListExportersResponse$outboundSchema,
    errors.V2ErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2ListExportersResponse$ {
    /** @deprecated use `V2ListExportersResponse$inboundSchema` instead. */
    export const inboundSchema = V2ListExportersResponse$inboundSchema;
    /** @deprecated use `V2ListExportersResponse$outboundSchema` instead. */
    export const outboundSchema = V2ListExportersResponse$outboundSchema;
    /** @deprecated use `V2ListExportersResponse$Outbound` instead. */
    export type Outbound = V2ListExportersResponse$Outbound;
}
