/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as errors from "../errors/index.js";
import * as z from "zod";

export type V2ListLedgersRequest = {
    /**
     * The maximum number of results to return per page.
     *
     * @remarks
     *
     */
    pageSize?: number | undefined;
    /**
     * Parameter used in pagination requests. Maximum page size is set to 15.
     *
     * @remarks
     * Set to the value of next for the next page of results.
     * Set to the value of previous for the previous page of results.
     * No other parameters can be set when this parameter is set.
     *
     */
    cursor?: string | undefined;
    /**
     * Sort results using a field name and order (ascending or descending).
     *
     * @remarks
     * Format: `<field>:<order>`, where `<field>` is the field name and `<order>` is either `asc` or `desc`.
     *
     */
    sort?: string | undefined;
};

export type V2ListLedgersResponse = components.V2LedgerListResponse | errors.V2ErrorResponse;

/** @internal */
export const V2ListLedgersRequest$inboundSchema: z.ZodType<
    V2ListLedgersRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    pageSize: z.number().int().optional(),
    cursor: z.string().optional(),
    sort: z.string().optional(),
});

/** @internal */
export type V2ListLedgersRequest$Outbound = {
    pageSize?: number | undefined;
    cursor?: string | undefined;
    sort?: string | undefined;
};

/** @internal */
export const V2ListLedgersRequest$outboundSchema: z.ZodType<
    V2ListLedgersRequest$Outbound,
    z.ZodTypeDef,
    V2ListLedgersRequest
> = z.object({
    pageSize: z.number().int().optional(),
    cursor: z.string().optional(),
    sort: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2ListLedgersRequest$ {
    /** @deprecated use `V2ListLedgersRequest$inboundSchema` instead. */
    export const inboundSchema = V2ListLedgersRequest$inboundSchema;
    /** @deprecated use `V2ListLedgersRequest$outboundSchema` instead. */
    export const outboundSchema = V2ListLedgersRequest$outboundSchema;
    /** @deprecated use `V2ListLedgersRequest$Outbound` instead. */
    export type Outbound = V2ListLedgersRequest$Outbound;
}

/** @internal */
export const V2ListLedgersResponse$inboundSchema: z.ZodType<
    V2ListLedgersResponse,
    z.ZodTypeDef,
    unknown
> = z.union([components.V2LedgerListResponse$inboundSchema, errors.V2ErrorResponse$inboundSchema]);

/** @internal */
export type V2ListLedgersResponse$Outbound =
    | components.V2LedgerListResponse$Outbound
    | errors.V2ErrorResponse$Outbound;

/** @internal */
export const V2ListLedgersResponse$outboundSchema: z.ZodType<
    V2ListLedgersResponse$Outbound,
    z.ZodTypeDef,
    V2ListLedgersResponse
> = z.union([
    components.V2LedgerListResponse$outboundSchema,
    errors.V2ErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2ListLedgersResponse$ {
    /** @deprecated use `V2ListLedgersResponse$inboundSchema` instead. */
    export const inboundSchema = V2ListLedgersResponse$inboundSchema;
    /** @deprecated use `V2ListLedgersResponse$outboundSchema` instead. */
    export const outboundSchema = V2ListLedgersResponse$outboundSchema;
    /** @deprecated use `V2ListLedgersResponse$Outbound` instead. */
    export type Outbound = V2ListLedgersResponse$Outbound;
}
