/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type V2ResetPipelineRequest = {
    /**
     * Name of the ledger.
     */
    ledger: string;
    /**
     * The pipeline id
     */
    pipelineID: string;
};

/** @internal */
export const V2ResetPipelineRequest$inboundSchema: z.ZodType<
    V2ResetPipelineRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    ledger: z.string(),
    pipelineID: z.string(),
});

/** @internal */
export type V2ResetPipelineRequest$Outbound = {
    ledger: string;
    pipelineID: string;
};

/** @internal */
export const V2ResetPipelineRequest$outboundSchema: z.ZodType<
    V2ResetPipelineRequest$Outbound,
    z.ZodTypeDef,
    V2ResetPipelineRequest
> = z.object({
    ledger: z.string(),
    pipelineID: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2ResetPipelineRequest$ {
    /** @deprecated use `V2ResetPipelineRequest$inboundSchema` instead. */
    export const inboundSchema = V2ResetPipelineRequest$inboundSchema;
    /** @deprecated use `V2ResetPipelineRequest$outboundSchema` instead. */
    export const outboundSchema = V2ResetPipelineRequest$outboundSchema;
    /** @deprecated use `V2ResetPipelineRequest$Outbound` instead. */
    export type Outbound = V2ResetPipelineRequest$Outbound;
}
