/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type V2SendEventRequestBody = {
    name: string;
};

export type V2SendEventRequest = {
    /**
     * The instance id
     */
    instanceID: string;
    requestBody?: V2SendEventRequestBody | undefined;
};

/** @internal */
export const V2SendEventRequestBody$inboundSchema: z.ZodType<
    V2SendEventRequestBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    name: z.string(),
});

/** @internal */
export type V2SendEventRequestBody$Outbound = {
    name: string;
};

/** @internal */
export const V2SendEventRequestBody$outboundSchema: z.ZodType<
    V2SendEventRequestBody$Outbound,
    z.ZodTypeDef,
    V2SendEventRequestBody
> = z.object({
    name: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2SendEventRequestBody$ {
    /** @deprecated use `V2SendEventRequestBody$inboundSchema` instead. */
    export const inboundSchema = V2SendEventRequestBody$inboundSchema;
    /** @deprecated use `V2SendEventRequestBody$outboundSchema` instead. */
    export const outboundSchema = V2SendEventRequestBody$outboundSchema;
    /** @deprecated use `V2SendEventRequestBody$Outbound` instead. */
    export type Outbound = V2SendEventRequestBody$Outbound;
}

/** @internal */
export const V2SendEventRequest$inboundSchema: z.ZodType<
    V2SendEventRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        instanceID: z.string(),
        RequestBody: z.lazy(() => V2SendEventRequestBody$inboundSchema).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            RequestBody: "requestBody",
        });
    });

/** @internal */
export type V2SendEventRequest$Outbound = {
    instanceID: string;
    RequestBody?: V2SendEventRequestBody$Outbound | undefined;
};

/** @internal */
export const V2SendEventRequest$outboundSchema: z.ZodType<
    V2SendEventRequest$Outbound,
    z.ZodTypeDef,
    V2SendEventRequest
> = z
    .object({
        instanceID: z.string(),
        requestBody: z.lazy(() => V2SendEventRequestBody$outboundSchema).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            requestBody: "RequestBody",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2SendEventRequest$ {
    /** @deprecated use `V2SendEventRequest$inboundSchema` instead. */
    export const inboundSchema = V2SendEventRequest$inboundSchema;
    /** @deprecated use `V2SendEventRequest$outboundSchema` instead. */
    export const outboundSchema = V2SendEventRequest$outboundSchema;
    /** @deprecated use `V2SendEventRequest$Outbound` instead. */
    export type Outbound = V2SendEventRequest$Outbound;
}
