/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type V3AddBankAccountToPaymentServiceUserRequest = {
    /**
     * The payment service user ID
     */
    paymentServiceUserID: string;
    /**
     * The bank account ID
     */
    bankAccountID: string;
};

/** @internal */
export const V3AddBankAccountToPaymentServiceUserRequest$inboundSchema: z.ZodType<
    V3AddBankAccountToPaymentServiceUserRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    paymentServiceUserID: z.string(),
    bankAccountID: z.string(),
});

/** @internal */
export type V3AddBankAccountToPaymentServiceUserRequest$Outbound = {
    paymentServiceUserID: string;
    bankAccountID: string;
};

/** @internal */
export const V3AddBankAccountToPaymentServiceUserRequest$outboundSchema: z.ZodType<
    V3AddBankAccountToPaymentServiceUserRequest$Outbound,
    z.ZodTypeDef,
    V3AddBankAccountToPaymentServiceUserRequest
> = z.object({
    paymentServiceUserID: z.string(),
    bankAccountID: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3AddBankAccountToPaymentServiceUserRequest$ {
    /** @deprecated use `V3AddBankAccountToPaymentServiceUserRequest$inboundSchema` instead. */
    export const inboundSchema = V3AddBankAccountToPaymentServiceUserRequest$inboundSchema;
    /** @deprecated use `V3AddBankAccountToPaymentServiceUserRequest$outboundSchema` instead. */
    export const outboundSchema = V3AddBankAccountToPaymentServiceUserRequest$outboundSchema;
    /** @deprecated use `V3AddBankAccountToPaymentServiceUserRequest$Outbound` instead. */
    export type Outbound = V3AddBankAccountToPaymentServiceUserRequest$Outbound;
}
