/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export type V3CreatePaymentServiceUserResponse =
    | components.V3CreatePaymentServiceUserResponse
    | components.V3ErrorResponse;

/** @internal */
export const V3CreatePaymentServiceUserResponse$inboundSchema: z.ZodType<
    V3CreatePaymentServiceUserResponse,
    z.ZodTypeDef,
    unknown
> = z.union([
    components.V3CreatePaymentServiceUserResponse$inboundSchema,
    components.V3ErrorResponse$inboundSchema,
]);

/** @internal */
export type V3CreatePaymentServiceUserResponse$Outbound =
    | components.V3CreatePaymentServiceUserResponse$Outbound
    | components.V3ErrorResponse$Outbound;

/** @internal */
export const V3CreatePaymentServiceUserResponse$outboundSchema: z.ZodType<
    V3CreatePaymentServiceUserResponse$Outbound,
    z.ZodTypeDef,
    V3CreatePaymentServiceUserResponse
> = z.union([
    components.V3CreatePaymentServiceUserResponse$outboundSchema,
    components.V3ErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3CreatePaymentServiceUserResponse$ {
    /** @deprecated use `V3CreatePaymentServiceUserResponse$inboundSchema` instead. */
    export const inboundSchema = V3CreatePaymentServiceUserResponse$inboundSchema;
    /** @deprecated use `V3CreatePaymentServiceUserResponse$outboundSchema` instead. */
    export const outboundSchema = V3CreatePaymentServiceUserResponse$outboundSchema;
    /** @deprecated use `V3CreatePaymentServiceUserResponse$Outbound` instead. */
    export type Outbound = V3CreatePaymentServiceUserResponse$Outbound;
}
