/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export type V3CreatePoolResponse = components.V3CreatePoolResponse | components.V3ErrorResponse;

/** @internal */
export const V3CreatePoolResponse$inboundSchema: z.ZodType<
    V3CreatePoolResponse,
    z.ZodTypeDef,
    unknown
> = z.union([
    components.V3CreatePoolResponse$inboundSchema,
    components.V3ErrorResponse$inboundSchema,
]);

/** @internal */
export type V3CreatePoolResponse$Outbound =
    | components.V3CreatePoolResponse$Outbound
    | components.V3ErrorResponse$Outbound;

/** @internal */
export const V3CreatePoolResponse$outboundSchema: z.ZodType<
    V3CreatePoolResponse$Outbound,
    z.ZodTypeDef,
    V3CreatePoolResponse
> = z.union([
    components.V3CreatePoolResponse$outboundSchema,
    components.V3ErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3CreatePoolResponse$ {
    /** @deprecated use `V3CreatePoolResponse$inboundSchema` instead. */
    export const inboundSchema = V3CreatePoolResponse$inboundSchema;
    /** @deprecated use `V3CreatePoolResponse$outboundSchema` instead. */
    export const outboundSchema = V3CreatePoolResponse$outboundSchema;
    /** @deprecated use `V3CreatePoolResponse$Outbound` instead. */
    export type Outbound = V3CreatePoolResponse$Outbound;
}
