/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export type V3CreateBankAccountResponse =
    | components.V3CreateBankAccountResponse
    | components.V3ErrorResponse;

/** @internal */
export const V3CreateBankAccountResponse$inboundSchema: z.ZodType<
    V3CreateBankAccountResponse,
    z.ZodTypeDef,
    unknown
> = z.union([
    components.V3CreateBankAccountResponse$inboundSchema,
    components.V3ErrorResponse$inboundSchema,
]);

/** @internal */
export type V3CreateBankAccountResponse$Outbound =
    | components.V3CreateBankAccountResponse$Outbound
    | components.V3ErrorResponse$Outbound;

/** @internal */
export const V3CreateBankAccountResponse$outboundSchema: z.ZodType<
    V3CreateBankAccountResponse$Outbound,
    z.ZodTypeDef,
    V3CreateBankAccountResponse
> = z.union([
    components.V3CreateBankAccountResponse$outboundSchema,
    components.V3ErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3CreateBankAccountResponse$ {
    /** @deprecated use `V3CreateBankAccountResponse$inboundSchema` instead. */
    export const inboundSchema = V3CreateBankAccountResponse$inboundSchema;
    /** @deprecated use `V3CreateBankAccountResponse$outboundSchema` instead. */
    export const outboundSchema = V3CreateBankAccountResponse$outboundSchema;
    /** @deprecated use `V3CreateBankAccountResponse$Outbound` instead. */
    export type Outbound = V3CreateBankAccountResponse$Outbound;
}
