/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type V3CreateLinkForPaymentServiceUserRequest = {
    /**
     * The payment service user ID
     */
    paymentServiceUserID: string;
    /**
     * The connector ID
     */
    connectorID: string;
    v3PaymentServiceUserCreateLinkRequest?:
        | components.V3PaymentServiceUserCreateLinkRequest
        | undefined;
};

export type V3CreateLinkForPaymentServiceUserResponse =
    | components.V3PaymentServiceUserCreateLinkResponse
    | components.V3ErrorResponse;

/** @internal */
export const V3CreateLinkForPaymentServiceUserRequest$inboundSchema: z.ZodType<
    V3CreateLinkForPaymentServiceUserRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        paymentServiceUserID: z.string(),
        connectorID: z.string(),
        V3PaymentServiceUserCreateLinkRequest:
            components.V3PaymentServiceUserCreateLinkRequest$inboundSchema.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            V3PaymentServiceUserCreateLinkRequest: "v3PaymentServiceUserCreateLinkRequest",
        });
    });

/** @internal */
export type V3CreateLinkForPaymentServiceUserRequest$Outbound = {
    paymentServiceUserID: string;
    connectorID: string;
    V3PaymentServiceUserCreateLinkRequest?:
        | components.V3PaymentServiceUserCreateLinkRequest$Outbound
        | undefined;
};

/** @internal */
export const V3CreateLinkForPaymentServiceUserRequest$outboundSchema: z.ZodType<
    V3CreateLinkForPaymentServiceUserRequest$Outbound,
    z.ZodTypeDef,
    V3CreateLinkForPaymentServiceUserRequest
> = z
    .object({
        paymentServiceUserID: z.string(),
        connectorID: z.string(),
        v3PaymentServiceUserCreateLinkRequest:
            components.V3PaymentServiceUserCreateLinkRequest$outboundSchema.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            v3PaymentServiceUserCreateLinkRequest: "V3PaymentServiceUserCreateLinkRequest",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3CreateLinkForPaymentServiceUserRequest$ {
    /** @deprecated use `V3CreateLinkForPaymentServiceUserRequest$inboundSchema` instead. */
    export const inboundSchema = V3CreateLinkForPaymentServiceUserRequest$inboundSchema;
    /** @deprecated use `V3CreateLinkForPaymentServiceUserRequest$outboundSchema` instead. */
    export const outboundSchema = V3CreateLinkForPaymentServiceUserRequest$outboundSchema;
    /** @deprecated use `V3CreateLinkForPaymentServiceUserRequest$Outbound` instead. */
    export type Outbound = V3CreateLinkForPaymentServiceUserRequest$Outbound;
}

/** @internal */
export const V3CreateLinkForPaymentServiceUserResponse$inboundSchema: z.ZodType<
    V3CreateLinkForPaymentServiceUserResponse,
    z.ZodTypeDef,
    unknown
> = z.union([
    components.V3PaymentServiceUserCreateLinkResponse$inboundSchema,
    components.V3ErrorResponse$inboundSchema,
]);

/** @internal */
export type V3CreateLinkForPaymentServiceUserResponse$Outbound =
    | components.V3PaymentServiceUserCreateLinkResponse$Outbound
    | components.V3ErrorResponse$Outbound;

/** @internal */
export const V3CreateLinkForPaymentServiceUserResponse$outboundSchema: z.ZodType<
    V3CreateLinkForPaymentServiceUserResponse$Outbound,
    z.ZodTypeDef,
    V3CreateLinkForPaymentServiceUserResponse
> = z.union([
    components.V3PaymentServiceUserCreateLinkResponse$outboundSchema,
    components.V3ErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3CreateLinkForPaymentServiceUserResponse$ {
    /** @deprecated use `V3CreateLinkForPaymentServiceUserResponse$inboundSchema` instead. */
    export const inboundSchema = V3CreateLinkForPaymentServiceUserResponse$inboundSchema;
    /** @deprecated use `V3CreateLinkForPaymentServiceUserResponse$outboundSchema` instead. */
    export const outboundSchema = V3CreateLinkForPaymentServiceUserResponse$outboundSchema;
    /** @deprecated use `V3CreateLinkForPaymentServiceUserResponse$Outbound` instead. */
    export type Outbound = V3CreateLinkForPaymentServiceUserResponse$Outbound;
}
