/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export type V3GetPaymentRequest = {
    /**
     * The payment ID
     */
    paymentID: string;
};

export type V3GetPaymentResponse = components.V3GetPaymentResponse | components.V3ErrorResponse;

/** @internal */
export const V3GetPaymentRequest$inboundSchema: z.ZodType<
    V3GetPaymentRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    paymentID: z.string(),
});

/** @internal */
export type V3GetPaymentRequest$Outbound = {
    paymentID: string;
};

/** @internal */
export const V3GetPaymentRequest$outboundSchema: z.ZodType<
    V3GetPaymentRequest$Outbound,
    z.ZodTypeDef,
    V3GetPaymentRequest
> = z.object({
    paymentID: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3GetPaymentRequest$ {
    /** @deprecated use `V3GetPaymentRequest$inboundSchema` instead. */
    export const inboundSchema = V3GetPaymentRequest$inboundSchema;
    /** @deprecated use `V3GetPaymentRequest$outboundSchema` instead. */
    export const outboundSchema = V3GetPaymentRequest$outboundSchema;
    /** @deprecated use `V3GetPaymentRequest$Outbound` instead. */
    export type Outbound = V3GetPaymentRequest$Outbound;
}

/** @internal */
export const V3GetPaymentResponse$inboundSchema: z.ZodType<
    V3GetPaymentResponse,
    z.ZodTypeDef,
    unknown
> = z.union([
    components.V3GetPaymentResponse$inboundSchema,
    components.V3ErrorResponse$inboundSchema,
]);

/** @internal */
export type V3GetPaymentResponse$Outbound =
    | components.V3GetPaymentResponse$Outbound
    | components.V3ErrorResponse$Outbound;

/** @internal */
export const V3GetPaymentResponse$outboundSchema: z.ZodType<
    V3GetPaymentResponse$Outbound,
    z.ZodTypeDef,
    V3GetPaymentResponse
> = z.union([
    components.V3GetPaymentResponse$outboundSchema,
    components.V3ErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3GetPaymentResponse$ {
    /** @deprecated use `V3GetPaymentResponse$inboundSchema` instead. */
    export const inboundSchema = V3GetPaymentResponse$inboundSchema;
    /** @deprecated use `V3GetPaymentResponse$outboundSchema` instead. */
    export const outboundSchema = V3GetPaymentResponse$outboundSchema;
    /** @deprecated use `V3GetPaymentResponse$Outbound` instead. */
    export type Outbound = V3GetPaymentResponse$Outbound;
}
