/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export type V3GetPoolBalancesRequest = {
    /**
     * The pool ID
     */
    poolID: string;
    /**
     * The time to filter by
     */
    at?: Date | undefined;
};

export type V3GetPoolBalancesResponse =
    | components.V3PoolBalancesResponse
    | components.V3ErrorResponse;

/** @internal */
export const V3GetPoolBalancesRequest$inboundSchema: z.ZodType<
    V3GetPoolBalancesRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    poolID: z.string(),
    at: z
        .string()
        .datetime({ offset: true })
        .transform((v) => new Date(v))
        .optional(),
});

/** @internal */
export type V3GetPoolBalancesRequest$Outbound = {
    poolID: string;
    at?: string | undefined;
};

/** @internal */
export const V3GetPoolBalancesRequest$outboundSchema: z.ZodType<
    V3GetPoolBalancesRequest$Outbound,
    z.ZodTypeDef,
    V3GetPoolBalancesRequest
> = z.object({
    poolID: z.string(),
    at: z
        .date()
        .transform((v) => v.toISOString())
        .optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3GetPoolBalancesRequest$ {
    /** @deprecated use `V3GetPoolBalancesRequest$inboundSchema` instead. */
    export const inboundSchema = V3GetPoolBalancesRequest$inboundSchema;
    /** @deprecated use `V3GetPoolBalancesRequest$outboundSchema` instead. */
    export const outboundSchema = V3GetPoolBalancesRequest$outboundSchema;
    /** @deprecated use `V3GetPoolBalancesRequest$Outbound` instead. */
    export type Outbound = V3GetPoolBalancesRequest$Outbound;
}

/** @internal */
export const V3GetPoolBalancesResponse$inboundSchema: z.ZodType<
    V3GetPoolBalancesResponse,
    z.ZodTypeDef,
    unknown
> = z.union([
    components.V3PoolBalancesResponse$inboundSchema,
    components.V3ErrorResponse$inboundSchema,
]);

/** @internal */
export type V3GetPoolBalancesResponse$Outbound =
    | components.V3PoolBalancesResponse$Outbound
    | components.V3ErrorResponse$Outbound;

/** @internal */
export const V3GetPoolBalancesResponse$outboundSchema: z.ZodType<
    V3GetPoolBalancesResponse$Outbound,
    z.ZodTypeDef,
    V3GetPoolBalancesResponse
> = z.union([
    components.V3PoolBalancesResponse$outboundSchema,
    components.V3ErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3GetPoolBalancesResponse$ {
    /** @deprecated use `V3GetPoolBalancesResponse$inboundSchema` instead. */
    export const inboundSchema = V3GetPoolBalancesResponse$inboundSchema;
    /** @deprecated use `V3GetPoolBalancesResponse$outboundSchema` instead. */
    export const outboundSchema = V3GetPoolBalancesResponse$outboundSchema;
    /** @deprecated use `V3GetPoolBalancesResponse$Outbound` instead. */
    export type Outbound = V3GetPoolBalancesResponse$Outbound;
}
