/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export type V3GetPaymentInitiationRequest = {
    /**
     * The payment initiation ID
     */
    paymentInitiationID: string;
};

export type V3GetPaymentInitiationResponse =
    | components.V3GetPaymentInitiationResponse
    | components.V3ErrorResponse;

/** @internal */
export const V3GetPaymentInitiationRequest$inboundSchema: z.ZodType<
    V3GetPaymentInitiationRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    paymentInitiationID: z.string(),
});

/** @internal */
export type V3GetPaymentInitiationRequest$Outbound = {
    paymentInitiationID: string;
};

/** @internal */
export const V3GetPaymentInitiationRequest$outboundSchema: z.ZodType<
    V3GetPaymentInitiationRequest$Outbound,
    z.ZodTypeDef,
    V3GetPaymentInitiationRequest
> = z.object({
    paymentInitiationID: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3GetPaymentInitiationRequest$ {
    /** @deprecated use `V3GetPaymentInitiationRequest$inboundSchema` instead. */
    export const inboundSchema = V3GetPaymentInitiationRequest$inboundSchema;
    /** @deprecated use `V3GetPaymentInitiationRequest$outboundSchema` instead. */
    export const outboundSchema = V3GetPaymentInitiationRequest$outboundSchema;
    /** @deprecated use `V3GetPaymentInitiationRequest$Outbound` instead. */
    export type Outbound = V3GetPaymentInitiationRequest$Outbound;
}

/** @internal */
export const V3GetPaymentInitiationResponse$inboundSchema: z.ZodType<
    V3GetPaymentInitiationResponse,
    z.ZodTypeDef,
    unknown
> = z.union([
    components.V3GetPaymentInitiationResponse$inboundSchema,
    components.V3ErrorResponse$inboundSchema,
]);

/** @internal */
export type V3GetPaymentInitiationResponse$Outbound =
    | components.V3GetPaymentInitiationResponse$Outbound
    | components.V3ErrorResponse$Outbound;

/** @internal */
export const V3GetPaymentInitiationResponse$outboundSchema: z.ZodType<
    V3GetPaymentInitiationResponse$Outbound,
    z.ZodTypeDef,
    V3GetPaymentInitiationResponse
> = z.union([
    components.V3GetPaymentInitiationResponse$outboundSchema,
    components.V3ErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3GetPaymentInitiationResponse$ {
    /** @deprecated use `V3GetPaymentInitiationResponse$inboundSchema` instead. */
    export const inboundSchema = V3GetPaymentInitiationResponse$inboundSchema;
    /** @deprecated use `V3GetPaymentInitiationResponse$outboundSchema` instead. */
    export const outboundSchema = V3GetPaymentInitiationResponse$outboundSchema;
    /** @deprecated use `V3GetPaymentInitiationResponse$Outbound` instead. */
    export type Outbound = V3GetPaymentInitiationResponse$Outbound;
}
