/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type V3UpdatePaymentMetadataRequest = {
    /**
     * The payment ID
     */
    paymentID: string;
    v3UpdatePaymentMetadataRequest?: components.V3UpdatePaymentMetadataRequest | undefined;
};

/** @internal */
export const V3UpdatePaymentMetadataRequest$inboundSchema: z.ZodType<
    V3UpdatePaymentMetadataRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        paymentID: z.string(),
        V3UpdatePaymentMetadataRequest:
            components.V3UpdatePaymentMetadataRequest$inboundSchema.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            V3UpdatePaymentMetadataRequest: "v3UpdatePaymentMetadataRequest",
        });
    });

/** @internal */
export type V3UpdatePaymentMetadataRequest$Outbound = {
    paymentID: string;
    V3UpdatePaymentMetadataRequest?: components.V3UpdatePaymentMetadataRequest$Outbound | undefined;
};

/** @internal */
export const V3UpdatePaymentMetadataRequest$outboundSchema: z.ZodType<
    V3UpdatePaymentMetadataRequest$Outbound,
    z.ZodTypeDef,
    V3UpdatePaymentMetadataRequest
> = z
    .object({
        paymentID: z.string(),
        v3UpdatePaymentMetadataRequest:
            components.V3UpdatePaymentMetadataRequest$outboundSchema.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            v3UpdatePaymentMetadataRequest: "V3UpdatePaymentMetadataRequest",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3UpdatePaymentMetadataRequest$ {
    /** @deprecated use `V3UpdatePaymentMetadataRequest$inboundSchema` instead. */
    export const inboundSchema = V3UpdatePaymentMetadataRequest$inboundSchema;
    /** @deprecated use `V3UpdatePaymentMetadataRequest$outboundSchema` instead. */
    export const outboundSchema = V3UpdatePaymentMetadataRequest$outboundSchema;
    /** @deprecated use `V3UpdatePaymentMetadataRequest$Outbound` instead. */
    export type Outbound = V3UpdatePaymentMetadataRequest$Outbound;
}
