/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    ConfigurationVersion,
    ConfigurationVersion$inboundSchema,
    ConfigurationVersion$Outbound,
    ConfigurationVersion$outboundSchema,
} from "./configurationversion.js";
import { Run, Run$inboundSchema, Run$Outbound, Run$outboundSchema } from "./run.js";
import * as z from "zod";

export type App = {
    /**
     * Unique identifier for the app
     */
    id: string;
    /**
     * Name of the app
     */
    name: string;
    currentConfigurationVersion?: ConfigurationVersion | undefined;
    currentRun?: Run | undefined;
};

/** @internal */
export const App$inboundSchema: z.ZodType<App, z.ZodTypeDef, unknown> = z.object({
    id: z.string(),
    name: z.string(),
    currentConfigurationVersion: ConfigurationVersion$inboundSchema.optional(),
    currentRun: Run$inboundSchema.optional(),
});

/** @internal */
export type App$Outbound = {
    id: string;
    name: string;
    currentConfigurationVersion?: ConfigurationVersion$Outbound | undefined;
    currentRun?: Run$Outbound | undefined;
};

/** @internal */
export const App$outboundSchema: z.ZodType<App$Outbound, z.ZodTypeDef, App> = z.object({
    id: z.string(),
    name: z.string(),
    currentConfigurationVersion: ConfigurationVersion$outboundSchema.optional(),
    currentRun: Run$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace App$ {
    /** @deprecated use `App$inboundSchema` instead. */
    export const inboundSchema = App$inboundSchema;
    /** @deprecated use `App$outboundSchema` instead. */
    export const outboundSchema = App$outboundSchema;
    /** @deprecated use `App$Outbound` instead. */
    export type Outbound = App$Outbound;
}
