/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    Variable,
    Variable$inboundSchema,
    Variable$Outbound,
    Variable$outboundSchema,
} from "./variable.js";
import * as z from "zod";

export type CreateVariableResponse = {
    data: Variable;
};

/** @internal */
export const CreateVariableResponse$inboundSchema: z.ZodType<
    CreateVariableResponse,
    z.ZodTypeDef,
    unknown
> = z.object({
    data: Variable$inboundSchema,
});

/** @internal */
export type CreateVariableResponse$Outbound = {
    data: Variable$Outbound;
};

/** @internal */
export const CreateVariableResponse$outboundSchema: z.ZodType<
    CreateVariableResponse$Outbound,
    z.ZodTypeDef,
    CreateVariableResponse
> = z.object({
    data: Variable$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateVariableResponse$ {
    /** @deprecated use `CreateVariableResponse$inboundSchema` instead. */
    export const inboundSchema = CreateVariableResponse$inboundSchema;
    /** @deprecated use `CreateVariableResponse$outboundSchema` instead. */
    export const outboundSchema = CreateVariableResponse$outboundSchema;
    /** @deprecated use `CreateVariableResponse$Outbound` instead. */
    export type Outbound = CreateVariableResponse$Outbound;
}
