/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    VariableData,
    VariableData$inboundSchema,
    VariableData$Outbound,
    VariableData$outboundSchema,
} from "./variabledata.js";
import * as z from "zod";

export type CreateVariableRequest = {
    variable: VariableData;
};

/** @internal */
export const CreateVariableRequest$inboundSchema: z.ZodType<
    CreateVariableRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    variable: VariableData$inboundSchema,
});

/** @internal */
export type CreateVariableRequest$Outbound = {
    variable: VariableData$Outbound;
};

/** @internal */
export const CreateVariableRequest$outboundSchema: z.ZodType<
    CreateVariableRequest$Outbound,
    z.ZodTypeDef,
    CreateVariableRequest
> = z.object({
    variable: VariableData$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateVariableRequest$ {
    /** @deprecated use `CreateVariableRequest$inboundSchema` instead. */
    export const inboundSchema = CreateVariableRequest$inboundSchema;
    /** @deprecated use `CreateVariableRequest$outboundSchema` instead. */
    export const outboundSchema = CreateVariableRequest$outboundSchema;
    /** @deprecated use `CreateVariableRequest$Outbound` instead. */
    export type Outbound = CreateVariableRequest$Outbound;
}
