/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Detailed log message
 */
export type Diagnostic = {
    /**
     * Severity of the log message
     */
    severity: string;
    detail: string;
    /**
     * Brief summary of the log message
     */
    summary: string;
};

export type Log = {
    /**
     * Log message
     */
    message: string;
    /**
     * Timestamp when the log was created
     */
    timestamp: Date;
    /**
     * Module or component that generated the log
     */
    module: string;
    /**
     * Detailed log message
     */
    diagnostic?: Diagnostic | undefined;
};

/** @internal */
export const Diagnostic$inboundSchema: z.ZodType<Diagnostic, z.ZodTypeDef, unknown> = z.object({
    severity: z.string(),
    detail: z.string(),
    summary: z.string(),
});

/** @internal */
export type Diagnostic$Outbound = {
    severity: string;
    detail: string;
    summary: string;
};

/** @internal */
export const Diagnostic$outboundSchema: z.ZodType<Diagnostic$Outbound, z.ZodTypeDef, Diagnostic> =
    z.object({
        severity: z.string(),
        detail: z.string(),
        summary: z.string(),
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Diagnostic$ {
    /** @deprecated use `Diagnostic$inboundSchema` instead. */
    export const inboundSchema = Diagnostic$inboundSchema;
    /** @deprecated use `Diagnostic$outboundSchema` instead. */
    export const outboundSchema = Diagnostic$outboundSchema;
    /** @deprecated use `Diagnostic$Outbound` instead. */
    export type Outbound = Diagnostic$Outbound;
}

/** @internal */
export const Log$inboundSchema: z.ZodType<Log, z.ZodTypeDef, unknown> = z.object({
    message: z.string(),
    timestamp: z
        .string()
        .datetime({ offset: true })
        .transform((v) => new Date(v)),
    module: z.string(),
    diagnostic: z.lazy(() => Diagnostic$inboundSchema).optional(),
});

/** @internal */
export type Log$Outbound = {
    message: string;
    timestamp: string;
    module: string;
    diagnostic?: Diagnostic$Outbound | undefined;
};

/** @internal */
export const Log$outboundSchema: z.ZodType<Log$Outbound, z.ZodTypeDef, Log> = z.object({
    message: z.string(),
    timestamp: z.date().transform((v) => v.toISOString()),
    module: z.string(),
    diagnostic: z.lazy(() => Diagnostic$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Log$ {
    /** @deprecated use `Log$inboundSchema` instead. */
    export const inboundSchema = Log$inboundSchema;
    /** @deprecated use `Log$outboundSchema` instead. */
    export const outboundSchema = Log$outboundSchema;
    /** @deprecated use `Log$Outbound` instead. */
    export type Outbound = Log$Outbound;
}
