/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { Log, Log$inboundSchema, Log$Outbound, Log$outboundSchema } from "./log.js";
import * as z from "zod";

export type ReadLogsResponse = {
    data?: Array<Log> | undefined;
};

/** @internal */
export const ReadLogsResponse$inboundSchema: z.ZodType<ReadLogsResponse, z.ZodTypeDef, unknown> =
    z.object({
        data: z.array(Log$inboundSchema).optional(),
    });

/** @internal */
export type ReadLogsResponse$Outbound = {
    data?: Array<Log$Outbound> | undefined;
};

/** @internal */
export const ReadLogsResponse$outboundSchema: z.ZodType<
    ReadLogsResponse$Outbound,
    z.ZodTypeDef,
    ReadLogsResponse
> = z.object({
    data: z.array(Log$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ReadLogsResponse$ {
    /** @deprecated use `ReadLogsResponse$inboundSchema` instead. */
    export const inboundSchema = ReadLogsResponse$inboundSchema;
    /** @deprecated use `ReadLogsResponse$outboundSchema` instead. */
    export const outboundSchema = ReadLogsResponse$outboundSchema;
    /** @deprecated use `ReadLogsResponse$Outbound` instead. */
    export type Outbound = ReadLogsResponse$Outbound;
}
