export const POLICIES_LIST = 'policies-list';
export const REPORTS_LIST = 'reports-list';

export const RECONCILIATION_ACTION_DELETE_POLICY =
  'RECONCILIATION-ACTION-DELETE-POLICY';

export const RECONCILIATION_ACTION_CREATE_POLICY =
  'RECONCILIATION-ACTION-CREATE-POLICY';
export const RECONCILIATION_ACTION_RUN = 'RECONCILIATION-ACTION-RUN';
