/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    ConfigurationVersion,
    ConfigurationVersion$inboundSchema,
    ConfigurationVersion$Outbound,
    ConfigurationVersion$outboundSchema,
} from "./configurationversion.js";
import * as z from "zod";

export type ListVersionsResponseData = {
    /**
     * Current page number
     */
    currentPage?: number | undefined;
    /**
     * Previous page number
     */
    previousPage?: number | undefined;
    /**
     * Next page number
     */
    nextPage?: number | undefined;
    /**
     * Total number of pages
     */
    totalPages?: number | undefined;
    /**
     * Total number of items
     */
    totalCount?: number | undefined;
    items: Array<ConfigurationVersion>;
};

export type ListVersionsResponse = {
    data: ListVersionsResponseData;
};

/** @internal */
export const ListVersionsResponseData$inboundSchema: z.ZodType<
    ListVersionsResponseData,
    z.ZodTypeDef,
    unknown
> = z.object({
    currentPage: z.number().int().optional(),
    previousPage: z.number().int().optional(),
    nextPage: z.number().int().optional(),
    totalPages: z.number().int().optional(),
    totalCount: z.number().int().optional(),
    items: z.array(ConfigurationVersion$inboundSchema),
});

/** @internal */
export type ListVersionsResponseData$Outbound = {
    currentPage?: number | undefined;
    previousPage?: number | undefined;
    nextPage?: number | undefined;
    totalPages?: number | undefined;
    totalCount?: number | undefined;
    items: Array<ConfigurationVersion$Outbound>;
};

/** @internal */
export const ListVersionsResponseData$outboundSchema: z.ZodType<
    ListVersionsResponseData$Outbound,
    z.ZodTypeDef,
    ListVersionsResponseData
> = z.object({
    currentPage: z.number().int().optional(),
    previousPage: z.number().int().optional(),
    nextPage: z.number().int().optional(),
    totalPages: z.number().int().optional(),
    totalCount: z.number().int().optional(),
    items: z.array(ConfigurationVersion$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListVersionsResponseData$ {
    /** @deprecated use `ListVersionsResponseData$inboundSchema` instead. */
    export const inboundSchema = ListVersionsResponseData$inboundSchema;
    /** @deprecated use `ListVersionsResponseData$outboundSchema` instead. */
    export const outboundSchema = ListVersionsResponseData$outboundSchema;
    /** @deprecated use `ListVersionsResponseData$Outbound` instead. */
    export type Outbound = ListVersionsResponseData$Outbound;
}

/** @internal */
export const ListVersionsResponse$inboundSchema: z.ZodType<
    ListVersionsResponse,
    z.ZodTypeDef,
    unknown
> = z.object({
    data: z.lazy(() => ListVersionsResponseData$inboundSchema),
});

/** @internal */
export type ListVersionsResponse$Outbound = {
    data: ListVersionsResponseData$Outbound;
};

/** @internal */
export const ListVersionsResponse$outboundSchema: z.ZodType<
    ListVersionsResponse$Outbound,
    z.ZodTypeDef,
    ListVersionsResponse
> = z.object({
    data: z.lazy(() => ListVersionsResponseData$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListVersionsResponse$ {
    /** @deprecated use `ListVersionsResponse$inboundSchema` instead. */
    export const inboundSchema = ListVersionsResponse$inboundSchema;
    /** @deprecated use `ListVersionsResponse$outboundSchema` instead. */
    export const outboundSchema = ListVersionsResponse$outboundSchema;
    /** @deprecated use `ListVersionsResponse$Outbound` instead. */
    export type Outbound = ListVersionsResponse$Outbound;
}
