/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { App, App$inboundSchema, App$Outbound, App$outboundSchema } from "./app.js";
import * as z from "zod";

export type Data = {
    /**
     * Current page number
     */
    currentPage?: number | undefined;
    /**
     * Previous page number
     */
    previousPage?: number | undefined;
    /**
     * Next page number
     */
    nextPage?: number | undefined;
    /**
     * Total number of pages
     */
    totalPages?: number | undefined;
    /**
     * Total number of items
     */
    totalCount?: number | undefined;
    items: Array<App>;
};

export type ListAppsResponse = {
    data: Data;
};

/** @internal */
export const Data$inboundSchema: z.ZodType<Data, z.ZodTypeDef, unknown> = z.object({
    currentPage: z.number().int().optional(),
    previousPage: z.number().int().optional(),
    nextPage: z.number().int().optional(),
    totalPages: z.number().int().optional(),
    totalCount: z.number().int().optional(),
    items: z.array(App$inboundSchema),
});

/** @internal */
export type Data$Outbound = {
    currentPage?: number | undefined;
    previousPage?: number | undefined;
    nextPage?: number | undefined;
    totalPages?: number | undefined;
    totalCount?: number | undefined;
    items: Array<App$Outbound>;
};

/** @internal */
export const Data$outboundSchema: z.ZodType<Data$Outbound, z.ZodTypeDef, Data> = z.object({
    currentPage: z.number().int().optional(),
    previousPage: z.number().int().optional(),
    nextPage: z.number().int().optional(),
    totalPages: z.number().int().optional(),
    totalCount: z.number().int().optional(),
    items: z.array(App$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Data$ {
    /** @deprecated use `Data$inboundSchema` instead. */
    export const inboundSchema = Data$inboundSchema;
    /** @deprecated use `Data$outboundSchema` instead. */
    export const outboundSchema = Data$outboundSchema;
    /** @deprecated use `Data$Outbound` instead. */
    export type Outbound = Data$Outbound;
}

/** @internal */
export const ListAppsResponse$inboundSchema: z.ZodType<ListAppsResponse, z.ZodTypeDef, unknown> =
    z.object({
        data: z.lazy(() => Data$inboundSchema),
    });

/** @internal */
export type ListAppsResponse$Outbound = {
    data: Data$Outbound;
};

/** @internal */
export const ListAppsResponse$outboundSchema: z.ZodType<
    ListAppsResponse$Outbound,
    z.ZodTypeDef,
    ListAppsResponse
> = z.object({
    data: z.lazy(() => Data$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListAppsResponse$ {
    /** @deprecated use `ListAppsResponse$inboundSchema` instead. */
    export const inboundSchema = ListAppsResponse$inboundSchema;
    /** @deprecated use `ListAppsResponse$outboundSchema` instead. */
    export const outboundSchema = ListAppsResponse$outboundSchema;
    /** @deprecated use `ListAppsResponse$Outbound` instead. */
    export type Outbound = ListAppsResponse$Outbound;
}
