/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types/enums.js";
import * as z from "zod";

/**
 * Category of the variable
 */
export const VariableDataCategory = {
    Env: "env",
    Terraform: "terraform",
} as const;
/**
 * Category of the variable
 */
export type VariableDataCategory = ClosedEnum<typeof VariableDataCategory>;

export type VariableData = {
    /**
     * Key of the variable
     */
    key: string;
    /**
     * Value of the variable
     */
    value: string;
    /**
     * Description of the variable
     */
    description?: string | undefined;
    /**
     * Whether the variable is sensitive
     */
    sensitive: boolean;
    /**
     * Category of the variable
     */
    category: VariableDataCategory;
};

/** @internal */
export const VariableDataCategory$inboundSchema: z.ZodNativeEnum<typeof VariableDataCategory> =
    z.nativeEnum(VariableDataCategory);

/** @internal */
export const VariableDataCategory$outboundSchema: z.ZodNativeEnum<typeof VariableDataCategory> =
    VariableDataCategory$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace VariableDataCategory$ {
    /** @deprecated use `VariableDataCategory$inboundSchema` instead. */
    export const inboundSchema = VariableDataCategory$inboundSchema;
    /** @deprecated use `VariableDataCategory$outboundSchema` instead. */
    export const outboundSchema = VariableDataCategory$outboundSchema;
}

/** @internal */
export const VariableData$inboundSchema: z.ZodType<VariableData, z.ZodTypeDef, unknown> = z.object({
    key: z.string(),
    value: z.string(),
    description: z.string().optional(),
    sensitive: z.boolean(),
    category: VariableDataCategory$inboundSchema,
});

/** @internal */
export type VariableData$Outbound = {
    key: string;
    value: string;
    description?: string | undefined;
    sensitive: boolean;
    category: string;
};

/** @internal */
export const VariableData$outboundSchema: z.ZodType<
    VariableData$Outbound,
    z.ZodTypeDef,
    VariableData
> = z.object({
    key: z.string(),
    value: z.string(),
    description: z.string().optional(),
    sensitive: z.boolean(),
    category: VariableDataCategory$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace VariableData$ {
    /** @deprecated use `VariableData$inboundSchema` instead. */
    export const inboundSchema = VariableData$inboundSchema;
    /** @deprecated use `VariableData$outboundSchema` instead. */
    export const outboundSchema = VariableData$outboundSchema;
    /** @deprecated use `VariableData$Outbound` instead. */
    export type Outbound = VariableData$Outbound;
}
