/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    FlowsAccount,
    FlowsAccount$inboundSchema,
    FlowsAccount$Outbound,
    FlowsAccount$outboundSchema,
} from "./flowsaccount.js";
import * as z from "zod";

export type ActivityGetAccountOutput = {
    data: FlowsAccount;
};

/** @internal */
export const ActivityGetAccountOutput$inboundSchema: z.ZodType<
    ActivityGetAccountOutput,
    z.ZodTypeDef,
    unknown
> = z.object({
    data: FlowsAccount$inboundSchema,
});

/** @internal */
export type ActivityGetAccountOutput$Outbound = {
    data: FlowsAccount$Outbound;
};

/** @internal */
export const ActivityGetAccountOutput$outboundSchema: z.ZodType<
    ActivityGetAccountOutput$Outbound,
    z.ZodTypeDef,
    ActivityGetAccountOutput
> = z.object({
    data: FlowsAccount$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ActivityGetAccountOutput$ {
    /** @deprecated use `ActivityGetAccountOutput$inboundSchema` instead. */
    export const inboundSchema = ActivityGetAccountOutput$inboundSchema;
    /** @deprecated use `ActivityGetAccountOutput$outboundSchema` instead. */
    export const outboundSchema = ActivityGetAccountOutput$outboundSchema;
    /** @deprecated use `ActivityGetAccountOutput$Outbound` instead. */
    export type Outbound = ActivityGetAccountOutput$Outbound;
}
