/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    WebhooksConfig,
    WebhooksConfig$inboundSchema,
    WebhooksConfig$Outbound,
    WebhooksConfig$outboundSchema,
} from "./webhooksconfig.js";
import * as z from "zod";

export type Attempt = {
    id: string;
    webhookID: string;
    createdAt: Date;
    updatedAt: Date;
    config: WebhooksConfig;
    payload: string;
    statusCode: number;
    retryAttempt: number;
    status: string;
    nextRetryAfter?: Date | undefined;
};

/** @internal */
export const Attempt$inboundSchema: z.ZodType<Attempt, z.ZodTypeDef, unknown> = z.object({
    id: z.string(),
    webhookID: z.string(),
    createdAt: z
        .string()
        .datetime({ offset: true })
        .transform((v) => new Date(v)),
    updatedAt: z
        .string()
        .datetime({ offset: true })
        .transform((v) => new Date(v)),
    config: WebhooksConfig$inboundSchema,
    payload: z.string(),
    statusCode: z.number().int(),
    retryAttempt: z.number().int(),
    status: z.string(),
    nextRetryAfter: z
        .string()
        .datetime({ offset: true })
        .transform((v) => new Date(v))
        .optional(),
});

/** @internal */
export type Attempt$Outbound = {
    id: string;
    webhookID: string;
    createdAt: string;
    updatedAt: string;
    config: WebhooksConfig$Outbound;
    payload: string;
    statusCode: number;
    retryAttempt: number;
    status: string;
    nextRetryAfter?: string | undefined;
};

/** @internal */
export const Attempt$outboundSchema: z.ZodType<Attempt$Outbound, z.ZodTypeDef, Attempt> = z.object({
    id: z.string(),
    webhookID: z.string(),
    createdAt: z.date().transform((v) => v.toISOString()),
    updatedAt: z.date().transform((v) => v.toISOString()),
    config: WebhooksConfig$outboundSchema,
    payload: z.string(),
    statusCode: z.number().int(),
    retryAttempt: z.number().int(),
    status: z.string(),
    nextRetryAfter: z
        .date()
        .transform((v) => v.toISOString())
        .optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Attempt$ {
    /** @deprecated use `Attempt$inboundSchema` instead. */
    export const inboundSchema = Attempt$inboundSchema;
    /** @deprecated use `Attempt$outboundSchema` instead. */
    export const outboundSchema = Attempt$outboundSchema;
    /** @deprecated use `Attempt$Outbound` instead. */
    export type Outbound = Attempt$Outbound;
}
