/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    AccountBalance,
    AccountBalance$inboundSchema,
    AccountBalance$Outbound,
    AccountBalance$outboundSchema,
} from "./accountbalance.js";
import * as z from "zod";

export type BalancesCursorCursor = {
    pageSize: number;
    hasMore: boolean;
    previous?: string | undefined;
    next?: string | undefined;
    data: Array<AccountBalance>;
};

export type BalancesCursor = {
    cursor: BalancesCursorCursor;
};

/** @internal */
export const BalancesCursorCursor$inboundSchema: z.ZodType<
    BalancesCursorCursor,
    z.ZodTypeDef,
    unknown
> = z.object({
    pageSize: z.number().int(),
    hasMore: z.boolean(),
    previous: z.string().optional(),
    next: z.string().optional(),
    data: z.array(AccountBalance$inboundSchema),
});

/** @internal */
export type BalancesCursorCursor$Outbound = {
    pageSize: number;
    hasMore: boolean;
    previous?: string | undefined;
    next?: string | undefined;
    data: Array<AccountBalance$Outbound>;
};

/** @internal */
export const BalancesCursorCursor$outboundSchema: z.ZodType<
    BalancesCursorCursor$Outbound,
    z.ZodTypeDef,
    BalancesCursorCursor
> = z.object({
    pageSize: z.number().int(),
    hasMore: z.boolean(),
    previous: z.string().optional(),
    next: z.string().optional(),
    data: z.array(AccountBalance$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BalancesCursorCursor$ {
    /** @deprecated use `BalancesCursorCursor$inboundSchema` instead. */
    export const inboundSchema = BalancesCursorCursor$inboundSchema;
    /** @deprecated use `BalancesCursorCursor$outboundSchema` instead. */
    export const outboundSchema = BalancesCursorCursor$outboundSchema;
    /** @deprecated use `BalancesCursorCursor$Outbound` instead. */
    export type Outbound = BalancesCursorCursor$Outbound;
}

/** @internal */
export const BalancesCursor$inboundSchema: z.ZodType<BalancesCursor, z.ZodTypeDef, unknown> =
    z.object({
        cursor: z.lazy(() => BalancesCursorCursor$inboundSchema),
    });

/** @internal */
export type BalancesCursor$Outbound = {
    cursor: BalancesCursorCursor$Outbound;
};

/** @internal */
export const BalancesCursor$outboundSchema: z.ZodType<
    BalancesCursor$Outbound,
    z.ZodTypeDef,
    BalancesCursor
> = z.object({
    cursor: z.lazy(() => BalancesCursorCursor$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BalancesCursor$ {
    /** @deprecated use `BalancesCursor$inboundSchema` instead. */
    export const inboundSchema = BalancesCursor$inboundSchema;
    /** @deprecated use `BalancesCursor$outboundSchema` instead. */
    export const outboundSchema = BalancesCursor$outboundSchema;
    /** @deprecated use `BalancesCursor$Outbound` instead. */
    export type Outbound = BalancesCursor$Outbound;
}
