/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type BankAccountRequest = {
    country: string;
    connectorID?: string | undefined;
    name: string;
    accountNumber?: string | undefined;
    iban?: string | undefined;
    swiftBicCode?: string | undefined;
    metadata?: { [k: string]: string } | null | undefined;
};

/** @internal */
export const BankAccountRequest$inboundSchema: z.ZodType<
    BankAccountRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    country: z.string(),
    connectorID: z.string().optional(),
    name: z.string(),
    accountNumber: z.string().optional(),
    iban: z.string().optional(),
    swiftBicCode: z.string().optional(),
    metadata: z.nullable(z.record(z.string())).optional(),
});

/** @internal */
export type BankAccountRequest$Outbound = {
    country: string;
    connectorID?: string | undefined;
    name: string;
    accountNumber?: string | undefined;
    iban?: string | undefined;
    swiftBicCode?: string | undefined;
    metadata?: { [k: string]: string } | null | undefined;
};

/** @internal */
export const BankAccountRequest$outboundSchema: z.ZodType<
    BankAccountRequest$Outbound,
    z.ZodTypeDef,
    BankAccountRequest
> = z.object({
    country: z.string(),
    connectorID: z.string().optional(),
    name: z.string(),
    accountNumber: z.string().optional(),
    iban: z.string().optional(),
    swiftBicCode: z.string().optional(),
    metadata: z.nullable(z.record(z.string())).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BankAccountRequest$ {
    /** @deprecated use `BankAccountRequest$inboundSchema` instead. */
    export const inboundSchema = BankAccountRequest$inboundSchema;
    /** @deprecated use `BankAccountRequest$outboundSchema` instead. */
    export const outboundSchema = BankAccountRequest$outboundSchema;
    /** @deprecated use `BankAccountRequest$Outbound` instead. */
    export type Outbound = BankAccountRequest$Outbound;
}
