/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    Subject,
    Subject$inboundSchema,
    Subject$Outbound,
    Subject$outboundSchema,
} from "./subject.js";
import * as z from "zod";

export type ExpandedDebitHold = {
    /**
     * The unique ID of the hold.
     */
    id: string;
    /**
     * The ID of the wallet the hold is associated with.
     */
    walletID: string;
    /**
     * Metadata associated with the hold.
     */
    metadata: { [k: string]: string };
    asset: string;
    description: string;
    destination?: Subject | undefined;
    /**
     * Remaining amount on hold
     */
    remaining: bigint;
    /**
     * Original amount on hold
     */
    originalAmount: bigint;
};

/** @internal */
export const ExpandedDebitHold$inboundSchema: z.ZodType<ExpandedDebitHold, z.ZodTypeDef, unknown> =
    z.object({
        id: z.string(),
        walletID: z.string(),
        metadata: z.record(z.string()),
        asset: z.string(),
        description: z.string(),
        destination: Subject$inboundSchema.optional(),
        remaining: z.number().transform((v) => BigInt(v)),
        originalAmount: z.number().transform((v) => BigInt(v)),
    });

/** @internal */
export type ExpandedDebitHold$Outbound = {
    id: string;
    walletID: string;
    metadata: { [k: string]: string };
    asset: string;
    description: string;
    destination?: Subject$Outbound | undefined;
    remaining: number;
    originalAmount: number;
};

/** @internal */
export const ExpandedDebitHold$outboundSchema: z.ZodType<
    ExpandedDebitHold$Outbound,
    z.ZodTypeDef,
    ExpandedDebitHold
> = z.object({
    id: z.string(),
    walletID: z.string(),
    metadata: z.record(z.string()),
    asset: z.string(),
    description: z.string(),
    destination: Subject$outboundSchema.optional(),
    remaining: z.bigint().transform((v) => Number(v)),
    originalAmount: z.bigint().transform((v) => Number(v)),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ExpandedDebitHold$ {
    /** @deprecated use `ExpandedDebitHold$inboundSchema` instead. */
    export const inboundSchema = ExpandedDebitHold$inboundSchema;
    /** @deprecated use `ExpandedDebitHold$outboundSchema` instead. */
    export const outboundSchema = ExpandedDebitHold$outboundSchema;
    /** @deprecated use `ExpandedDebitHold$Outbound` instead. */
    export type Outbound = ExpandedDebitHold$Outbound;
}
