/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    FlowsPaymentStatus,
    FlowsPaymentStatus$inboundSchema,
    FlowsPaymentStatus$outboundSchema,
} from "./flowspaymentstatus.js";
import * as z from "zod";

export type FlowsPaymentAdjustmentRaw = {};

export type FlowsPaymentAdjustment = {
    status: FlowsPaymentStatus;
    amount: bigint;
    date: Date;
    raw: FlowsPaymentAdjustmentRaw;
    absolute: boolean;
};

/** @internal */
export const FlowsPaymentAdjustmentRaw$inboundSchema: z.ZodType<
    FlowsPaymentAdjustmentRaw,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type FlowsPaymentAdjustmentRaw$Outbound = {};

/** @internal */
export const FlowsPaymentAdjustmentRaw$outboundSchema: z.ZodType<
    FlowsPaymentAdjustmentRaw$Outbound,
    z.ZodTypeDef,
    FlowsPaymentAdjustmentRaw
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FlowsPaymentAdjustmentRaw$ {
    /** @deprecated use `FlowsPaymentAdjustmentRaw$inboundSchema` instead. */
    export const inboundSchema = FlowsPaymentAdjustmentRaw$inboundSchema;
    /** @deprecated use `FlowsPaymentAdjustmentRaw$outboundSchema` instead. */
    export const outboundSchema = FlowsPaymentAdjustmentRaw$outboundSchema;
    /** @deprecated use `FlowsPaymentAdjustmentRaw$Outbound` instead. */
    export type Outbound = FlowsPaymentAdjustmentRaw$Outbound;
}

/** @internal */
export const FlowsPaymentAdjustment$inboundSchema: z.ZodType<
    FlowsPaymentAdjustment,
    z.ZodTypeDef,
    unknown
> = z.object({
    status: FlowsPaymentStatus$inboundSchema,
    amount: z.number().transform((v) => BigInt(v)),
    date: z
        .string()
        .datetime({ offset: true })
        .transform((v) => new Date(v)),
    raw: z.lazy(() => FlowsPaymentAdjustmentRaw$inboundSchema),
    absolute: z.boolean(),
});

/** @internal */
export type FlowsPaymentAdjustment$Outbound = {
    status: string;
    amount: number;
    date: string;
    raw: FlowsPaymentAdjustmentRaw$Outbound;
    absolute: boolean;
};

/** @internal */
export const FlowsPaymentAdjustment$outboundSchema: z.ZodType<
    FlowsPaymentAdjustment$Outbound,
    z.ZodTypeDef,
    FlowsPaymentAdjustment
> = z.object({
    status: FlowsPaymentStatus$outboundSchema,
    amount: z.bigint().transform((v) => Number(v)),
    date: z.date().transform((v) => v.toISOString()),
    raw: z.lazy(() => FlowsPaymentAdjustmentRaw$outboundSchema),
    absolute: z.boolean(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FlowsPaymentAdjustment$ {
    /** @deprecated use `FlowsPaymentAdjustment$inboundSchema` instead. */
    export const inboundSchema = FlowsPaymentAdjustment$inboundSchema;
    /** @deprecated use `FlowsPaymentAdjustment$outboundSchema` instead. */
    export const outboundSchema = FlowsPaymentAdjustment$outboundSchema;
    /** @deprecated use `FlowsPaymentAdjustment$Outbound` instead. */
    export type Outbound = FlowsPaymentAdjustment$Outbound;
}
