/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types/enums.js";
import * as z from "zod";

export const Type = {
    NewTransaction: "NEW_TRANSACTION",
    SetMetadata: "SET_METADATA",
} as const;
export type Type = ClosedEnum<typeof Type>;

export type Log = {
    id: number;
    type: Type;
    data: { [k: string]: any };
    hash: string;
    date: Date;
};

/** @internal */
export const Type$inboundSchema: z.ZodNativeEnum<typeof Type> = z.nativeEnum(Type);

/** @internal */
export const Type$outboundSchema: z.ZodNativeEnum<typeof Type> = Type$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Type$ {
    /** @deprecated use `Type$inboundSchema` instead. */
    export const inboundSchema = Type$inboundSchema;
    /** @deprecated use `Type$outboundSchema` instead. */
    export const outboundSchema = Type$outboundSchema;
}

/** @internal */
export const Log$inboundSchema: z.ZodType<Log, z.ZodTypeDef, unknown> = z.object({
    id: z.number().int(),
    type: Type$inboundSchema,
    data: z.record(z.any()),
    hash: z.string(),
    date: z
        .string()
        .datetime({ offset: true })
        .transform((v) => new Date(v)),
});

/** @internal */
export type Log$Outbound = {
    id: number;
    type: string;
    data: { [k: string]: any };
    hash: string;
    date: string;
};

/** @internal */
export const Log$outboundSchema: z.ZodType<Log$Outbound, z.ZodTypeDef, Log> = z.object({
    id: z.number().int(),
    type: Type$outboundSchema,
    data: z.record(z.any()),
    hash: z.string(),
    date: z.date().transform((v) => v.toISOString()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Log$ {
    /** @deprecated use `Log$inboundSchema` instead. */
    export const inboundSchema = Log$inboundSchema;
    /** @deprecated use `Log$outboundSchema` instead. */
    export const outboundSchema = Log$outboundSchema;
    /** @deprecated use `Log$Outbound` instead. */
    export type Outbound = Log$Outbound;
}
