/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ReverseTransferInitiationRequest = {
    reference: string;
    description: string;
    amount: bigint;
    asset: string;
    metadata: { [k: string]: string } | null;
};

/** @internal */
export const ReverseTransferInitiationRequest$inboundSchema: z.ZodType<
    ReverseTransferInitiationRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    reference: z.string(),
    description: z.string(),
    amount: z.number().transform((v) => BigInt(v)),
    asset: z.string(),
    metadata: z.nullable(z.record(z.string())),
});

/** @internal */
export type ReverseTransferInitiationRequest$Outbound = {
    reference: string;
    description: string;
    amount: number;
    asset: string;
    metadata: { [k: string]: string } | null;
};

/** @internal */
export const ReverseTransferInitiationRequest$outboundSchema: z.ZodType<
    ReverseTransferInitiationRequest$Outbound,
    z.ZodTypeDef,
    ReverseTransferInitiationRequest
> = z.object({
    reference: z.string(),
    description: z.string(),
    amount: z.bigint().transform((v) => Number(v)),
    asset: z.string(),
    metadata: z.nullable(z.record(z.string())),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ReverseTransferInitiationRequest$ {
    /** @deprecated use `ReverseTransferInitiationRequest$inboundSchema` instead. */
    export const inboundSchema = ReverseTransferInitiationRequest$inboundSchema;
    /** @deprecated use `ReverseTransferInitiationRequest$outboundSchema` instead. */
    export const outboundSchema = ReverseTransferInitiationRequest$outboundSchema;
    /** @deprecated use `ReverseTransferInitiationRequest$Outbound` instead. */
    export type Outbound = ReverseTransferInitiationRequest$Outbound;
}
