/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { TaskStatus, TaskStatus$inboundSchema, TaskStatus$outboundSchema } from "./taskstatus.js";
import * as z from "zod";

export type TaskWiseState = {};

export type TaskWiseDescriptor = {
    name?: string | undefined;
    key?: string | undefined;
    profileID?: number | undefined;
};

export type TaskWise = {
    id: string;
    connectorID: string;
    createdAt: Date;
    updatedAt: Date;
    status: TaskStatus;
    state?: TaskWiseState | null | undefined;
    error?: string | null | undefined;
    descriptor: TaskWiseDescriptor;
};

/** @internal */
export const TaskWiseState$inboundSchema: z.ZodType<TaskWiseState, z.ZodTypeDef, unknown> =
    z.object({});

/** @internal */
export type TaskWiseState$Outbound = {};

/** @internal */
export const TaskWiseState$outboundSchema: z.ZodType<
    TaskWiseState$Outbound,
    z.ZodTypeDef,
    TaskWiseState
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskWiseState$ {
    /** @deprecated use `TaskWiseState$inboundSchema` instead. */
    export const inboundSchema = TaskWiseState$inboundSchema;
    /** @deprecated use `TaskWiseState$outboundSchema` instead. */
    export const outboundSchema = TaskWiseState$outboundSchema;
    /** @deprecated use `TaskWiseState$Outbound` instead. */
    export type Outbound = TaskWiseState$Outbound;
}

/** @internal */
export const TaskWiseDescriptor$inboundSchema: z.ZodType<
    TaskWiseDescriptor,
    z.ZodTypeDef,
    unknown
> = z.object({
    name: z.string().optional(),
    key: z.string().optional(),
    profileID: z.number().int().optional(),
});

/** @internal */
export type TaskWiseDescriptor$Outbound = {
    name?: string | undefined;
    key?: string | undefined;
    profileID?: number | undefined;
};

/** @internal */
export const TaskWiseDescriptor$outboundSchema: z.ZodType<
    TaskWiseDescriptor$Outbound,
    z.ZodTypeDef,
    TaskWiseDescriptor
> = z.object({
    name: z.string().optional(),
    key: z.string().optional(),
    profileID: z.number().int().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskWiseDescriptor$ {
    /** @deprecated use `TaskWiseDescriptor$inboundSchema` instead. */
    export const inboundSchema = TaskWiseDescriptor$inboundSchema;
    /** @deprecated use `TaskWiseDescriptor$outboundSchema` instead. */
    export const outboundSchema = TaskWiseDescriptor$outboundSchema;
    /** @deprecated use `TaskWiseDescriptor$Outbound` instead. */
    export type Outbound = TaskWiseDescriptor$Outbound;
}

/** @internal */
export const TaskWise$inboundSchema: z.ZodType<TaskWise, z.ZodTypeDef, unknown> = z.object({
    id: z.string(),
    connectorID: z.string(),
    createdAt: z
        .string()
        .datetime({ offset: true })
        .transform((v) => new Date(v)),
    updatedAt: z
        .string()
        .datetime({ offset: true })
        .transform((v) => new Date(v)),
    status: TaskStatus$inboundSchema,
    state: z.nullable(z.lazy(() => TaskWiseState$inboundSchema)).optional(),
    error: z.nullable(z.string()).optional(),
    descriptor: z.lazy(() => TaskWiseDescriptor$inboundSchema),
});

/** @internal */
export type TaskWise$Outbound = {
    id: string;
    connectorID: string;
    createdAt: string;
    updatedAt: string;
    status: string;
    state?: TaskWiseState$Outbound | null | undefined;
    error?: string | null | undefined;
    descriptor: TaskWiseDescriptor$Outbound;
};

/** @internal */
export const TaskWise$outboundSchema: z.ZodType<TaskWise$Outbound, z.ZodTypeDef, TaskWise> =
    z.object({
        id: z.string(),
        connectorID: z.string(),
        createdAt: z.date().transform((v) => v.toISOString()),
        updatedAt: z.date().transform((v) => v.toISOString()),
        status: TaskStatus$outboundSchema,
        state: z.nullable(z.lazy(() => TaskWiseState$outboundSchema)).optional(),
        error: z.nullable(z.string()).optional(),
        descriptor: z.lazy(() => TaskWiseDescriptor$outboundSchema),
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskWise$ {
    /** @deprecated use `TaskWise$inboundSchema` instead. */
    export const inboundSchema = TaskWise$inboundSchema;
    /** @deprecated use `TaskWise$outboundSchema` instead. */
    export const outboundSchema = TaskWise$outboundSchema;
    /** @deprecated use `TaskWise$Outbound` instead. */
    export type Outbound = TaskWise$Outbound;
}
