/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types/enums.js";
import * as z from "zod";

export const TransferInitiationRequestType = {
    Transfer: "TRANSFER",
    Payout: "PAYOUT",
} as const;
export type TransferInitiationRequestType = ClosedEnum<typeof TransferInitiationRequestType>;

export type TransferInitiationRequest = {
    reference: string;
    scheduledAt: Date;
    description: string;
    sourceAccountID: string;
    destinationAccountID: string;
    connectorID?: string | undefined;
    type: TransferInitiationRequestType;
    amount: bigint;
    asset: string;
    validated: boolean;
    metadata?: { [k: string]: string } | null | undefined;
};

/** @internal */
export const TransferInitiationRequestType$inboundSchema: z.ZodNativeEnum<
    typeof TransferInitiationRequestType
> = z.nativeEnum(TransferInitiationRequestType);

/** @internal */
export const TransferInitiationRequestType$outboundSchema: z.ZodNativeEnum<
    typeof TransferInitiationRequestType
> = TransferInitiationRequestType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TransferInitiationRequestType$ {
    /** @deprecated use `TransferInitiationRequestType$inboundSchema` instead. */
    export const inboundSchema = TransferInitiationRequestType$inboundSchema;
    /** @deprecated use `TransferInitiationRequestType$outboundSchema` instead. */
    export const outboundSchema = TransferInitiationRequestType$outboundSchema;
}

/** @internal */
export const TransferInitiationRequest$inboundSchema: z.ZodType<
    TransferInitiationRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    reference: z.string(),
    scheduledAt: z
        .string()
        .datetime({ offset: true })
        .transform((v) => new Date(v)),
    description: z.string(),
    sourceAccountID: z.string(),
    destinationAccountID: z.string(),
    connectorID: z.string().optional(),
    type: TransferInitiationRequestType$inboundSchema,
    amount: z.number().transform((v) => BigInt(v)),
    asset: z.string(),
    validated: z.boolean(),
    metadata: z.nullable(z.record(z.string())).optional(),
});

/** @internal */
export type TransferInitiationRequest$Outbound = {
    reference: string;
    scheduledAt: string;
    description: string;
    sourceAccountID: string;
    destinationAccountID: string;
    connectorID?: string | undefined;
    type: string;
    amount: number;
    asset: string;
    validated: boolean;
    metadata?: { [k: string]: string } | null | undefined;
};

/** @internal */
export const TransferInitiationRequest$outboundSchema: z.ZodType<
    TransferInitiationRequest$Outbound,
    z.ZodTypeDef,
    TransferInitiationRequest
> = z.object({
    reference: z.string(),
    scheduledAt: z.date().transform((v) => v.toISOString()),
    description: z.string(),
    sourceAccountID: z.string(),
    destinationAccountID: z.string(),
    connectorID: z.string().optional(),
    type: TransferInitiationRequestType$outboundSchema,
    amount: z.bigint().transform((v) => Number(v)),
    asset: z.string(),
    validated: z.boolean(),
    metadata: z.nullable(z.record(z.string())).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TransferInitiationRequest$ {
    /** @deprecated use `TransferInitiationRequest$inboundSchema` instead. */
    export const inboundSchema = TransferInitiationRequest$inboundSchema;
    /** @deprecated use `TransferInitiationRequest$outboundSchema` instead. */
    export const outboundSchema = TransferInitiationRequest$outboundSchema;
    /** @deprecated use `TransferInitiationRequest$Outbound` instead. */
    export type Outbound = TransferInitiationRequest$Outbound;
}
