/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    FlowsV2PostTransaction,
    FlowsV2PostTransaction$inboundSchema,
    FlowsV2PostTransaction$Outbound,
    FlowsV2PostTransaction$outboundSchema,
} from "./flowsv2posttransaction.js";
import * as z from "zod";

export type V2ActivityCreateTransaction = {
    ledger?: string | undefined;
    data?: FlowsV2PostTransaction | undefined;
};

/** @internal */
export const V2ActivityCreateTransaction$inboundSchema: z.ZodType<
    V2ActivityCreateTransaction,
    z.ZodTypeDef,
    unknown
> = z.object({
    ledger: z.string().optional(),
    data: FlowsV2PostTransaction$inboundSchema.optional(),
});

/** @internal */
export type V2ActivityCreateTransaction$Outbound = {
    ledger?: string | undefined;
    data?: FlowsV2PostTransaction$Outbound | undefined;
};

/** @internal */
export const V2ActivityCreateTransaction$outboundSchema: z.ZodType<
    V2ActivityCreateTransaction$Outbound,
    z.ZodTypeDef,
    V2ActivityCreateTransaction
> = z.object({
    ledger: z.string().optional(),
    data: FlowsV2PostTransaction$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2ActivityCreateTransaction$ {
    /** @deprecated use `V2ActivityCreateTransaction$inboundSchema` instead. */
    export const inboundSchema = V2ActivityCreateTransaction$inboundSchema;
    /** @deprecated use `V2ActivityCreateTransaction$outboundSchema` instead. */
    export const outboundSchema = V2ActivityCreateTransaction$outboundSchema;
    /** @deprecated use `V2ActivityCreateTransaction$Outbound` instead. */
    export type Outbound = V2ActivityCreateTransaction$Outbound;
}
