/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    V2TargetId,
    V2TargetId$inboundSchema,
    V2TargetId$Outbound,
    V2TargetId$outboundSchema,
} from "./v2targetid.js";
import {
    V2TargetType,
    V2TargetType$inboundSchema,
    V2TargetType$outboundSchema,
} from "./v2targettype.js";
import * as z from "zod";

export type Data = {
    targetId: V2TargetId;
    targetType: V2TargetType;
    metadata: { [k: string]: string };
};

export type V2BulkElementAddMetadata = {
    action: string;
    ik?: string | undefined;
    data?: Data | undefined;
};

/** @internal */
export const Data$inboundSchema: z.ZodType<Data, z.ZodTypeDef, unknown> = z.object({
    targetId: V2TargetId$inboundSchema,
    targetType: V2TargetType$inboundSchema,
    metadata: z.record(z.string()),
});

/** @internal */
export type Data$Outbound = {
    targetId: V2TargetId$Outbound;
    targetType: string;
    metadata: { [k: string]: string };
};

/** @internal */
export const Data$outboundSchema: z.ZodType<Data$Outbound, z.ZodTypeDef, Data> = z.object({
    targetId: V2TargetId$outboundSchema,
    targetType: V2TargetType$outboundSchema,
    metadata: z.record(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Data$ {
    /** @deprecated use `Data$inboundSchema` instead. */
    export const inboundSchema = Data$inboundSchema;
    /** @deprecated use `Data$outboundSchema` instead. */
    export const outboundSchema = Data$outboundSchema;
    /** @deprecated use `Data$Outbound` instead. */
    export type Outbound = Data$Outbound;
}

/** @internal */
export const V2BulkElementAddMetadata$inboundSchema: z.ZodType<
    V2BulkElementAddMetadata,
    z.ZodTypeDef,
    unknown
> = z.object({
    action: z.string(),
    ik: z.string().optional(),
    data: z.lazy(() => Data$inboundSchema).optional(),
});

/** @internal */
export type V2BulkElementAddMetadata$Outbound = {
    action: string;
    ik?: string | undefined;
    data?: Data$Outbound | undefined;
};

/** @internal */
export const V2BulkElementAddMetadata$outboundSchema: z.ZodType<
    V2BulkElementAddMetadata$Outbound,
    z.ZodTypeDef,
    V2BulkElementAddMetadata
> = z.object({
    action: z.string(),
    ik: z.string().optional(),
    data: z.lazy(() => Data$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2BulkElementAddMetadata$ {
    /** @deprecated use `V2BulkElementAddMetadata$inboundSchema` instead. */
    export const inboundSchema = V2BulkElementAddMetadata$inboundSchema;
    /** @deprecated use `V2BulkElementAddMetadata$outboundSchema` instead. */
    export const outboundSchema = V2BulkElementAddMetadata$outboundSchema;
    /** @deprecated use `V2BulkElementAddMetadata$Outbound` instead. */
    export type Outbound = V2BulkElementAddMetadata$Outbound;
}
