/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    V2Exporter,
    V2Exporter$inboundSchema,
    V2Exporter$Outbound,
    V2Exporter$outboundSchema,
} from "./v2exporter.js";
import * as z from "zod";

export type V2GetExporterStateResponse = {
    data: V2Exporter;
};

/** @internal */
export const V2GetExporterStateResponse$inboundSchema: z.ZodType<
    V2GetExporterStateResponse,
    z.ZodTypeDef,
    unknown
> = z.object({
    data: V2Exporter$inboundSchema,
});

/** @internal */
export type V2GetExporterStateResponse$Outbound = {
    data: V2Exporter$Outbound;
};

/** @internal */
export const V2GetExporterStateResponse$outboundSchema: z.ZodType<
    V2GetExporterStateResponse$Outbound,
    z.ZodTypeDef,
    V2GetExporterStateResponse
> = z.object({
    data: V2Exporter$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2GetExporterStateResponse$ {
    /** @deprecated use `V2GetExporterStateResponse$inboundSchema` instead. */
    export const inboundSchema = V2GetExporterStateResponse$inboundSchema;
    /** @deprecated use `V2GetExporterStateResponse$outboundSchema` instead. */
    export const outboundSchema = V2GetExporterStateResponse$outboundSchema;
    /** @deprecated use `V2GetExporterStateResponse$Outbound` instead. */
    export type Outbound = V2GetExporterStateResponse$Outbound;
}
