/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { V2Log, V2Log$inboundSchema, V2Log$Outbound, V2Log$outboundSchema } from "./v2log.js";
import * as z from "zod";

export type V2LogsCursorResponseCursor = {
    pageSize: number;
    hasMore: boolean;
    previous?: string | undefined;
    next?: string | undefined;
    data: Array<V2Log>;
};

export type V2LogsCursorResponse = {
    cursor: V2LogsCursorResponseCursor;
};

/** @internal */
export const V2LogsCursorResponseCursor$inboundSchema: z.ZodType<
    V2LogsCursorResponseCursor,
    z.ZodTypeDef,
    unknown
> = z.object({
    pageSize: z.number().int(),
    hasMore: z.boolean(),
    previous: z.string().optional(),
    next: z.string().optional(),
    data: z.array(V2Log$inboundSchema),
});

/** @internal */
export type V2LogsCursorResponseCursor$Outbound = {
    pageSize: number;
    hasMore: boolean;
    previous?: string | undefined;
    next?: string | undefined;
    data: Array<V2Log$Outbound>;
};

/** @internal */
export const V2LogsCursorResponseCursor$outboundSchema: z.ZodType<
    V2LogsCursorResponseCursor$Outbound,
    z.ZodTypeDef,
    V2LogsCursorResponseCursor
> = z.object({
    pageSize: z.number().int(),
    hasMore: z.boolean(),
    previous: z.string().optional(),
    next: z.string().optional(),
    data: z.array(V2Log$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2LogsCursorResponseCursor$ {
    /** @deprecated use `V2LogsCursorResponseCursor$inboundSchema` instead. */
    export const inboundSchema = V2LogsCursorResponseCursor$inboundSchema;
    /** @deprecated use `V2LogsCursorResponseCursor$outboundSchema` instead. */
    export const outboundSchema = V2LogsCursorResponseCursor$outboundSchema;
    /** @deprecated use `V2LogsCursorResponseCursor$Outbound` instead. */
    export type Outbound = V2LogsCursorResponseCursor$Outbound;
}

/** @internal */
export const V2LogsCursorResponse$inboundSchema: z.ZodType<
    V2LogsCursorResponse,
    z.ZodTypeDef,
    unknown
> = z.object({
    cursor: z.lazy(() => V2LogsCursorResponseCursor$inboundSchema),
});

/** @internal */
export type V2LogsCursorResponse$Outbound = {
    cursor: V2LogsCursorResponseCursor$Outbound;
};

/** @internal */
export const V2LogsCursorResponse$outboundSchema: z.ZodType<
    V2LogsCursorResponse$Outbound,
    z.ZodTypeDef,
    V2LogsCursorResponse
> = z.object({
    cursor: z.lazy(() => V2LogsCursorResponseCursor$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2LogsCursorResponse$ {
    /** @deprecated use `V2LogsCursorResponse$inboundSchema` instead. */
    export const inboundSchema = V2LogsCursorResponse$inboundSchema;
    /** @deprecated use `V2LogsCursorResponse$outboundSchema` instead. */
    export const outboundSchema = V2LogsCursorResponse$outboundSchema;
    /** @deprecated use `V2LogsCursorResponse$Outbound` instead. */
    export type Outbound = V2LogsCursorResponse$Outbound;
}
