/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    V3AccountTypeEnum,
    V3AccountTypeEnum$inboundSchema,
    V3AccountTypeEnum$outboundSchema,
} from "./v3accounttypeenum.js";
import {
    V3ConnectorBase,
    V3ConnectorBase$inboundSchema,
    V3ConnectorBase$Outbound,
    V3ConnectorBase$outboundSchema,
} from "./v3connectorbase.js";
import * as z from "zod";

export type V3AccountRaw = {};

export type V3Account = {
    id: string;
    connectorID: string;
    connector?: V3ConnectorBase | undefined;
    provider: string;
    reference: string;
    createdAt: Date;
    type: V3AccountTypeEnum;
    name?: string | null | undefined;
    defaultAsset?: string | null | undefined;
    metadata?: { [k: string]: string } | null | undefined;
    raw: V3AccountRaw;
};

/** @internal */
export const V3AccountRaw$inboundSchema: z.ZodType<V3AccountRaw, z.ZodTypeDef, unknown> = z.object(
    {}
);

/** @internal */
export type V3AccountRaw$Outbound = {};

/** @internal */
export const V3AccountRaw$outboundSchema: z.ZodType<
    V3AccountRaw$Outbound,
    z.ZodTypeDef,
    V3AccountRaw
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3AccountRaw$ {
    /** @deprecated use `V3AccountRaw$inboundSchema` instead. */
    export const inboundSchema = V3AccountRaw$inboundSchema;
    /** @deprecated use `V3AccountRaw$outboundSchema` instead. */
    export const outboundSchema = V3AccountRaw$outboundSchema;
    /** @deprecated use `V3AccountRaw$Outbound` instead. */
    export type Outbound = V3AccountRaw$Outbound;
}

/** @internal */
export const V3Account$inboundSchema: z.ZodType<V3Account, z.ZodTypeDef, unknown> = z.object({
    id: z.string(),
    connectorID: z.string(),
    connector: V3ConnectorBase$inboundSchema.optional(),
    provider: z.string(),
    reference: z.string(),
    createdAt: z
        .string()
        .datetime({ offset: true })
        .transform((v) => new Date(v)),
    type: V3AccountTypeEnum$inboundSchema,
    name: z.nullable(z.string()).optional(),
    defaultAsset: z.nullable(z.string()).optional(),
    metadata: z.nullable(z.record(z.string())).optional(),
    raw: z.lazy(() => V3AccountRaw$inboundSchema),
});

/** @internal */
export type V3Account$Outbound = {
    id: string;
    connectorID: string;
    connector?: V3ConnectorBase$Outbound | undefined;
    provider: string;
    reference: string;
    createdAt: string;
    type: string;
    name?: string | null | undefined;
    defaultAsset?: string | null | undefined;
    metadata?: { [k: string]: string } | null | undefined;
    raw: V3AccountRaw$Outbound;
};

/** @internal */
export const V3Account$outboundSchema: z.ZodType<V3Account$Outbound, z.ZodTypeDef, V3Account> =
    z.object({
        id: z.string(),
        connectorID: z.string(),
        connector: V3ConnectorBase$outboundSchema.optional(),
        provider: z.string(),
        reference: z.string(),
        createdAt: z.date().transform((v) => v.toISOString()),
        type: V3AccountTypeEnum$outboundSchema,
        name: z.nullable(z.string()).optional(),
        defaultAsset: z.nullable(z.string()).optional(),
        metadata: z.nullable(z.record(z.string())).optional(),
        raw: z.lazy(() => V3AccountRaw$outboundSchema),
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3Account$ {
    /** @deprecated use `V3Account$inboundSchema` instead. */
    export const inboundSchema = V3Account$inboundSchema;
    /** @deprecated use `V3Account$outboundSchema` instead. */
    export const outboundSchema = V3Account$outboundSchema;
    /** @deprecated use `V3Account$Outbound` instead. */
    export type Outbound = V3Account$Outbound;
}
