/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type V3ColumnConfig = {
    apiKey: string;
    endpoint: string;
    name: string;
    pageSize?: number | undefined;
    pollingPeriod?: string | undefined;
    provider?: string | undefined;
};

/** @internal */
export const V3ColumnConfig$inboundSchema: z.ZodType<V3ColumnConfig, z.ZodTypeDef, unknown> =
    z.object({
        apiKey: z.string(),
        endpoint: z.string(),
        name: z.string(),
        pageSize: z.number().int().default(25),
        pollingPeriod: z.string().optional(),
        provider: z.string().default("Column"),
    });

/** @internal */
export type V3ColumnConfig$Outbound = {
    apiKey: string;
    endpoint: string;
    name: string;
    pageSize: number;
    pollingPeriod?: string | undefined;
    provider: string;
};

/** @internal */
export const V3ColumnConfig$outboundSchema: z.ZodType<
    V3ColumnConfig$Outbound,
    z.ZodTypeDef,
    V3ColumnConfig
> = z.object({
    apiKey: z.string(),
    endpoint: z.string(),
    name: z.string(),
    pageSize: z.number().int().default(25),
    pollingPeriod: z.string().optional(),
    provider: z.string().default("Column"),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3ColumnConfig$ {
    /** @deprecated use `V3ColumnConfig$inboundSchema` instead. */
    export const inboundSchema = V3ColumnConfig$inboundSchema;
    /** @deprecated use `V3ColumnConfig$outboundSchema` instead. */
    export const outboundSchema = V3ColumnConfig$outboundSchema;
    /** @deprecated use `V3ColumnConfig$Outbound` instead. */
    export type Outbound = V3ColumnConfig$Outbound;
}
