/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    V3BankAccount,
    V3BankAccount$inboundSchema,
    V3BankAccount$Outbound,
    V3BankAccount$outboundSchema,
} from "./v3bankaccount.js";
import * as z from "zod";

export type V3GetBankAccountResponse = {
    data: V3BankAccount;
};

/** @internal */
export const V3GetBankAccountResponse$inboundSchema: z.ZodType<
    V3GetBankAccountResponse,
    z.ZodTypeDef,
    unknown
> = z.object({
    data: V3BankAccount$inboundSchema,
});

/** @internal */
export type V3GetBankAccountResponse$Outbound = {
    data: V3BankAccount$Outbound;
};

/** @internal */
export const V3GetBankAccountResponse$outboundSchema: z.ZodType<
    V3GetBankAccountResponse$Outbound,
    z.ZodTypeDef,
    V3GetBankAccountResponse
> = z.object({
    data: V3BankAccount$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3GetBankAccountResponse$ {
    /** @deprecated use `V3GetBankAccountResponse$inboundSchema` instead. */
    export const inboundSchema = V3GetBankAccountResponse$inboundSchema;
    /** @deprecated use `V3GetBankAccountResponse$outboundSchema` instead. */
    export const outboundSchema = V3GetBankAccountResponse$outboundSchema;
    /** @deprecated use `V3GetBankAccountResponse$Outbound` instead. */
    export type Outbound = V3GetBankAccountResponse$Outbound;
}
