/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type V3IncreaseConfig = {
    apiKey: string;
    endpoint: string;
    name: string;
    pageSize?: number | undefined;
    pollingPeriod?: string | undefined;
    provider?: string | undefined;
    webhookSharedSecret: string;
};

/** @internal */
export const V3IncreaseConfig$inboundSchema: z.ZodType<V3IncreaseConfig, z.ZodTypeDef, unknown> =
    z.object({
        apiKey: z.string(),
        endpoint: z.string(),
        name: z.string(),
        pageSize: z.number().int().default(25),
        pollingPeriod: z.string().optional(),
        provider: z.string().default("Increase"),
        webhookSharedSecret: z.string(),
    });

/** @internal */
export type V3IncreaseConfig$Outbound = {
    apiKey: string;
    endpoint: string;
    name: string;
    pageSize: number;
    pollingPeriod?: string | undefined;
    provider: string;
    webhookSharedSecret: string;
};

/** @internal */
export const V3IncreaseConfig$outboundSchema: z.ZodType<
    V3IncreaseConfig$Outbound,
    z.ZodTypeDef,
    V3IncreaseConfig
> = z.object({
    apiKey: z.string(),
    endpoint: z.string(),
    name: z.string(),
    pageSize: z.number().int().default(25),
    pollingPeriod: z.string().optional(),
    provider: z.string().default("Increase"),
    webhookSharedSecret: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3IncreaseConfig$ {
    /** @deprecated use `V3IncreaseConfig$inboundSchema` instead. */
    export const inboundSchema = V3IncreaseConfig$inboundSchema;
    /** @deprecated use `V3IncreaseConfig$outboundSchema` instead. */
    export const outboundSchema = V3IncreaseConfig$outboundSchema;
    /** @deprecated use `V3IncreaseConfig$Outbound` instead. */
    export type Outbound = V3IncreaseConfig$Outbound;
}
