/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type V3UpdatePaymentMetadataRequest = {
    metadata: { [k: string]: string } | null;
};

/** @internal */
export const V3UpdatePaymentMetadataRequest$inboundSchema: z.ZodType<
    V3UpdatePaymentMetadataRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    metadata: z.nullable(z.record(z.string())),
});

/** @internal */
export type V3UpdatePaymentMetadataRequest$Outbound = {
    metadata: { [k: string]: string } | null;
};

/** @internal */
export const V3UpdatePaymentMetadataRequest$outboundSchema: z.ZodType<
    V3UpdatePaymentMetadataRequest$Outbound,
    z.ZodTypeDef,
    V3UpdatePaymentMetadataRequest
> = z.object({
    metadata: z.nullable(z.record(z.string())),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3UpdatePaymentMetadataRequest$ {
    /** @deprecated use `V3UpdatePaymentMetadataRequest$inboundSchema` instead. */
    export const inboundSchema = V3UpdatePaymentMetadataRequest$inboundSchema;
    /** @deprecated use `V3UpdatePaymentMetadataRequest$outboundSchema` instead. */
    export const outboundSchema = V3UpdatePaymentMetadataRequest$outboundSchema;
    /** @deprecated use `V3UpdatePaymentMetadataRequest$Outbound` instead. */
    export type Outbound = V3UpdatePaymentMetadataRequest$Outbound;
}
