/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    BalanceWithAssets,
    BalanceWithAssets$inboundSchema,
    BalanceWithAssets$Outbound,
    BalanceWithAssets$outboundSchema,
} from "./balancewithassets.js";
import * as z from "zod";

export type WalletSummary = {
    balances: Array<BalanceWithAssets>;
    availableFunds: { [k: string]: bigint };
    expiredFunds: { [k: string]: bigint };
    expirableFunds: { [k: string]: bigint };
    holdFunds: { [k: string]: bigint };
};

/** @internal */
export const WalletSummary$inboundSchema: z.ZodType<WalletSummary, z.ZodTypeDef, unknown> =
    z.object({
        balances: z.array(BalanceWithAssets$inboundSchema),
        availableFunds: z.record(z.number().transform((v) => BigInt(v))),
        expiredFunds: z.record(z.number().transform((v) => BigInt(v))),
        expirableFunds: z.record(z.number().transform((v) => BigInt(v))),
        holdFunds: z.record(z.number().transform((v) => BigInt(v))),
    });

/** @internal */
export type WalletSummary$Outbound = {
    balances: Array<BalanceWithAssets$Outbound>;
    availableFunds: { [k: string]: number };
    expiredFunds: { [k: string]: number };
    expirableFunds: { [k: string]: number };
    holdFunds: { [k: string]: number };
};

/** @internal */
export const WalletSummary$outboundSchema: z.ZodType<
    WalletSummary$Outbound,
    z.ZodTypeDef,
    WalletSummary
> = z.object({
    balances: z.array(BalanceWithAssets$outboundSchema),
    availableFunds: z.record(z.bigint().transform((v) => Number(v))),
    expiredFunds: z.record(z.bigint().transform((v) => Number(v))),
    expirableFunds: z.record(z.bigint().transform((v) => Number(v))),
    holdFunds: z.record(z.bigint().transform((v) => Number(v))),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WalletSummary$ {
    /** @deprecated use `WalletSummary$inboundSchema` instead. */
    export const inboundSchema = WalletSummary$inboundSchema;
    /** @deprecated use `WalletSummary$outboundSchema` instead. */
    export const outboundSchema = WalletSummary$outboundSchema;
    /** @deprecated use `WalletSummary$Outbound` instead. */
    export type Outbound = WalletSummary$Outbound;
}
