/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types/enums.js";
import * as z from "zod";

export const ErrorCode = {
    Validation: "VALIDATION",
    InternalError: "INTERNAL_ERROR",
    InsufficientFund: "INSUFFICIENT_FUND",
    HoldClosed: "HOLD_CLOSED",
} as const;
export type ErrorCode = ClosedEnum<typeof ErrorCode>;

export type WalletsErrorResponse = {
    errorCode: ErrorCode;
    errorMessage: string;
};

/** @internal */
export const ErrorCode$inboundSchema: z.ZodNativeEnum<typeof ErrorCode> = z.nativeEnum(ErrorCode);

/** @internal */
export const ErrorCode$outboundSchema: z.ZodNativeEnum<typeof ErrorCode> = ErrorCode$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ErrorCode$ {
    /** @deprecated use `ErrorCode$inboundSchema` instead. */
    export const inboundSchema = ErrorCode$inboundSchema;
    /** @deprecated use `ErrorCode$outboundSchema` instead. */
    export const outboundSchema = ErrorCode$outboundSchema;
}

/** @internal */
export const WalletsErrorResponse$inboundSchema: z.ZodType<
    WalletsErrorResponse,
    z.ZodTypeDef,
    unknown
> = z.object({
    errorCode: ErrorCode$inboundSchema,
    errorMessage: z.string(),
});

/** @internal */
export type WalletsErrorResponse$Outbound = {
    errorCode: string;
    errorMessage: string;
};

/** @internal */
export const WalletsErrorResponse$outboundSchema: z.ZodType<
    WalletsErrorResponse$Outbound,
    z.ZodTypeDef,
    WalletsErrorResponse
> = z.object({
    errorCode: ErrorCode$outboundSchema,
    errorMessage: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WalletsErrorResponse$ {
    /** @deprecated use `WalletsErrorResponse$inboundSchema` instead. */
    export const inboundSchema = WalletsErrorResponse$inboundSchema;
    /** @deprecated use `WalletsErrorResponse$outboundSchema` instead. */
    export const outboundSchema = WalletsErrorResponse$outboundSchema;
    /** @deprecated use `WalletsErrorResponse$Outbound` instead. */
    export type Outbound = WalletsErrorResponse$Outbound;
}
