/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type WebhooksConfig = {
    id: string;
    endpoint: string;
    secret: string;
    eventTypes: Array<string>;
    active: boolean;
    createdAt: Date;
    updatedAt: Date;
};

/** @internal */
export const WebhooksConfig$inboundSchema: z.ZodType<WebhooksConfig, z.ZodTypeDef, unknown> =
    z.object({
        id: z.string(),
        endpoint: z.string(),
        secret: z.string(),
        eventTypes: z.array(z.string()),
        active: z.boolean(),
        createdAt: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v)),
        updatedAt: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v)),
    });

/** @internal */
export type WebhooksConfig$Outbound = {
    id: string;
    endpoint: string;
    secret: string;
    eventTypes: Array<string>;
    active: boolean;
    createdAt: string;
    updatedAt: string;
};

/** @internal */
export const WebhooksConfig$outboundSchema: z.ZodType<
    WebhooksConfig$Outbound,
    z.ZodTypeDef,
    WebhooksConfig
> = z.object({
    id: z.string(),
    endpoint: z.string(),
    secret: z.string(),
    eventTypes: z.array(z.string()),
    active: z.boolean(),
    createdAt: z.date().transform((v) => v.toISOString()),
    updatedAt: z.date().transform((v) => v.toISOString()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WebhooksConfig$ {
    /** @deprecated use `WebhooksConfig$inboundSchema` instead. */
    export const inboundSchema = WebhooksConfig$inboundSchema;
    /** @deprecated use `WebhooksConfig$outboundSchema` instead. */
    export const outboundSchema = WebhooksConfig$outboundSchema;
    /** @deprecated use `WebhooksConfig$Outbound` instead. */
    export type Outbound = WebhooksConfig$Outbound;
}
