/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    StageStatus,
    StageStatus$inboundSchema,
    StageStatus$Outbound,
    StageStatus$outboundSchema,
} from "./stagestatus.js";
import {
    Workflow,
    Workflow$inboundSchema,
    Workflow$Outbound,
    Workflow$outboundSchema,
} from "./workflow.js";
import * as z from "zod";

export type WorkflowInstance = {
    workflowID: string;
    id: string;
    createdAt: Date;
    updatedAt: Date;
    status?: Array<StageStatus> | undefined;
    terminated: boolean;
    terminatedAt?: Date | undefined;
    error?: string | undefined;
    workflow?: Workflow | undefined;
};

/** @internal */
export const WorkflowInstance$inboundSchema: z.ZodType<WorkflowInstance, z.ZodTypeDef, unknown> =
    z.object({
        workflowID: z.string(),
        id: z.string(),
        createdAt: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v)),
        updatedAt: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v)),
        status: z.array(StageStatus$inboundSchema).optional(),
        terminated: z.boolean(),
        terminatedAt: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v))
            .optional(),
        error: z.string().optional(),
        workflow: Workflow$inboundSchema.optional(),
    });

/** @internal */
export type WorkflowInstance$Outbound = {
    workflowID: string;
    id: string;
    createdAt: string;
    updatedAt: string;
    status?: Array<StageStatus$Outbound> | undefined;
    terminated: boolean;
    terminatedAt?: string | undefined;
    error?: string | undefined;
    workflow?: Workflow$Outbound | undefined;
};

/** @internal */
export const WorkflowInstance$outboundSchema: z.ZodType<
    WorkflowInstance$Outbound,
    z.ZodTypeDef,
    WorkflowInstance
> = z.object({
    workflowID: z.string(),
    id: z.string(),
    createdAt: z.date().transform((v) => v.toISOString()),
    updatedAt: z.date().transform((v) => v.toISOString()),
    status: z.array(StageStatus$outboundSchema).optional(),
    terminated: z.boolean(),
    terminatedAt: z
        .date()
        .transform((v) => v.toISOString())
        .optional(),
    error: z.string().optional(),
    workflow: Workflow$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WorkflowInstance$ {
    /** @deprecated use `WorkflowInstance$inboundSchema` instead. */
    export const inboundSchema = WorkflowInstance$inboundSchema;
    /** @deprecated use `WorkflowInstance$outboundSchema` instead. */
    export const outboundSchema = WorkflowInstance$outboundSchema;
    /** @deprecated use `WorkflowInstance$Outbound` instead. */
    export type Outbound = WorkflowInstance$Outbound;
}
