/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import {
    ActivityCreateTransactionOutput,
    ActivityCreateTransactionOutput$inboundSchema,
    ActivityCreateTransactionOutput$Outbound,
    ActivityCreateTransactionOutput$outboundSchema,
} from "./activitycreatetransactionoutput.js";
import {
    ActivityDebitWalletOutput,
    ActivityDebitWalletOutput$inboundSchema,
    ActivityDebitWalletOutput$Outbound,
    ActivityDebitWalletOutput$outboundSchema,
} from "./activitydebitwalletoutput.js";
import {
    ActivityGetAccountOutput,
    ActivityGetAccountOutput$inboundSchema,
    ActivityGetAccountOutput$Outbound,
    ActivityGetAccountOutput$outboundSchema,
} from "./activitygetaccountoutput.js";
import {
    ActivityGetPaymentOutput,
    ActivityGetPaymentOutput$inboundSchema,
    ActivityGetPaymentOutput$Outbound,
    ActivityGetPaymentOutput$outboundSchema,
} from "./activitygetpaymentoutput.js";
import {
    ActivityGetWalletOutput,
    ActivityGetWalletOutput$inboundSchema,
    ActivityGetWalletOutput$Outbound,
    ActivityGetWalletOutput$outboundSchema,
} from "./activitygetwalletoutput.js";
import {
    ActivityRevertTransactionOutput,
    ActivityRevertTransactionOutput$inboundSchema,
    ActivityRevertTransactionOutput$Outbound,
    ActivityRevertTransactionOutput$outboundSchema,
} from "./activityreverttransactionoutput.js";
import {
    FlowsListWalletsResponse,
    FlowsListWalletsResponse$inboundSchema,
    FlowsListWalletsResponse$Outbound,
    FlowsListWalletsResponse$outboundSchema,
} from "./flowslistwalletsresponse.js";
import * as z from "zod";

export type WorkflowInstanceHistoryStageOutput = {
    getAccount?: ActivityGetAccountOutput | undefined;
    createTransaction?: ActivityCreateTransactionOutput | undefined;
    revertTransaction?: ActivityRevertTransactionOutput | undefined;
    getPayment?: ActivityGetPaymentOutput | undefined;
    debitWallet?: ActivityDebitWalletOutput | undefined;
    getWallet?: ActivityGetWalletOutput | undefined;
    listWallets?: FlowsListWalletsResponse | undefined;
};

/** @internal */
export const WorkflowInstanceHistoryStageOutput$inboundSchema: z.ZodType<
    WorkflowInstanceHistoryStageOutput,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        GetAccount: ActivityGetAccountOutput$inboundSchema.optional(),
        CreateTransaction: ActivityCreateTransactionOutput$inboundSchema.optional(),
        RevertTransaction: ActivityRevertTransactionOutput$inboundSchema.optional(),
        GetPayment: ActivityGetPaymentOutput$inboundSchema.optional(),
        DebitWallet: ActivityDebitWalletOutput$inboundSchema.optional(),
        GetWallet: ActivityGetWalletOutput$inboundSchema.optional(),
        ListWallets: FlowsListWalletsResponse$inboundSchema.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            GetAccount: "getAccount",
            CreateTransaction: "createTransaction",
            RevertTransaction: "revertTransaction",
            GetPayment: "getPayment",
            DebitWallet: "debitWallet",
            GetWallet: "getWallet",
            ListWallets: "listWallets",
        });
    });

/** @internal */
export type WorkflowInstanceHistoryStageOutput$Outbound = {
    GetAccount?: ActivityGetAccountOutput$Outbound | undefined;
    CreateTransaction?: ActivityCreateTransactionOutput$Outbound | undefined;
    RevertTransaction?: ActivityRevertTransactionOutput$Outbound | undefined;
    GetPayment?: ActivityGetPaymentOutput$Outbound | undefined;
    DebitWallet?: ActivityDebitWalletOutput$Outbound | undefined;
    GetWallet?: ActivityGetWalletOutput$Outbound | undefined;
    ListWallets?: FlowsListWalletsResponse$Outbound | undefined;
};

/** @internal */
export const WorkflowInstanceHistoryStageOutput$outboundSchema: z.ZodType<
    WorkflowInstanceHistoryStageOutput$Outbound,
    z.ZodTypeDef,
    WorkflowInstanceHistoryStageOutput
> = z
    .object({
        getAccount: ActivityGetAccountOutput$outboundSchema.optional(),
        createTransaction: ActivityCreateTransactionOutput$outboundSchema.optional(),
        revertTransaction: ActivityRevertTransactionOutput$outboundSchema.optional(),
        getPayment: ActivityGetPaymentOutput$outboundSchema.optional(),
        debitWallet: ActivityDebitWalletOutput$outboundSchema.optional(),
        getWallet: ActivityGetWalletOutput$outboundSchema.optional(),
        listWallets: FlowsListWalletsResponse$outboundSchema.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            getAccount: "GetAccount",
            createTransaction: "CreateTransaction",
            revertTransaction: "RevertTransaction",
            getPayment: "GetPayment",
            debitWallet: "DebitWallet",
            getWallet: "GetWallet",
            listWallets: "ListWallets",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WorkflowInstanceHistoryStageOutput$ {
    /** @deprecated use `WorkflowInstanceHistoryStageOutput$inboundSchema` instead. */
    export const inboundSchema = WorkflowInstanceHistoryStageOutput$inboundSchema;
    /** @deprecated use `WorkflowInstanceHistoryStageOutput$outboundSchema` instead. */
    export const outboundSchema = WorkflowInstanceHistoryStageOutput$outboundSchema;
    /** @deprecated use `WorkflowInstanceHistoryStageOutput$Outbound` instead. */
    export type Outbound = WorkflowInstanceHistoryStageOutput$Outbound;
}
