/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type AddMetadataToAccountRequest = {
    /**
     * Name of the ledger.
     */
    ledger: string;
    /**
     * Exact address of the account. It must match the following regular expressions pattern:
     *
     * @remarks
     * ```
     * ^\w+(:\w+)*$
     * ```
     *
     */
    address: string;
    /**
     * metadata
     */
    requestBody: { [k: string]: any } | null;
};

/** @internal */
export const AddMetadataToAccountRequest$inboundSchema: z.ZodType<
    AddMetadataToAccountRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        ledger: z.string(),
        address: z.string(),
        RequestBody: z.nullable(z.record(z.any())),
    })
    .transform((v) => {
        return remap$(v, {
            RequestBody: "requestBody",
        });
    });

/** @internal */
export type AddMetadataToAccountRequest$Outbound = {
    ledger: string;
    address: string;
    RequestBody: { [k: string]: any } | null;
};

/** @internal */
export const AddMetadataToAccountRequest$outboundSchema: z.ZodType<
    AddMetadataToAccountRequest$Outbound,
    z.ZodTypeDef,
    AddMetadataToAccountRequest
> = z
    .object({
        ledger: z.string(),
        address: z.string(),
        requestBody: z.nullable(z.record(z.any())),
    })
    .transform((v) => {
        return remap$(v, {
            requestBody: "RequestBody",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AddMetadataToAccountRequest$ {
    /** @deprecated use `AddMetadataToAccountRequest$inboundSchema` instead. */
    export const inboundSchema = AddMetadataToAccountRequest$inboundSchema;
    /** @deprecated use `AddMetadataToAccountRequest$outboundSchema` instead. */
    export const outboundSchema = AddMetadataToAccountRequest$outboundSchema;
    /** @deprecated use `AddMetadataToAccountRequest$Outbound` instead. */
    export type Outbound = AddMetadataToAccountRequest$Outbound;
}
