/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type CreateBalanceRequest = {
    id: string;
    /**
     * Use an idempotency key
     */
    idempotencyKey?: string | undefined;
    createBalanceRequest?: components.CreateBalanceRequest | undefined;
};

export type CreateBalanceResponse =
    | components.CreateBalanceResponse
    | components.WalletsErrorResponse;

/** @internal */
export const CreateBalanceRequest$inboundSchema: z.ZodType<
    CreateBalanceRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        id: z.string(),
        "Idempotency-Key": z.string().optional(),
        CreateBalanceRequest: components.CreateBalanceRequest$inboundSchema.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            "Idempotency-Key": "idempotencyKey",
            CreateBalanceRequest: "createBalanceRequest",
        });
    });

/** @internal */
export type CreateBalanceRequest$Outbound = {
    id: string;
    "Idempotency-Key"?: string | undefined;
    CreateBalanceRequest?: components.CreateBalanceRequest$Outbound | undefined;
};

/** @internal */
export const CreateBalanceRequest$outboundSchema: z.ZodType<
    CreateBalanceRequest$Outbound,
    z.ZodTypeDef,
    CreateBalanceRequest
> = z
    .object({
        id: z.string(),
        idempotencyKey: z.string().optional(),
        createBalanceRequest: components.CreateBalanceRequest$outboundSchema.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            idempotencyKey: "Idempotency-Key",
            createBalanceRequest: "CreateBalanceRequest",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateBalanceRequest$ {
    /** @deprecated use `CreateBalanceRequest$inboundSchema` instead. */
    export const inboundSchema = CreateBalanceRequest$inboundSchema;
    /** @deprecated use `CreateBalanceRequest$outboundSchema` instead. */
    export const outboundSchema = CreateBalanceRequest$outboundSchema;
    /** @deprecated use `CreateBalanceRequest$Outbound` instead. */
    export type Outbound = CreateBalanceRequest$Outbound;
}

/** @internal */
export const CreateBalanceResponse$inboundSchema: z.ZodType<
    CreateBalanceResponse,
    z.ZodTypeDef,
    unknown
> = z.union([
    components.CreateBalanceResponse$inboundSchema,
    components.WalletsErrorResponse$inboundSchema,
]);

/** @internal */
export type CreateBalanceResponse$Outbound =
    | components.CreateBalanceResponse$Outbound
    | components.WalletsErrorResponse$Outbound;

/** @internal */
export const CreateBalanceResponse$outboundSchema: z.ZodType<
    CreateBalanceResponse$Outbound,
    z.ZodTypeDef,
    CreateBalanceResponse
> = z.union([
    components.CreateBalanceResponse$outboundSchema,
    components.WalletsErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateBalanceResponse$ {
    /** @deprecated use `CreateBalanceResponse$inboundSchema` instead. */
    export const inboundSchema = CreateBalanceResponse$inboundSchema;
    /** @deprecated use `CreateBalanceResponse$outboundSchema` instead. */
    export const outboundSchema = CreateBalanceResponse$outboundSchema;
    /** @deprecated use `CreateBalanceResponse$Outbound` instead. */
    export type Outbound = CreateBalanceResponse$Outbound;
}
