/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as errors from "../errors/index.js";
import * as z from "zod";

export type GetBalancesAggregatedRequest = {
    /**
     * Name of the ledger.
     */
    ledger: string;
    /**
     * Filter balances involving given account, either as source or destination.
     */
    address?: string | undefined;
    /**
     * Use insertion date instead of effective date
     */
    useInsertionDate?: boolean | undefined;
};

export type GetBalancesAggregatedResponse =
    | components.AggregateBalancesResponse
    | errors.ErrorResponse;

/** @internal */
export const GetBalancesAggregatedRequest$inboundSchema: z.ZodType<
    GetBalancesAggregatedRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    ledger: z.string(),
    address: z.string().optional(),
    useInsertionDate: z.boolean().optional(),
});

/** @internal */
export type GetBalancesAggregatedRequest$Outbound = {
    ledger: string;
    address?: string | undefined;
    useInsertionDate?: boolean | undefined;
};

/** @internal */
export const GetBalancesAggregatedRequest$outboundSchema: z.ZodType<
    GetBalancesAggregatedRequest$Outbound,
    z.ZodTypeDef,
    GetBalancesAggregatedRequest
> = z.object({
    ledger: z.string(),
    address: z.string().optional(),
    useInsertionDate: z.boolean().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetBalancesAggregatedRequest$ {
    /** @deprecated use `GetBalancesAggregatedRequest$inboundSchema` instead. */
    export const inboundSchema = GetBalancesAggregatedRequest$inboundSchema;
    /** @deprecated use `GetBalancesAggregatedRequest$outboundSchema` instead. */
    export const outboundSchema = GetBalancesAggregatedRequest$outboundSchema;
    /** @deprecated use `GetBalancesAggregatedRequest$Outbound` instead. */
    export type Outbound = GetBalancesAggregatedRequest$Outbound;
}

/** @internal */
export const GetBalancesAggregatedResponse$inboundSchema: z.ZodType<
    GetBalancesAggregatedResponse,
    z.ZodTypeDef,
    unknown
> = z.union([
    components.AggregateBalancesResponse$inboundSchema,
    errors.ErrorResponse$inboundSchema,
]);

/** @internal */
export type GetBalancesAggregatedResponse$Outbound =
    | components.AggregateBalancesResponse$Outbound
    | errors.ErrorResponse$Outbound;

/** @internal */
export const GetBalancesAggregatedResponse$outboundSchema: z.ZodType<
    GetBalancesAggregatedResponse$Outbound,
    z.ZodTypeDef,
    GetBalancesAggregatedResponse
> = z.union([
    components.AggregateBalancesResponse$outboundSchema,
    errors.ErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetBalancesAggregatedResponse$ {
    /** @deprecated use `GetBalancesAggregatedResponse$inboundSchema` instead. */
    export const inboundSchema = GetBalancesAggregatedResponse$inboundSchema;
    /** @deprecated use `GetBalancesAggregatedResponse$outboundSchema` instead. */
    export const outboundSchema = GetBalancesAggregatedResponse$outboundSchema;
    /** @deprecated use `GetBalancesAggregatedResponse$Outbound` instead. */
    export type Outbound = GetBalancesAggregatedResponse$Outbound;
}
