/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export type ListPoliciesRequest = {
    /**
     * The maximum number of results to return per page.
     *
     * @remarks
     *
     */
    pageSize?: number | undefined;
    /**
     * Parameter used in pagination requests. Maximum page size is set to 15.
     *
     * @remarks
     * Set to the value of next for the next page of results.
     * Set to the value of previous for the previous page of results.
     * No other parameters can be set when this parameter is set.
     *
     */
    cursor?: string | undefined;
    query?: { [k: string]: any } | undefined;
};

export type ListPoliciesResponse =
    | components.PoliciesCursorResponse
    | components.ReconciliationErrorResponse;

/** @internal */
export const ListPoliciesRequest$inboundSchema: z.ZodType<
    ListPoliciesRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    pageSize: z.number().int().optional(),
    cursor: z.string().optional(),
    query: z.record(z.any()).optional(),
});

/** @internal */
export type ListPoliciesRequest$Outbound = {
    pageSize?: number | undefined;
    cursor?: string | undefined;
    query?: { [k: string]: any } | undefined;
};

/** @internal */
export const ListPoliciesRequest$outboundSchema: z.ZodType<
    ListPoliciesRequest$Outbound,
    z.ZodTypeDef,
    ListPoliciesRequest
> = z.object({
    pageSize: z.number().int().optional(),
    cursor: z.string().optional(),
    query: z.record(z.any()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListPoliciesRequest$ {
    /** @deprecated use `ListPoliciesRequest$inboundSchema` instead. */
    export const inboundSchema = ListPoliciesRequest$inboundSchema;
    /** @deprecated use `ListPoliciesRequest$outboundSchema` instead. */
    export const outboundSchema = ListPoliciesRequest$outboundSchema;
    /** @deprecated use `ListPoliciesRequest$Outbound` instead. */
    export type Outbound = ListPoliciesRequest$Outbound;
}

/** @internal */
export const ListPoliciesResponse$inboundSchema: z.ZodType<
    ListPoliciesResponse,
    z.ZodTypeDef,
    unknown
> = z.union([
    components.PoliciesCursorResponse$inboundSchema,
    components.ReconciliationErrorResponse$inboundSchema,
]);

/** @internal */
export type ListPoliciesResponse$Outbound =
    | components.PoliciesCursorResponse$Outbound
    | components.ReconciliationErrorResponse$Outbound;

/** @internal */
export const ListPoliciesResponse$outboundSchema: z.ZodType<
    ListPoliciesResponse$Outbound,
    z.ZodTypeDef,
    ListPoliciesResponse
> = z.union([
    components.PoliciesCursorResponse$outboundSchema,
    components.ReconciliationErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListPoliciesResponse$ {
    /** @deprecated use `ListPoliciesResponse$inboundSchema` instead. */
    export const inboundSchema = ListPoliciesResponse$inboundSchema;
    /** @deprecated use `ListPoliciesResponse$outboundSchema` instead. */
    export const outboundSchema = ListPoliciesResponse$outboundSchema;
    /** @deprecated use `ListPoliciesResponse$Outbound` instead. */
    export type Outbound = ListPoliciesResponse$Outbound;
}
