/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export type ListAllConnectorsResponse =
    | components.ConnectorsResponse
    | components.PaymentsErrorResponse;

/** @internal */
export const ListAllConnectorsResponse$inboundSchema: z.ZodType<
    ListAllConnectorsResponse,
    z.ZodTypeDef,
    unknown
> = z.union([
    components.ConnectorsResponse$inboundSchema,
    components.PaymentsErrorResponse$inboundSchema,
]);

/** @internal */
export type ListAllConnectorsResponse$Outbound =
    | components.ConnectorsResponse$Outbound
    | components.PaymentsErrorResponse$Outbound;

/** @internal */
export const ListAllConnectorsResponse$outboundSchema: z.ZodType<
    ListAllConnectorsResponse$Outbound,
    z.ZodTypeDef,
    ListAllConnectorsResponse
> = z.union([
    components.ConnectorsResponse$outboundSchema,
    components.PaymentsErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListAllConnectorsResponse$ {
    /** @deprecated use `ListAllConnectorsResponse$inboundSchema` instead. */
    export const inboundSchema = ListAllConnectorsResponse$inboundSchema;
    /** @deprecated use `ListAllConnectorsResponse$outboundSchema` instead. */
    export const outboundSchema = ListAllConnectorsResponse$outboundSchema;
    /** @deprecated use `ListAllConnectorsResponse$Outbound` instead. */
    export type Outbound = ListAllConnectorsResponse$Outbound;
}
