/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ReadUserRequest = {
    /**
     * User ID
     */
    userId: string;
};

/** @internal */
export const ReadUserRequest$inboundSchema: z.ZodType<ReadUserRequest, z.ZodTypeDef, unknown> =
    z.object({
        userId: z.string(),
    });

/** @internal */
export type ReadUserRequest$Outbound = {
    userId: string;
};

/** @internal */
export const ReadUserRequest$outboundSchema: z.ZodType<
    ReadUserRequest$Outbound,
    z.ZodTypeDef,
    ReadUserRequest
> = z.object({
    userId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ReadUserRequest$ {
    /** @deprecated use `ReadUserRequest$inboundSchema` instead. */
    export const inboundSchema = ReadUserRequest$inboundSchema;
    /** @deprecated use `ReadUserRequest$outboundSchema` instead. */
    export const outboundSchema = ReadUserRequest$outboundSchema;
    /** @deprecated use `ReadUserRequest$Outbound` instead. */
    export type Outbound = ReadUserRequest$Outbound;
}
