/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export type ReadConnectorConfigRequest = {
    /**
     * The name of the connector.
     */
    connector: components.Connector;
};

export type ReadConnectorConfigResponse =
    | components.ConnectorConfigResponse
    | components.PaymentsErrorResponse;

/** @internal */
export const ReadConnectorConfigRequest$inboundSchema: z.ZodType<
    ReadConnectorConfigRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    connector: components.Connector$inboundSchema,
});

/** @internal */
export type ReadConnectorConfigRequest$Outbound = {
    connector: string;
};

/** @internal */
export const ReadConnectorConfigRequest$outboundSchema: z.ZodType<
    ReadConnectorConfigRequest$Outbound,
    z.ZodTypeDef,
    ReadConnectorConfigRequest
> = z.object({
    connector: components.Connector$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ReadConnectorConfigRequest$ {
    /** @deprecated use `ReadConnectorConfigRequest$inboundSchema` instead. */
    export const inboundSchema = ReadConnectorConfigRequest$inboundSchema;
    /** @deprecated use `ReadConnectorConfigRequest$outboundSchema` instead. */
    export const outboundSchema = ReadConnectorConfigRequest$outboundSchema;
    /** @deprecated use `ReadConnectorConfigRequest$Outbound` instead. */
    export type Outbound = ReadConnectorConfigRequest$Outbound;
}

/** @internal */
export const ReadConnectorConfigResponse$inboundSchema: z.ZodType<
    ReadConnectorConfigResponse,
    z.ZodTypeDef,
    unknown
> = z.union([
    components.ConnectorConfigResponse$inboundSchema,
    components.PaymentsErrorResponse$inboundSchema,
]);

/** @internal */
export type ReadConnectorConfigResponse$Outbound =
    | components.ConnectorConfigResponse$Outbound
    | components.PaymentsErrorResponse$Outbound;

/** @internal */
export const ReadConnectorConfigResponse$outboundSchema: z.ZodType<
    ReadConnectorConfigResponse$Outbound,
    z.ZodTypeDef,
    ReadConnectorConfigResponse
> = z.union([
    components.ConnectorConfigResponse$outboundSchema,
    components.PaymentsErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ReadConnectorConfigResponse$ {
    /** @deprecated use `ReadConnectorConfigResponse$inboundSchema` instead. */
    export const inboundSchema = ReadConnectorConfigResponse$inboundSchema;
    /** @deprecated use `ReadConnectorConfigResponse$outboundSchema` instead. */
    export const outboundSchema = ReadConnectorConfigResponse$outboundSchema;
    /** @deprecated use `ReadConnectorConfigResponse$Outbound` instead. */
    export type Outbound = ReadConnectorConfigResponse$Outbound;
}
