/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type V2AddMetadataToAccountRequest = {
    /**
     * Name of the ledger.
     */
    ledger: string;
    /**
     * Exact address of the account. It must match the following regular expressions pattern:
     *
     * @remarks
     * ```
     * ^\w+(:\w+)*$
     * ```
     *
     */
    address: string;
    /**
     * Set the dry run mode. Dry run mode doesn't add the logs to the database or publish a message to the message broker.
     */
    dryRun?: boolean | undefined;
    /**
     * Use an idempotency key
     */
    idempotencyKey?: string | undefined;
    /**
     * metadata
     */
    requestBody: { [k: string]: string };
};

/** @internal */
export const V2AddMetadataToAccountRequest$inboundSchema: z.ZodType<
    V2AddMetadataToAccountRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        ledger: z.string(),
        address: z.string(),
        dryRun: z.boolean().optional(),
        "Idempotency-Key": z.string().optional(),
        RequestBody: z.record(z.string()),
    })
    .transform((v) => {
        return remap$(v, {
            "Idempotency-Key": "idempotencyKey",
            RequestBody: "requestBody",
        });
    });

/** @internal */
export type V2AddMetadataToAccountRequest$Outbound = {
    ledger: string;
    address: string;
    dryRun?: boolean | undefined;
    "Idempotency-Key"?: string | undefined;
    RequestBody: { [k: string]: string };
};

/** @internal */
export const V2AddMetadataToAccountRequest$outboundSchema: z.ZodType<
    V2AddMetadataToAccountRequest$Outbound,
    z.ZodTypeDef,
    V2AddMetadataToAccountRequest
> = z
    .object({
        ledger: z.string(),
        address: z.string(),
        dryRun: z.boolean().optional(),
        idempotencyKey: z.string().optional(),
        requestBody: z.record(z.string()),
    })
    .transform((v) => {
        return remap$(v, {
            idempotencyKey: "Idempotency-Key",
            requestBody: "RequestBody",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2AddMetadataToAccountRequest$ {
    /** @deprecated use `V2AddMetadataToAccountRequest$inboundSchema` instead. */
    export const inboundSchema = V2AddMetadataToAccountRequest$inboundSchema;
    /** @deprecated use `V2AddMetadataToAccountRequest$outboundSchema` instead. */
    export const outboundSchema = V2AddMetadataToAccountRequest$outboundSchema;
    /** @deprecated use `V2AddMetadataToAccountRequest$Outbound` instead. */
    export type Outbound = V2AddMetadataToAccountRequest$Outbound;
}
