/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as errors from "../errors/index.js";
import * as z from "zod";

export type V2CreateTransactionRequest = {
    /**
     * Name of the ledger.
     */
    ledger: string;
    /**
     * Set the dryRun mode. dry run mode doesn't add the logs to the database or publish a message to the message broker.
     */
    dryRun?: boolean | undefined;
    /**
     * Use an idempotency key
     */
    idempotencyKey?: string | undefined;
    /**
     * Disable balance checks when passing postings
     *
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    force?: boolean | undefined;
    /**
     * The request body must contain at least one of the following objects:
     *
     * @remarks
     *   - `postings`: suitable for simple transactions
     *   - `script`: enabling more complex transactions with Numscript
     *
     */
    v2PostTransaction: components.V2PostTransaction;
};

export type V2CreateTransactionResponse =
    | components.V2CreateTransactionResponse
    | errors.V2ErrorResponse;

/** @internal */
export const V2CreateTransactionRequest$inboundSchema: z.ZodType<
    V2CreateTransactionRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        ledger: z.string(),
        dryRun: z.boolean().optional(),
        "Idempotency-Key": z.string().optional(),
        force: z.boolean().optional(),
        V2PostTransaction: components.V2PostTransaction$inboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            "Idempotency-Key": "idempotencyKey",
            V2PostTransaction: "v2PostTransaction",
        });
    });

/** @internal */
export type V2CreateTransactionRequest$Outbound = {
    ledger: string;
    dryRun?: boolean | undefined;
    "Idempotency-Key"?: string | undefined;
    force?: boolean | undefined;
    V2PostTransaction: components.V2PostTransaction$Outbound;
};

/** @internal */
export const V2CreateTransactionRequest$outboundSchema: z.ZodType<
    V2CreateTransactionRequest$Outbound,
    z.ZodTypeDef,
    V2CreateTransactionRequest
> = z
    .object({
        ledger: z.string(),
        dryRun: z.boolean().optional(),
        idempotencyKey: z.string().optional(),
        force: z.boolean().optional(),
        v2PostTransaction: components.V2PostTransaction$outboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            idempotencyKey: "Idempotency-Key",
            v2PostTransaction: "V2PostTransaction",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2CreateTransactionRequest$ {
    /** @deprecated use `V2CreateTransactionRequest$inboundSchema` instead. */
    export const inboundSchema = V2CreateTransactionRequest$inboundSchema;
    /** @deprecated use `V2CreateTransactionRequest$outboundSchema` instead. */
    export const outboundSchema = V2CreateTransactionRequest$outboundSchema;
    /** @deprecated use `V2CreateTransactionRequest$Outbound` instead. */
    export type Outbound = V2CreateTransactionRequest$Outbound;
}

/** @internal */
export const V2CreateTransactionResponse$inboundSchema: z.ZodType<
    V2CreateTransactionResponse,
    z.ZodTypeDef,
    unknown
> = z.union([
    components.V2CreateTransactionResponse$inboundSchema,
    errors.V2ErrorResponse$inboundSchema,
]);

/** @internal */
export type V2CreateTransactionResponse$Outbound =
    | components.V2CreateTransactionResponse$Outbound
    | errors.V2ErrorResponse$Outbound;

/** @internal */
export const V2CreateTransactionResponse$outboundSchema: z.ZodType<
    V2CreateTransactionResponse$Outbound,
    z.ZodTypeDef,
    V2CreateTransactionResponse
> = z.union([
    components.V2CreateTransactionResponse$outboundSchema,
    errors.V2ErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2CreateTransactionResponse$ {
    /** @deprecated use `V2CreateTransactionResponse$inboundSchema` instead. */
    export const inboundSchema = V2CreateTransactionResponse$inboundSchema;
    /** @deprecated use `V2CreateTransactionResponse$outboundSchema` instead. */
    export const outboundSchema = V2CreateTransactionResponse$outboundSchema;
    /** @deprecated use `V2CreateTransactionResponse$Outbound` instead. */
    export type Outbound = V2CreateTransactionResponse$Outbound;
}
