/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as errors from "../errors/index.js";
import * as z from "zod";

export type V2CreateExporterResponse = components.V2CreateExporterResponse | errors.V2ErrorResponse;

/** @internal */
export const V2CreateExporterResponse$inboundSchema: z.ZodType<
    V2CreateExporterResponse,
    z.ZodTypeDef,
    unknown
> = z.union([
    components.V2CreateExporterResponse$inboundSchema,
    errors.V2ErrorResponse$inboundSchema,
]);

/** @internal */
export type V2CreateExporterResponse$Outbound =
    | components.V2CreateExporterResponse$Outbound
    | errors.V2ErrorResponse$Outbound;

/** @internal */
export const V2CreateExporterResponse$outboundSchema: z.ZodType<
    V2CreateExporterResponse$Outbound,
    z.ZodTypeDef,
    V2CreateExporterResponse
> = z.union([
    components.V2CreateExporterResponse$outboundSchema,
    errors.V2ErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2CreateExporterResponse$ {
    /** @deprecated use `V2CreateExporterResponse$inboundSchema` instead. */
    export const inboundSchema = V2CreateExporterResponse$inboundSchema;
    /** @deprecated use `V2CreateExporterResponse$outboundSchema` instead. */
    export const outboundSchema = V2CreateExporterResponse$outboundSchema;
    /** @deprecated use `V2CreateExporterResponse$Outbound` instead. */
    export type Outbound = V2CreateExporterResponse$Outbound;
}
