/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type V2DeleteAccountMetadataRequest = {
    /**
     * Name of the ledger.
     */
    ledger: string;
    /**
     * Account address
     */
    address: string;
    /**
     * The key to remove.
     */
    key: string;
    /**
     * Use an idempotency key
     */
    idempotencyKey?: string | undefined;
};

/** @internal */
export const V2DeleteAccountMetadataRequest$inboundSchema: z.ZodType<
    V2DeleteAccountMetadataRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        ledger: z.string(),
        address: z.string(),
        key: z.string(),
        "Idempotency-Key": z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            "Idempotency-Key": "idempotencyKey",
        });
    });

/** @internal */
export type V2DeleteAccountMetadataRequest$Outbound = {
    ledger: string;
    address: string;
    key: string;
    "Idempotency-Key"?: string | undefined;
};

/** @internal */
export const V2DeleteAccountMetadataRequest$outboundSchema: z.ZodType<
    V2DeleteAccountMetadataRequest$Outbound,
    z.ZodTypeDef,
    V2DeleteAccountMetadataRequest
> = z
    .object({
        ledger: z.string(),
        address: z.string(),
        key: z.string(),
        idempotencyKey: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            idempotencyKey: "Idempotency-Key",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2DeleteAccountMetadataRequest$ {
    /** @deprecated use `V2DeleteAccountMetadataRequest$inboundSchema` instead. */
    export const inboundSchema = V2DeleteAccountMetadataRequest$inboundSchema;
    /** @deprecated use `V2DeleteAccountMetadataRequest$outboundSchema` instead. */
    export const outboundSchema = V2DeleteAccountMetadataRequest$outboundSchema;
    /** @deprecated use `V2DeleteAccountMetadataRequest$Outbound` instead. */
    export type Outbound = V2DeleteAccountMetadataRequest$Outbound;
}
