/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as errors from "../errors/index.js";
import * as z from "zod";

export type V2GetExporterStateRequest = {
    /**
     * The exporter id
     */
    exporterID: string;
};

export type V2GetExporterStateResponse =
    | components.V2GetExporterStateResponse
    | errors.V2ErrorResponse;

/** @internal */
export const V2GetExporterStateRequest$inboundSchema: z.ZodType<
    V2GetExporterStateRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    exporterID: z.string(),
});

/** @internal */
export type V2GetExporterStateRequest$Outbound = {
    exporterID: string;
};

/** @internal */
export const V2GetExporterStateRequest$outboundSchema: z.ZodType<
    V2GetExporterStateRequest$Outbound,
    z.ZodTypeDef,
    V2GetExporterStateRequest
> = z.object({
    exporterID: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2GetExporterStateRequest$ {
    /** @deprecated use `V2GetExporterStateRequest$inboundSchema` instead. */
    export const inboundSchema = V2GetExporterStateRequest$inboundSchema;
    /** @deprecated use `V2GetExporterStateRequest$outboundSchema` instead. */
    export const outboundSchema = V2GetExporterStateRequest$outboundSchema;
    /** @deprecated use `V2GetExporterStateRequest$Outbound` instead. */
    export type Outbound = V2GetExporterStateRequest$Outbound;
}

/** @internal */
export const V2GetExporterStateResponse$inboundSchema: z.ZodType<
    V2GetExporterStateResponse,
    z.ZodTypeDef,
    unknown
> = z.union([
    components.V2GetExporterStateResponse$inboundSchema,
    errors.V2ErrorResponse$inboundSchema,
]);

/** @internal */
export type V2GetExporterStateResponse$Outbound =
    | components.V2GetExporterStateResponse$Outbound
    | errors.V2ErrorResponse$Outbound;

/** @internal */
export const V2GetExporterStateResponse$outboundSchema: z.ZodType<
    V2GetExporterStateResponse$Outbound,
    z.ZodTypeDef,
    V2GetExporterStateResponse
> = z.union([
    components.V2GetExporterStateResponse$outboundSchema,
    errors.V2ErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2GetExporterStateResponse$ {
    /** @deprecated use `V2GetExporterStateResponse$inboundSchema` instead. */
    export const inboundSchema = V2GetExporterStateResponse$inboundSchema;
    /** @deprecated use `V2GetExporterStateResponse$outboundSchema` instead. */
    export const outboundSchema = V2GetExporterStateResponse$outboundSchema;
    /** @deprecated use `V2GetExporterStateResponse$Outbound` instead. */
    export type Outbound = V2GetExporterStateResponse$Outbound;
}
