/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type V3DeletePaymentInitiationRequest = {
    /**
     * The payment initiation ID
     */
    paymentInitiationID: string;
};

/** @internal */
export const V3DeletePaymentInitiationRequest$inboundSchema: z.ZodType<
    V3DeletePaymentInitiationRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    paymentInitiationID: z.string(),
});

/** @internal */
export type V3DeletePaymentInitiationRequest$Outbound = {
    paymentInitiationID: string;
};

/** @internal */
export const V3DeletePaymentInitiationRequest$outboundSchema: z.ZodType<
    V3DeletePaymentInitiationRequest$Outbound,
    z.ZodTypeDef,
    V3DeletePaymentInitiationRequest
> = z.object({
    paymentInitiationID: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3DeletePaymentInitiationRequest$ {
    /** @deprecated use `V3DeletePaymentInitiationRequest$inboundSchema` instead. */
    export const inboundSchema = V3DeletePaymentInitiationRequest$inboundSchema;
    /** @deprecated use `V3DeletePaymentInitiationRequest$outboundSchema` instead. */
    export const outboundSchema = V3DeletePaymentInitiationRequest$outboundSchema;
    /** @deprecated use `V3DeletePaymentInitiationRequest$Outbound` instead. */
    export type Outbound = V3DeletePaymentInitiationRequest$Outbound;
}
