/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export type V3GetBankAccountRequest = {
    /**
     * The bank account ID
     */
    bankAccountID: string;
};

export type V3GetBankAccountResponse =
    | components.V3GetBankAccountResponse
    | components.V3ErrorResponse;

/** @internal */
export const V3GetBankAccountRequest$inboundSchema: z.ZodType<
    V3GetBankAccountRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    bankAccountID: z.string(),
});

/** @internal */
export type V3GetBankAccountRequest$Outbound = {
    bankAccountID: string;
};

/** @internal */
export const V3GetBankAccountRequest$outboundSchema: z.ZodType<
    V3GetBankAccountRequest$Outbound,
    z.ZodTypeDef,
    V3GetBankAccountRequest
> = z.object({
    bankAccountID: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3GetBankAccountRequest$ {
    /** @deprecated use `V3GetBankAccountRequest$inboundSchema` instead. */
    export const inboundSchema = V3GetBankAccountRequest$inboundSchema;
    /** @deprecated use `V3GetBankAccountRequest$outboundSchema` instead. */
    export const outboundSchema = V3GetBankAccountRequest$outboundSchema;
    /** @deprecated use `V3GetBankAccountRequest$Outbound` instead. */
    export type Outbound = V3GetBankAccountRequest$Outbound;
}

/** @internal */
export const V3GetBankAccountResponse$inboundSchema: z.ZodType<
    V3GetBankAccountResponse,
    z.ZodTypeDef,
    unknown
> = z.union([
    components.V3GetBankAccountResponse$inboundSchema,
    components.V3ErrorResponse$inboundSchema,
]);

/** @internal */
export type V3GetBankAccountResponse$Outbound =
    | components.V3GetBankAccountResponse$Outbound
    | components.V3ErrorResponse$Outbound;

/** @internal */
export const V3GetBankAccountResponse$outboundSchema: z.ZodType<
    V3GetBankAccountResponse$Outbound,
    z.ZodTypeDef,
    V3GetBankAccountResponse
> = z.union([
    components.V3GetBankAccountResponse$outboundSchema,
    components.V3ErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3GetBankAccountResponse$ {
    /** @deprecated use `V3GetBankAccountResponse$inboundSchema` instead. */
    export const inboundSchema = V3GetBankAccountResponse$inboundSchema;
    /** @deprecated use `V3GetBankAccountResponse$outboundSchema` instead. */
    export const outboundSchema = V3GetBankAccountResponse$outboundSchema;
    /** @deprecated use `V3GetBankAccountResponse$Outbound` instead. */
    export type Outbound = V3GetBankAccountResponse$Outbound;
}
