/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export type V3ListPaymentInitiationsRequest = {
    /**
     * The number of items to return
     */
    pageSize?: number | undefined;
    /**
     * Parameter used in pagination requests. Set to the value of next for the next page of results. Set to the value of previous for the previous page of results. No other parameters can be set when this parameter is set.
     *
     * @remarks
     *
     */
    cursor?: string | undefined;
    query?: { [k: string]: any } | undefined;
};

export type V3ListPaymentInitiationsResponse =
    | components.V3PaymentInitiationsCursorResponse
    | components.V3ErrorResponse;

/** @internal */
export const V3ListPaymentInitiationsRequest$inboundSchema: z.ZodType<
    V3ListPaymentInitiationsRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    pageSize: z.number().int().optional(),
    cursor: z.string().optional(),
    query: z.record(z.any()).optional(),
});

/** @internal */
export type V3ListPaymentInitiationsRequest$Outbound = {
    pageSize?: number | undefined;
    cursor?: string | undefined;
    query?: { [k: string]: any } | undefined;
};

/** @internal */
export const V3ListPaymentInitiationsRequest$outboundSchema: z.ZodType<
    V3ListPaymentInitiationsRequest$Outbound,
    z.ZodTypeDef,
    V3ListPaymentInitiationsRequest
> = z.object({
    pageSize: z.number().int().optional(),
    cursor: z.string().optional(),
    query: z.record(z.any()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3ListPaymentInitiationsRequest$ {
    /** @deprecated use `V3ListPaymentInitiationsRequest$inboundSchema` instead. */
    export const inboundSchema = V3ListPaymentInitiationsRequest$inboundSchema;
    /** @deprecated use `V3ListPaymentInitiationsRequest$outboundSchema` instead. */
    export const outboundSchema = V3ListPaymentInitiationsRequest$outboundSchema;
    /** @deprecated use `V3ListPaymentInitiationsRequest$Outbound` instead. */
    export type Outbound = V3ListPaymentInitiationsRequest$Outbound;
}

/** @internal */
export const V3ListPaymentInitiationsResponse$inboundSchema: z.ZodType<
    V3ListPaymentInitiationsResponse,
    z.ZodTypeDef,
    unknown
> = z.union([
    components.V3PaymentInitiationsCursorResponse$inboundSchema,
    components.V3ErrorResponse$inboundSchema,
]);

/** @internal */
export type V3ListPaymentInitiationsResponse$Outbound =
    | components.V3PaymentInitiationsCursorResponse$Outbound
    | components.V3ErrorResponse$Outbound;

/** @internal */
export const V3ListPaymentInitiationsResponse$outboundSchema: z.ZodType<
    V3ListPaymentInitiationsResponse$Outbound,
    z.ZodTypeDef,
    V3ListPaymentInitiationsResponse
> = z.union([
    components.V3PaymentInitiationsCursorResponse$outboundSchema,
    components.V3ErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3ListPaymentInitiationsResponse$ {
    /** @deprecated use `V3ListPaymentInitiationsResponse$inboundSchema` instead. */
    export const inboundSchema = V3ListPaymentInitiationsResponse$inboundSchema;
    /** @deprecated use `V3ListPaymentInitiationsResponse$outboundSchema` instead. */
    export const outboundSchema = V3ListPaymentInitiationsResponse$outboundSchema;
    /** @deprecated use `V3ListPaymentInitiationsResponse$Outbound` instead. */
    export type Outbound = V3ListPaymentInitiationsResponse$Outbound;
}
