import {
  FCTL_SNIPPETS as SHARED_FCTL_SNIPPETS,
  TSnippetKeys as SharedTSnippetKeys,
  TSnippet,
  TSnippetParams,
} from '@platform/utils';
import { TRouteParams } from '../types/routes';
import { TRouteId } from './routes';

export type TSnippetKeys = SharedTSnippetKeys;

// Re-export the shared FCTL_SNIPPETS function with console-v3 specific types
export const FCTL_SNIPPETS = (
  params: Partial<TRouteParams>
): Record<TSnippetKeys, TSnippet> => {
  const sharedSnippets = SHARED_FCTL_SNIPPETS(params as TSnippetParams);

  // Convert shared snippets to console-v3 format
  const consoleSnippets: Record<TSnippetKeys, TSnippet> = {} as Record<
    TSnippetKeys,
    TSnippet
  >;

  Object.entries(sharedSnippets).forEach(([key, value]) => {
    const typedKey = key as TSnippetKeys;
    consoleSnippets[typedKey] = {
      title: value.title,
      snippet: value.snippet,
      version: value.version,
    };
  });

  return consoleSnippets;
};

// Keep the existing SNIPPETS_MAPPING for console-v3 specific routing
export const SNIPPETS_MAPPING: Record<TRouteId, TSnippetKeys[]> = {
  // Goto
  GO_TO: [],

  // Overview
  GLOBAL_OVERVIEW: [],

  // Settings
  // Oauth
  OAUTH_CLIENTS_OVERVIEW: [
    'OAUTH_CLIENTS_LIST',
    'OAUTH_CLIENTS_SHOW',
    'OAUTH_CLIENTS_CREATE',
    'OAUTH_CLIENTS_SECRETS_CREATE',
    'OAUTH_CLIENTS_SECRETS_DELETE',
  ],
  OAUTH_CLIENTS_OVERVIEW_RESOURCES: [],
  OAUTH_CLIENTS_OVERVIEW_FAVORITES: [],
  OAUTH_CLIENTS_ALL: ['OAUTH_CLIENTS_LIST', 'OAUTH_CLIENTS_CREATE'],
  OAUTH_CLIENT_DETAIL: [
    'OAUTH_CLIENTS_SHOW',
    'OAUTH_CLIENTS_SECRETS_CREATE',
    'OAUTH_CLIENTS_SECRETS_DELETE',
  ],
  OAUTH_CLIENT_CREATE: ['OAUTH_CLIENTS_CREATE'],

  // Webhook
  WEBHOOKS_OVERVIEW: ['WEBHOOKS_ENABLE', 'WEBHOOKS_LIST', 'WEBHOOKS_CREATE'],
  WEBHOOKS_OVERVIEW_RESOURCES: [],
  WEBHOOKS_OVERVIEW_FAVORITES: [],
  WEBHOOKS_ALL: ['WEBHOOKS_LIST', 'WEBHOOKS_CREATE'],
  WEBHOOK_DETAIL: ['WEBHOOKS_SHOW'],
  WEBHOOK_CREATE: ['WEBHOOKS_CREATE'],

  // Connectors
  CONNECTIVITY_CONNECTORS_ALL: ['CONNECTORS_LIST', 'CONNECTOR_INSTALL'],
  CONNECTIVITY_CONNECTOR_DETAIL: ['CONNECTOR_INSTALL'],
  CONNECTIVITY_CONNECTORS_INSTALLED: ['CONNECTORS_LIST', 'CONNECTOR_INSTALL'],
  CONNECTIVITY_CONNECTOR_INSTALLED_DETAIL: [
    'CONNECTORS_SHOW',
    'CONNECTOR_UNINSTALL',
  ],
  CONNECTIVITY_CONNECTOR_INSTALLED_TASKS_DETAIL: [],
  CONNECTIVITY_INSTALL_CONNECTOR: ['CONNECTOR_INSTALL'],

  // Ledger
  LEDGER_OVERVIEW: [
    'LEDGER_LIST',
    'LEDGER_CREATE',
    'LEDGER_IMPORT',
    'LEDGER_EXPORT',
  ],
  LEDGER_OVERVIEW_RESOURCES: [],
  LEDGER_OVERVIEW_FAVORITES: [],
  LEDGER_ALL: ['LEDGER_LIST', 'LEDGER_CREATE'],
  LEDGER_DETAIL: [
    'LEDGER_STATS',
    'LEDGER_SET_METADATA',
    'LEDGER_DELETE_METADATA',
  ],
  LEDGER_STORAGE_MIGRATIONS: [],
  LEDGER_TRANSACTIONS_INDEX: [
    'LEDGER_TRANSACTIONS_LIST',
    'LEDGER_TRANSACTIONS_LIST_BY_LEDGER',
  ],
  LEDGER_TRANSACTIONS: [
    'LEDGER_TRANSACTIONS_LIST',
    'LEDGER_TRANSACTIONS_LIST_BY_LEDGER',
  ],
  LEDGER_TRANSACTION: ['LEDGER_TRANSACTIONS_SHOW'],
  LEDGER_TRANSACTION_INFORMATION: ['LEDGER_TRANSACTIONS_SHOW'],
  LEDGER_TRANSACTION_METADATA: [],

  LEDGER_ACCOUNTS_INDEX: ['LEDGER_ACCOUNTS_LIST'],
  LEDGER_ACCOUNTS: ['LEDGER_ACCOUNTS_LIST', 'LEDGER_ACCOUNTS_LIST_BY_LEDGER'],
  LEDGER_ACCOUNT: ['LEDGER_ACCOUNT_SHOW'],
  LEDGER_ACCOUNT_ASSETS: ['LEDGER_ACCOUNT_SHOW'],
  LEDGER_ACCOUNT_METADATA: ['LEDGER_ACCOUNT_SHOW'],
  LEDGER_VOLUMES: ['LEDGER_VOLUMES_LIST'],
  LEDGER_AGGREGATE_BALANCES: [],
  LEDGER_LOGS: [],
  LEDGER_CREATE: ['LEDGER_CREATE'],

  // Connectivity
  CONNECTIVITY_OVERVIEW: [
    'CONNECTIVITY_PAYMENTS_LIST',
    'CONNECTIVITY_ACCOUNTS_LIST',
    'CONNECTIVITY_CASH_POOLS_LIST',
    'CONNECTIVITY_TRANSFERS_LIST',
    'CONNECTIVITY_BANK_ACCOUNTS_LIST',
  ],
  CONNECTIVITY_OVERVIEW_RESOURCES: [],
  CONNECTIVITY_OVERVIEW_FAVORITES: [],
  CONNECTIVITY_PAYMENTS: ['CONNECTIVITY_PAYMENTS_LIST'],
  CONNECTIVITY_PAYMENT_DETAIL: ['CONNECTIVITY_PAYMENT_DETAIL'],
  CONNECTIVITY_ACCOUNTS: ['CONNECTIVITY_ACCOUNTS_LIST'],
  CONNECTIVITY_ACCOUNT_DETAIL: ['CONNECTIVITY_ACCOUNT_DETAIL'],
  CONNECTIVITY_ACCOUNT_BALANCES: [],
  CONNECTIVITY_ACCOUNT_TRANSFERS: [],
  CONNECTIVITY_ACCOUNT_POOLS: [],
  CONNECTIVITY_CASH_POOLS_CREATE: [],
  CONNECTIVITY_CASH_POOLS: [
    'CONNECTIVITY_CASH_POOLS_LIST',
    'CONNECTIVITY_CASH_POOLS_CREATE',
  ],
  CONNECTIVITY_CASH_POOL_DETAIL: ['CONNECTIVITY_CASH_POOL_DETAIL'],
  CONNECTIVITY_TRANSFERS: [
    'CONNECTIVITY_TRANSFERS_LIST',
    'CONNECTIVITY_TRANSFERS_CREATE',
  ],
  CONNECTIVITY_TRANSFER_DETAIL: [
    'CONNECTIVITY_TRANSFER_DETAIL',
    'CONNECTIVITY_TRANSFER_UPDATE_STATUS',
    'CONNECTIVITY_TRANSFER_RETRY',
    'CONNECTIVITY_TRANSFER_REVERSE',
  ],
  CONNECTIVITY_TRANSFERS_VALIDATE: [
    'CONNECTIVITY_TRANSFER_DETAIL',
    'CONNECTIVITY_TRANSFER_UPDATE_STATUS',
    'CONNECTIVITY_TRANSFER_RETRY',
    'CONNECTIVITY_TRANSFER_REVERSE',
  ],
  CONNECTIVITY_BANK_ACCOUNTS: ['CONNECTIVITY_BANK_ACCOUNTS_LIST'],
  CONNECTIVITY_BANK_ACCOUNT_DETAIL: ['CONNECTIVITY_BANK_ACCOUNT_DETAIL'],
  CONNECTIVITY_BANK_ACCOUNTS_CREATE: ['CONNECTIVITY_BANK_ACCOUNTS_CREATE'],
  // Wallets
  WALLETS_OVERVIEW: ['WALLETS_ENABLE', 'WALLET_LIST', 'WALLET_CREATE'],
  WALLETS_OVERVIEW_RESOURCES: [],
  WALLETS_OVERVIEW_FAVORITES: [],
  WALLETS_ALL: ['WALLET_LIST', 'WALLET_CREATE'],
  WALLET_DETAIL: [
    'WALLET_DETAIL',
    'WALLET_UPDATE',
    'WALLET_TRANSACTIONS',
    'WALLET_BALANCES',
    'WALLET_CREATE_BALANCE',
    'WALLET_CREDIT_BALANCE',
    'WALLET_DEBIT_BALANCE',
    'WALLET_HOLDS_LIST',
    'WALLET_HOLDS_SHOW',
    'WALLET_HOLDS_CREATE',
    'WALLET_HOLDS_CONFIRM',
    'WALLET_HOLDS_CANCEL',
  ],
  WALLET_BALANCES: [
    'WALLET_BALANCES',
    'WALLET_CREATE_BALANCE',
    'WALLET_CREDIT_BALANCE',
    'WALLET_DEBIT_BALANCE',
  ],
  WALLET_HOLDS: [
    'WALLET_HOLDS_LIST',
    'WALLET_HOLDS_SHOW',
    'WALLET_HOLDS_CREATE',
  ],
  WALLET_HOLD: [
    'WALLET_HOLDS_SHOW',
    'WALLET_HOLDS_CONFIRM',
    'WALLET_HOLDS_CANCEL',
  ],
  WALLET_TRANSACTIONS: ['WALLET_TRANSACTIONS'],
  WALLET_CREATE: ['WALLET_CREATE'],

  // Flows
  FLOWS_OVERVIEW: [
    'FLOWS_ENABLE',
    'FLOWS_WORKFLOWS_LIST',
    'FLOWS_INSTANCES_LIST',
    'FLOWS_WORKFLOW_SHOW',
  ],
  FLOWS_OVERVIEW_RESOURCES: [],
  FLOWS_OVERVIEW_FAVORITES: [],
  FLOWS_WORKFLOWS: ['FLOWS_WORKFLOWS_LIST', 'FLOWS_WORKFLOW_CREATE'],
  FLOWS_WORKFLOW_DETAIL: [
    'FLOWS_WORKFLOW_CREATE',
    'FLOWS_WORKFLOW_SHOW',
    'FLOWS_WORKFLOW_RUN',
    'FLOWS_WORKFLOW_DELETE',
  ],
  FLOWS_INSTANCES: ['FLOWS_INSTANCES_LIST'],
  FLOWS_INSTANCE_DETAIL: [
    'FLOWS_INSTANCE_DESCRIBE',
    'FLOWS_INSTANCE_SHOW',
    'FLOWS_INSTANCE_STOP',
    'FLOWS_INSTANCE_SEND_EVENT',
  ],
  FLOWS_TRIGGERS: ['FLOWS_TRIGGERS_LIST', 'FLOWS_TRIGGER_CREATE'],
  FLOWS_TRIGGER_DETAIL: [
    'FLOWS_TRIGGER_SHOW',
    'FLOWS_TRIGGER_CREATE',
    'FLOWS_TRIGGER_TEST',
    'FLOWS_TRIGGER_OCCURRENCES_LIST',
    'FLOWS_TRIGGER_DELETE',
  ],

  // Reconciliation
  RECONCILIATION_OVERVIEW: [
    'RECONCILIATION_ENABLE',
    'RECONCILIATION_POLICIES_LIST',
    'RECONCILIATION_POLICY_SHOW',
    'RECONCILIATION_REPORTS_LIST',
    'RECONCILIATION_REPORT_SHOW',
  ],
  RECONCILIATION_OVERVIEW_RESOURCES: [],
  RECONCILIATION_OVERVIEW_FAVORITES: [],
  RECONCILIATION_POLICY_CREATE: ['RECONCILIATION_POLICY_CREATE'],
  RECONCILIATION_POLICY_DETAIL: [
    'RECONCILIATION_POLICY_SHOW',
    'RECONCILIATION_POLICY_DELETE',
    'RECONCILIATION_POLICY_CREATE',
    'RECONCILIATION_POLICY_RECONCILE',
  ],
  RECONCILIATION_REPORTS_LIST: [
    'RECONCILIATION_REPORTS_LIST',
    'RECONCILIATION_POLICY_RECONCILE',
  ],
  RECONCILIATION_REPORT_DETAIL: [
    'RECONCILIATION_REPORT_SHOW',
    'RECONCILIATION_REPORT_DELETE',
  ],
  RECONCILIATION_POLICIES_LIST: [
    'RECONCILIATION_POLICIES_LIST',
    'RECONCILIATION_POLICY_CREATE',
  ],
  BANKING_BRIDGE_OVERVIEW: [],
  BANKING_BRIDGE_BROWSE: [],
};
