/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    Account,
    Account$inboundSchema,
    Account$Outbound,
    Account$outboundSchema,
} from "./account.js";
import * as z from "zod";

export type Cursor = {
    pageSize: number;
    hasMore: boolean;
    previous?: string | undefined;
    next?: string | undefined;
    data: Array<Account>;
};

export type AccountsCursorResponse = {
    cursor: Cursor;
};

/** @internal */
export const Cursor$inboundSchema: z.ZodType<Cursor, z.ZodTypeDef, unknown> = z.object({
    pageSize: z.number().int(),
    hasMore: z.boolean(),
    previous: z.string().optional(),
    next: z.string().optional(),
    data: z.array(Account$inboundSchema),
});

/** @internal */
export type Cursor$Outbound = {
    pageSize: number;
    hasMore: boolean;
    previous?: string | undefined;
    next?: string | undefined;
    data: Array<Account$Outbound>;
};

/** @internal */
export const Cursor$outboundSchema: z.ZodType<Cursor$Outbound, z.ZodTypeDef, Cursor> = z.object({
    pageSize: z.number().int(),
    hasMore: z.boolean(),
    previous: z.string().optional(),
    next: z.string().optional(),
    data: z.array(Account$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Cursor$ {
    /** @deprecated use `Cursor$inboundSchema` instead. */
    export const inboundSchema = Cursor$inboundSchema;
    /** @deprecated use `Cursor$outboundSchema` instead. */
    export const outboundSchema = Cursor$outboundSchema;
    /** @deprecated use `Cursor$Outbound` instead. */
    export type Outbound = Cursor$Outbound;
}

/** @internal */
export const AccountsCursorResponse$inboundSchema: z.ZodType<
    AccountsCursorResponse,
    z.ZodTypeDef,
    unknown
> = z.object({
    cursor: z.lazy(() => Cursor$inboundSchema),
});

/** @internal */
export type AccountsCursorResponse$Outbound = {
    cursor: Cursor$Outbound;
};

/** @internal */
export const AccountsCursorResponse$outboundSchema: z.ZodType<
    AccountsCursorResponse$Outbound,
    z.ZodTypeDef,
    AccountsCursorResponse
> = z.object({
    cursor: z.lazy(() => Cursor$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AccountsCursorResponse$ {
    /** @deprecated use `AccountsCursorResponse$inboundSchema` instead. */
    export const inboundSchema = AccountsCursorResponse$inboundSchema;
    /** @deprecated use `AccountsCursorResponse$outboundSchema` instead. */
    export const outboundSchema = AccountsCursorResponse$outboundSchema;
    /** @deprecated use `AccountsCursorResponse$Outbound` instead. */
    export type Outbound = AccountsCursorResponse$Outbound;
}
