/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    FlowsTransaction,
    FlowsTransaction$inboundSchema,
    FlowsTransaction$Outbound,
    FlowsTransaction$outboundSchema,
} from "./flowstransaction.js";
import * as z from "zod";

export type ActivityCreateTransactionOutput = {
    data: FlowsTransaction;
};

/** @internal */
export const ActivityCreateTransactionOutput$inboundSchema: z.ZodType<
    ActivityCreateTransactionOutput,
    z.ZodTypeDef,
    unknown
> = z.object({
    data: FlowsTransaction$inboundSchema,
});

/** @internal */
export type ActivityCreateTransactionOutput$Outbound = {
    data: FlowsTransaction$Outbound;
};

/** @internal */
export const ActivityCreateTransactionOutput$outboundSchema: z.ZodType<
    ActivityCreateTransactionOutput$Outbound,
    z.ZodTypeDef,
    ActivityCreateTransactionOutput
> = z.object({
    data: FlowsTransaction$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ActivityCreateTransactionOutput$ {
    /** @deprecated use `ActivityCreateTransactionOutput$inboundSchema` instead. */
    export const inboundSchema = ActivityCreateTransactionOutput$inboundSchema;
    /** @deprecated use `ActivityCreateTransactionOutput$outboundSchema` instead. */
    export const outboundSchema = ActivityCreateTransactionOutput$outboundSchema;
    /** @deprecated use `ActivityCreateTransactionOutput$Outbound` instead. */
    export type Outbound = ActivityCreateTransactionOutput$Outbound;
}
