/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    FlowsCreditWalletRequest,
    FlowsCreditWalletRequest$inboundSchema,
    FlowsCreditWalletRequest$Outbound,
    FlowsCreditWalletRequest$outboundSchema,
} from "./flowscreditwalletrequest.js";
import * as z from "zod";

export type ActivityCreditWallet = {
    id?: string | undefined;
    data?: FlowsCreditWalletRequest | undefined;
};

/** @internal */
export const ActivityCreditWallet$inboundSchema: z.ZodType<
    ActivityCreditWallet,
    z.ZodTypeDef,
    unknown
> = z.object({
    id: z.string().optional(),
    data: FlowsCreditWalletRequest$inboundSchema.optional(),
});

/** @internal */
export type ActivityCreditWallet$Outbound = {
    id?: string | undefined;
    data?: FlowsCreditWalletRequest$Outbound | undefined;
};

/** @internal */
export const ActivityCreditWallet$outboundSchema: z.ZodType<
    ActivityCreditWallet$Outbound,
    z.ZodTypeDef,
    ActivityCreditWallet
> = z.object({
    id: z.string().optional(),
    data: FlowsCreditWalletRequest$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ActivityCreditWallet$ {
    /** @deprecated use `ActivityCreditWallet$inboundSchema` instead. */
    export const inboundSchema = ActivityCreditWallet$inboundSchema;
    /** @deprecated use `ActivityCreditWallet$outboundSchema` instead. */
    export const outboundSchema = ActivityCreditWallet$outboundSchema;
    /** @deprecated use `ActivityCreditWallet$Outbound` instead. */
    export type Outbound = ActivityCreditWallet$Outbound;
}
