/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type BalancesCursorResponseCursor = {
    pageSize: number;
    hasMore: boolean;
    previous?: string | undefined;
    next?: string | undefined;
    data: Array<{ [k: string]: { [k: string]: number } }>;
};

export type BalancesCursorResponse = {
    cursor: BalancesCursorResponseCursor;
};

/** @internal */
export const BalancesCursorResponseCursor$inboundSchema: z.ZodType<
    BalancesCursorResponseCursor,
    z.ZodTypeDef,
    unknown
> = z.object({
    pageSize: z.number().int(),
    hasMore: z.boolean(),
    previous: z.string().optional(),
    next: z.string().optional(),
    data: z.array(z.record(z.record(z.number().int()))),
});

/** @internal */
export type BalancesCursorResponseCursor$Outbound = {
    pageSize: number;
    hasMore: boolean;
    previous?: string | undefined;
    next?: string | undefined;
    data: Array<{ [k: string]: { [k: string]: number } }>;
};

/** @internal */
export const BalancesCursorResponseCursor$outboundSchema: z.ZodType<
    BalancesCursorResponseCursor$Outbound,
    z.ZodTypeDef,
    BalancesCursorResponseCursor
> = z.object({
    pageSize: z.number().int(),
    hasMore: z.boolean(),
    previous: z.string().optional(),
    next: z.string().optional(),
    data: z.array(z.record(z.record(z.number().int()))),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BalancesCursorResponseCursor$ {
    /** @deprecated use `BalancesCursorResponseCursor$inboundSchema` instead. */
    export const inboundSchema = BalancesCursorResponseCursor$inboundSchema;
    /** @deprecated use `BalancesCursorResponseCursor$outboundSchema` instead. */
    export const outboundSchema = BalancesCursorResponseCursor$outboundSchema;
    /** @deprecated use `BalancesCursorResponseCursor$Outbound` instead. */
    export type Outbound = BalancesCursorResponseCursor$Outbound;
}

/** @internal */
export const BalancesCursorResponse$inboundSchema: z.ZodType<
    BalancesCursorResponse,
    z.ZodTypeDef,
    unknown
> = z.object({
    cursor: z.lazy(() => BalancesCursorResponseCursor$inboundSchema),
});

/** @internal */
export type BalancesCursorResponse$Outbound = {
    cursor: BalancesCursorResponseCursor$Outbound;
};

/** @internal */
export const BalancesCursorResponse$outboundSchema: z.ZodType<
    BalancesCursorResponse$Outbound,
    z.ZodTypeDef,
    BalancesCursorResponse
> = z.object({
    cursor: z.lazy(() => BalancesCursorResponseCursor$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BalancesCursorResponse$ {
    /** @deprecated use `BalancesCursorResponse$inboundSchema` instead. */
    export const inboundSchema = BalancesCursorResponse$inboundSchema;
    /** @deprecated use `BalancesCursorResponse$outboundSchema` instead. */
    export const outboundSchema = BalancesCursorResponse$outboundSchema;
    /** @deprecated use `BalancesCursorResponse$Outbound` instead. */
    export type Outbound = BalancesCursorResponse$Outbound;
}
