/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type BalanceWithAssets = {
    name: string;
    expiresAt?: Date | null | undefined;
    priority?: bigint | undefined;
    assets: { [k: string]: bigint };
};

/** @internal */
export const BalanceWithAssets$inboundSchema: z.ZodType<BalanceWithAssets, z.ZodTypeDef, unknown> =
    z.object({
        name: z.string(),
        expiresAt: z
            .nullable(
                z
                    .string()
                    .datetime({ offset: true })
                    .transform((v) => new Date(v))
            )
            .optional(),
        priority: z
            .number()
            .transform((v) => BigInt(v))
            .optional(),
        assets: z.record(z.number().transform((v) => BigInt(v))),
    });

/** @internal */
export type BalanceWithAssets$Outbound = {
    name: string;
    expiresAt?: string | null | undefined;
    priority?: number | undefined;
    assets: { [k: string]: number };
};

/** @internal */
export const BalanceWithAssets$outboundSchema: z.ZodType<
    BalanceWithAssets$Outbound,
    z.ZodTypeDef,
    BalanceWithAssets
> = z.object({
    name: z.string(),
    expiresAt: z.nullable(z.date().transform((v) => v.toISOString())).optional(),
    priority: z
        .bigint()
        .transform((v) => Number(v))
        .optional(),
    assets: z.record(z.bigint().transform((v) => Number(v))),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BalanceWithAssets$ {
    /** @deprecated use `BalanceWithAssets$inboundSchema` instead. */
    export const inboundSchema = BalanceWithAssets$inboundSchema;
    /** @deprecated use `BalanceWithAssets$outboundSchema` instead. */
    export const outboundSchema = BalanceWithAssets$outboundSchema;
    /** @deprecated use `BalanceWithAssets$Outbound` instead. */
    export type Outbound = BalanceWithAssets$Outbound;
}
