/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type BankAccountRelatedAccounts = {
    id: string;
    createdAt: Date;
    provider: string;
    connectorID: string;
    accountID: string;
};

/** @internal */
export const BankAccountRelatedAccounts$inboundSchema: z.ZodType<
    BankAccountRelatedAccounts,
    z.ZodTypeDef,
    unknown
> = z.object({
    id: z.string(),
    createdAt: z
        .string()
        .datetime({ offset: true })
        .transform((v) => new Date(v)),
    provider: z.string(),
    connectorID: z.string(),
    accountID: z.string(),
});

/** @internal */
export type BankAccountRelatedAccounts$Outbound = {
    id: string;
    createdAt: string;
    provider: string;
    connectorID: string;
    accountID: string;
};

/** @internal */
export const BankAccountRelatedAccounts$outboundSchema: z.ZodType<
    BankAccountRelatedAccounts$Outbound,
    z.ZodTypeDef,
    BankAccountRelatedAccounts
> = z.object({
    id: z.string(),
    createdAt: z.date().transform((v) => v.toISOString()),
    provider: z.string(),
    connectorID: z.string(),
    accountID: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BankAccountRelatedAccounts$ {
    /** @deprecated use `BankAccountRelatedAccounts$inboundSchema` instead. */
    export const inboundSchema = BankAccountRelatedAccounts$inboundSchema;
    /** @deprecated use `BankAccountRelatedAccounts$outboundSchema` instead. */
    export const outboundSchema = BankAccountRelatedAccounts$outboundSchema;
    /** @deprecated use `BankAccountRelatedAccounts$Outbound` instead. */
    export type Outbound = BankAccountRelatedAccounts$Outbound;
}
