/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ConnectorsConfigsResponseData = {
    dataType: string;
    required: boolean;
    defaultValue?: string | undefined;
};

export type ConnectorsConfigsResponse = {
    data: { [k: string]: { [k: string]: ConnectorsConfigsResponseData } };
};

/** @internal */
export const ConnectorsConfigsResponseData$inboundSchema: z.ZodType<
    ConnectorsConfigsResponseData,
    z.ZodTypeDef,
    unknown
> = z.object({
    dataType: z.string(),
    required: z.boolean(),
    defaultValue: z.string().optional(),
});

/** @internal */
export type ConnectorsConfigsResponseData$Outbound = {
    dataType: string;
    required: boolean;
    defaultValue?: string | undefined;
};

/** @internal */
export const ConnectorsConfigsResponseData$outboundSchema: z.ZodType<
    ConnectorsConfigsResponseData$Outbound,
    z.ZodTypeDef,
    ConnectorsConfigsResponseData
> = z.object({
    dataType: z.string(),
    required: z.boolean(),
    defaultValue: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConnectorsConfigsResponseData$ {
    /** @deprecated use `ConnectorsConfigsResponseData$inboundSchema` instead. */
    export const inboundSchema = ConnectorsConfigsResponseData$inboundSchema;
    /** @deprecated use `ConnectorsConfigsResponseData$outboundSchema` instead. */
    export const outboundSchema = ConnectorsConfigsResponseData$outboundSchema;
    /** @deprecated use `ConnectorsConfigsResponseData$Outbound` instead. */
    export type Outbound = ConnectorsConfigsResponseData$Outbound;
}

/** @internal */
export const ConnectorsConfigsResponse$inboundSchema: z.ZodType<
    ConnectorsConfigsResponse,
    z.ZodTypeDef,
    unknown
> = z.object({
    data: z.record(z.record(z.lazy(() => ConnectorsConfigsResponseData$inboundSchema))),
});

/** @internal */
export type ConnectorsConfigsResponse$Outbound = {
    data: { [k: string]: { [k: string]: ConnectorsConfigsResponseData$Outbound } };
};

/** @internal */
export const ConnectorsConfigsResponse$outboundSchema: z.ZodType<
    ConnectorsConfigsResponse$Outbound,
    z.ZodTypeDef,
    ConnectorsConfigsResponse
> = z.object({
    data: z.record(z.record(z.lazy(() => ConnectorsConfigsResponseData$outboundSchema))),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConnectorsConfigsResponse$ {
    /** @deprecated use `ConnectorsConfigsResponse$inboundSchema` instead. */
    export const inboundSchema = ConnectorsConfigsResponse$inboundSchema;
    /** @deprecated use `ConnectorsConfigsResponse$outboundSchema` instead. */
    export const outboundSchema = ConnectorsConfigsResponse$outboundSchema;
    /** @deprecated use `ConnectorsConfigsResponse$Outbound` instead. */
    export type Outbound = ConnectorsConfigsResponse$Outbound;
}
