/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types/enums.js";
import * as z from "zod";

export const ErrorErrorCode = {
    Validation: "VALIDATION",
    NotFound: "NOT_FOUND",
    Internal: "INTERNAL",
} as const;
export type ErrorErrorCode = ClosedEnum<typeof ErrorErrorCode>;

export type ErrorT = {
    errorCode: ErrorErrorCode;
    errorMessage: string;
};

/** @internal */
export const ErrorErrorCode$inboundSchema: z.ZodNativeEnum<typeof ErrorErrorCode> =
    z.nativeEnum(ErrorErrorCode);

/** @internal */
export const ErrorErrorCode$outboundSchema: z.ZodNativeEnum<typeof ErrorErrorCode> =
    ErrorErrorCode$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ErrorErrorCode$ {
    /** @deprecated use `ErrorErrorCode$inboundSchema` instead. */
    export const inboundSchema = ErrorErrorCode$inboundSchema;
    /** @deprecated use `ErrorErrorCode$outboundSchema` instead. */
    export const outboundSchema = ErrorErrorCode$outboundSchema;
}

/** @internal */
export const ErrorT$inboundSchema: z.ZodType<ErrorT, z.ZodTypeDef, unknown> = z.object({
    errorCode: ErrorErrorCode$inboundSchema,
    errorMessage: z.string(),
});

/** @internal */
export type ErrorT$Outbound = {
    errorCode: string;
    errorMessage: string;
};

/** @internal */
export const ErrorT$outboundSchema: z.ZodType<ErrorT$Outbound, z.ZodTypeDef, ErrorT> = z.object({
    errorCode: ErrorErrorCode$outboundSchema,
    errorMessage: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ErrorT$ {
    /** @deprecated use `ErrorT$inboundSchema` instead. */
    export const inboundSchema = ErrorT$inboundSchema;
    /** @deprecated use `ErrorT$outboundSchema` instead. */
    export const outboundSchema = ErrorT$outboundSchema;
    /** @deprecated use `ErrorT$Outbound` instead. */
    export type Outbound = ErrorT$Outbound;
}
