/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types/enums.js";
import {
    FlowsConnector,
    FlowsConnector$inboundSchema,
    FlowsConnector$outboundSchema,
} from "./flowsconnector.js";
import {
    FlowsPaymentAdjustment,
    FlowsPaymentAdjustment$inboundSchema,
    FlowsPaymentAdjustment$Outbound,
    FlowsPaymentAdjustment$outboundSchema,
} from "./flowspaymentadjustment.js";
import {
    FlowsPaymentMetadata,
    FlowsPaymentMetadata$inboundSchema,
    FlowsPaymentMetadata$Outbound,
    FlowsPaymentMetadata$outboundSchema,
} from "./flowspaymentmetadata.js";
import {
    FlowsPaymentStatus,
    FlowsPaymentStatus$inboundSchema,
    FlowsPaymentStatus$outboundSchema,
} from "./flowspaymentstatus.js";
import * as z from "zod";

export const FlowsPaymentType = {
    PayIn: "PAY-IN",
    Payout: "PAYOUT",
    Transfer: "TRANSFER",
    Other: "OTHER",
} as const;
export type FlowsPaymentType = ClosedEnum<typeof FlowsPaymentType>;

export const Scheme = {
    Visa: "visa",
    Mastercard: "mastercard",
    Amex: "amex",
    Diners: "diners",
    Discover: "discover",
    Jcb: "jcb",
    Unionpay: "unionpay",
    SepaDebit: "sepa debit",
    SepaCredit: "sepa credit",
    Sepa: "sepa",
    ApplePay: "apple pay",
    GooglePay: "google pay",
    A2a: "a2a",
    AchDebit: "ach debit",
    Ach: "ach",
    Rtp: "rtp",
    Unknown: "unknown",
    Other: "other",
} as const;
export type Scheme = ClosedEnum<typeof Scheme>;

export type FlowsPaymentRaw = {};

export type FlowsPayment = {
    id: string;
    reference: string;
    sourceAccountID: string;
    destinationAccountID: string;
    connectorID: string;
    provider?: FlowsConnector | undefined;
    type: FlowsPaymentType;
    status: FlowsPaymentStatus;
    initialAmount: bigint;
    scheme: Scheme;
    asset: string;
    createdAt: Date;
    raw: FlowsPaymentRaw | null;
    adjustments: Array<FlowsPaymentAdjustment>;
    metadata: FlowsPaymentMetadata | null;
};

/** @internal */
export const FlowsPaymentType$inboundSchema: z.ZodNativeEnum<typeof FlowsPaymentType> =
    z.nativeEnum(FlowsPaymentType);

/** @internal */
export const FlowsPaymentType$outboundSchema: z.ZodNativeEnum<typeof FlowsPaymentType> =
    FlowsPaymentType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FlowsPaymentType$ {
    /** @deprecated use `FlowsPaymentType$inboundSchema` instead. */
    export const inboundSchema = FlowsPaymentType$inboundSchema;
    /** @deprecated use `FlowsPaymentType$outboundSchema` instead. */
    export const outboundSchema = FlowsPaymentType$outboundSchema;
}

/** @internal */
export const Scheme$inboundSchema: z.ZodNativeEnum<typeof Scheme> = z.nativeEnum(Scheme);

/** @internal */
export const Scheme$outboundSchema: z.ZodNativeEnum<typeof Scheme> = Scheme$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Scheme$ {
    /** @deprecated use `Scheme$inboundSchema` instead. */
    export const inboundSchema = Scheme$inboundSchema;
    /** @deprecated use `Scheme$outboundSchema` instead. */
    export const outboundSchema = Scheme$outboundSchema;
}

/** @internal */
export const FlowsPaymentRaw$inboundSchema: z.ZodType<FlowsPaymentRaw, z.ZodTypeDef, unknown> =
    z.object({});

/** @internal */
export type FlowsPaymentRaw$Outbound = {};

/** @internal */
export const FlowsPaymentRaw$outboundSchema: z.ZodType<
    FlowsPaymentRaw$Outbound,
    z.ZodTypeDef,
    FlowsPaymentRaw
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FlowsPaymentRaw$ {
    /** @deprecated use `FlowsPaymentRaw$inboundSchema` instead. */
    export const inboundSchema = FlowsPaymentRaw$inboundSchema;
    /** @deprecated use `FlowsPaymentRaw$outboundSchema` instead. */
    export const outboundSchema = FlowsPaymentRaw$outboundSchema;
    /** @deprecated use `FlowsPaymentRaw$Outbound` instead. */
    export type Outbound = FlowsPaymentRaw$Outbound;
}

/** @internal */
export const FlowsPayment$inboundSchema: z.ZodType<FlowsPayment, z.ZodTypeDef, unknown> = z.object({
    id: z.string(),
    reference: z.string(),
    sourceAccountID: z.string(),
    destinationAccountID: z.string(),
    connectorID: z.string(),
    provider: FlowsConnector$inboundSchema.optional(),
    type: FlowsPaymentType$inboundSchema,
    status: FlowsPaymentStatus$inboundSchema,
    initialAmount: z.number().transform((v) => BigInt(v)),
    scheme: Scheme$inboundSchema,
    asset: z.string(),
    createdAt: z
        .string()
        .datetime({ offset: true })
        .transform((v) => new Date(v)),
    raw: z.nullable(z.lazy(() => FlowsPaymentRaw$inboundSchema)),
    adjustments: z.array(FlowsPaymentAdjustment$inboundSchema),
    metadata: z.nullable(FlowsPaymentMetadata$inboundSchema),
});

/** @internal */
export type FlowsPayment$Outbound = {
    id: string;
    reference: string;
    sourceAccountID: string;
    destinationAccountID: string;
    connectorID: string;
    provider?: string | undefined;
    type: string;
    status: string;
    initialAmount: number;
    scheme: string;
    asset: string;
    createdAt: string;
    raw: FlowsPaymentRaw$Outbound | null;
    adjustments: Array<FlowsPaymentAdjustment$Outbound>;
    metadata: FlowsPaymentMetadata$Outbound | null;
};

/** @internal */
export const FlowsPayment$outboundSchema: z.ZodType<
    FlowsPayment$Outbound,
    z.ZodTypeDef,
    FlowsPayment
> = z.object({
    id: z.string(),
    reference: z.string(),
    sourceAccountID: z.string(),
    destinationAccountID: z.string(),
    connectorID: z.string(),
    provider: FlowsConnector$outboundSchema.optional(),
    type: FlowsPaymentType$outboundSchema,
    status: FlowsPaymentStatus$outboundSchema,
    initialAmount: z.bigint().transform((v) => Number(v)),
    scheme: Scheme$outboundSchema,
    asset: z.string(),
    createdAt: z.date().transform((v) => v.toISOString()),
    raw: z.nullable(z.lazy(() => FlowsPaymentRaw$outboundSchema)),
    adjustments: z.array(FlowsPaymentAdjustment$outboundSchema),
    metadata: z.nullable(FlowsPaymentMetadata$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FlowsPayment$ {
    /** @deprecated use `FlowsPayment$inboundSchema` instead. */
    export const inboundSchema = FlowsPayment$inboundSchema;
    /** @deprecated use `FlowsPayment$outboundSchema` instead. */
    export const outboundSchema = FlowsPayment$outboundSchema;
    /** @deprecated use `FlowsPayment$Outbound` instead. */
    export type Outbound = FlowsPayment$Outbound;
}
