/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    FlowsWallet,
    FlowsWallet$inboundSchema,
    FlowsWallet$Outbound,
    FlowsWallet$outboundSchema,
} from "./flowswallet.js";
import * as z from "zod";

export type FlowsListWalletsResponseCursor = {
    pageSize: number;
    hasMore?: boolean | undefined;
    previous?: string | undefined;
    next?: string | undefined;
    data: Array<FlowsWallet>;
};

export type FlowsListWalletsResponse = {
    cursor: FlowsListWalletsResponseCursor;
};

/** @internal */
export const FlowsListWalletsResponseCursor$inboundSchema: z.ZodType<
    FlowsListWalletsResponseCursor,
    z.ZodTypeDef,
    unknown
> = z.object({
    pageSize: z.number().int(),
    hasMore: z.boolean().optional(),
    previous: z.string().optional(),
    next: z.string().optional(),
    data: z.array(FlowsWallet$inboundSchema),
});

/** @internal */
export type FlowsListWalletsResponseCursor$Outbound = {
    pageSize: number;
    hasMore?: boolean | undefined;
    previous?: string | undefined;
    next?: string | undefined;
    data: Array<FlowsWallet$Outbound>;
};

/** @internal */
export const FlowsListWalletsResponseCursor$outboundSchema: z.ZodType<
    FlowsListWalletsResponseCursor$Outbound,
    z.ZodTypeDef,
    FlowsListWalletsResponseCursor
> = z.object({
    pageSize: z.number().int(),
    hasMore: z.boolean().optional(),
    previous: z.string().optional(),
    next: z.string().optional(),
    data: z.array(FlowsWallet$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FlowsListWalletsResponseCursor$ {
    /** @deprecated use `FlowsListWalletsResponseCursor$inboundSchema` instead. */
    export const inboundSchema = FlowsListWalletsResponseCursor$inboundSchema;
    /** @deprecated use `FlowsListWalletsResponseCursor$outboundSchema` instead. */
    export const outboundSchema = FlowsListWalletsResponseCursor$outboundSchema;
    /** @deprecated use `FlowsListWalletsResponseCursor$Outbound` instead. */
    export type Outbound = FlowsListWalletsResponseCursor$Outbound;
}

/** @internal */
export const FlowsListWalletsResponse$inboundSchema: z.ZodType<
    FlowsListWalletsResponse,
    z.ZodTypeDef,
    unknown
> = z.object({
    cursor: z.lazy(() => FlowsListWalletsResponseCursor$inboundSchema),
});

/** @internal */
export type FlowsListWalletsResponse$Outbound = {
    cursor: FlowsListWalletsResponseCursor$Outbound;
};

/** @internal */
export const FlowsListWalletsResponse$outboundSchema: z.ZodType<
    FlowsListWalletsResponse$Outbound,
    z.ZodTypeDef,
    FlowsListWalletsResponse
> = z.object({
    cursor: z.lazy(() => FlowsListWalletsResponseCursor$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FlowsListWalletsResponse$ {
    /** @deprecated use `FlowsListWalletsResponse$inboundSchema` instead. */
    export const inboundSchema = FlowsListWalletsResponse$inboundSchema;
    /** @deprecated use `FlowsListWalletsResponse$outboundSchema` instead. */
    export const outboundSchema = FlowsListWalletsResponse$outboundSchema;
    /** @deprecated use `FlowsListWalletsResponse$Outbound` instead. */
    export type Outbound = FlowsListWalletsResponse$Outbound;
}
