/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { Volume, Volume$inboundSchema, Volume$Outbound, Volume$outboundSchema } from "./volume.js";
import * as z from "zod";

export type FlowsAccount = {
    address: string;
    metadata: { [k: string]: string };
    volumes?: { [k: string]: Volume } | undefined;
    effectiveVolumes?: { [k: string]: Volume } | undefined;
};

/** @internal */
export const FlowsAccount$inboundSchema: z.ZodType<FlowsAccount, z.ZodTypeDef, unknown> = z.object({
    address: z.string(),
    metadata: z.record(z.string()),
    volumes: z.record(Volume$inboundSchema).optional(),
    effectiveVolumes: z.record(Volume$inboundSchema).optional(),
});

/** @internal */
export type FlowsAccount$Outbound = {
    address: string;
    metadata: { [k: string]: string };
    volumes?: { [k: string]: Volume$Outbound } | undefined;
    effectiveVolumes?: { [k: string]: Volume$Outbound } | undefined;
};

/** @internal */
export const FlowsAccount$outboundSchema: z.ZodType<
    FlowsAccount$Outbound,
    z.ZodTypeDef,
    FlowsAccount
> = z.object({
    address: z.string(),
    metadata: z.record(z.string()),
    volumes: z.record(Volume$outboundSchema).optional(),
    effectiveVolumes: z.record(Volume$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FlowsAccount$ {
    /** @deprecated use `FlowsAccount$inboundSchema` instead. */
    export const inboundSchema = FlowsAccount$inboundSchema;
    /** @deprecated use `FlowsAccount$outboundSchema` instead. */
    export const outboundSchema = FlowsAccount$outboundSchema;
    /** @deprecated use `FlowsAccount$Outbound` instead. */
    export type Outbound = FlowsAccount$Outbound;
}
