/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    Balance,
    Balance$inboundSchema,
    Balance$Outbound,
    Balance$outboundSchema,
} from "./balance.js";
import * as z from "zod";

export type ListBalancesResponseCursor = {
    pageSize: number;
    hasMore?: boolean | undefined;
    previous?: string | undefined;
    next?: string | undefined;
    data: Array<Balance>;
};

export type ListBalancesResponse = {
    cursor: ListBalancesResponseCursor;
};

/** @internal */
export const ListBalancesResponseCursor$inboundSchema: z.ZodType<
    ListBalancesResponseCursor,
    z.ZodTypeDef,
    unknown
> = z.object({
    pageSize: z.number().int(),
    hasMore: z.boolean().optional(),
    previous: z.string().optional(),
    next: z.string().optional(),
    data: z.array(Balance$inboundSchema),
});

/** @internal */
export type ListBalancesResponseCursor$Outbound = {
    pageSize: number;
    hasMore?: boolean | undefined;
    previous?: string | undefined;
    next?: string | undefined;
    data: Array<Balance$Outbound>;
};

/** @internal */
export const ListBalancesResponseCursor$outboundSchema: z.ZodType<
    ListBalancesResponseCursor$Outbound,
    z.ZodTypeDef,
    ListBalancesResponseCursor
> = z.object({
    pageSize: z.number().int(),
    hasMore: z.boolean().optional(),
    previous: z.string().optional(),
    next: z.string().optional(),
    data: z.array(Balance$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListBalancesResponseCursor$ {
    /** @deprecated use `ListBalancesResponseCursor$inboundSchema` instead. */
    export const inboundSchema = ListBalancesResponseCursor$inboundSchema;
    /** @deprecated use `ListBalancesResponseCursor$outboundSchema` instead. */
    export const outboundSchema = ListBalancesResponseCursor$outboundSchema;
    /** @deprecated use `ListBalancesResponseCursor$Outbound` instead. */
    export type Outbound = ListBalancesResponseCursor$Outbound;
}

/** @internal */
export const ListBalancesResponse$inboundSchema: z.ZodType<
    ListBalancesResponse,
    z.ZodTypeDef,
    unknown
> = z.object({
    cursor: z.lazy(() => ListBalancesResponseCursor$inboundSchema),
});

/** @internal */
export type ListBalancesResponse$Outbound = {
    cursor: ListBalancesResponseCursor$Outbound;
};

/** @internal */
export const ListBalancesResponse$outboundSchema: z.ZodType<
    ListBalancesResponse$Outbound,
    z.ZodTypeDef,
    ListBalancesResponse
> = z.object({
    cursor: z.lazy(() => ListBalancesResponseCursor$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListBalancesResponse$ {
    /** @deprecated use `ListBalancesResponse$inboundSchema` instead. */
    export const inboundSchema = ListBalancesResponse$inboundSchema;
    /** @deprecated use `ListBalancesResponse$outboundSchema` instead. */
    export const outboundSchema = ListBalancesResponse$outboundSchema;
    /** @deprecated use `ListBalancesResponse$Outbound` instead. */
    export type Outbound = ListBalancesResponse$Outbound;
}
