/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types/enums.js";
import * as z from "zod";

export const State = {
    ToDo: "TO DO",
    Done: "DONE",
} as const;
export type State = ClosedEnum<typeof State>;

export type MigrationInfo = {
    version?: string | undefined;
    name?: string | undefined;
    date?: Date | undefined;
    state?: State | undefined;
};

/** @internal */
export const State$inboundSchema: z.ZodNativeEnum<typeof State> = z.nativeEnum(State);

/** @internal */
export const State$outboundSchema: z.ZodNativeEnum<typeof State> = State$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace State$ {
    /** @deprecated use `State$inboundSchema` instead. */
    export const inboundSchema = State$inboundSchema;
    /** @deprecated use `State$outboundSchema` instead. */
    export const outboundSchema = State$outboundSchema;
}

/** @internal */
export const MigrationInfo$inboundSchema: z.ZodType<MigrationInfo, z.ZodTypeDef, unknown> =
    z.object({
        version: z.string().optional(),
        name: z.string().optional(),
        date: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v))
            .optional(),
        state: State$inboundSchema.optional(),
    });

/** @internal */
export type MigrationInfo$Outbound = {
    version?: string | undefined;
    name?: string | undefined;
    date?: string | undefined;
    state?: string | undefined;
};

/** @internal */
export const MigrationInfo$outboundSchema: z.ZodType<
    MigrationInfo$Outbound,
    z.ZodTypeDef,
    MigrationInfo
> = z.object({
    version: z.string().optional(),
    name: z.string().optional(),
    date: z
        .date()
        .transform((v) => v.toISOString())
        .optional(),
    state: State$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MigrationInfo$ {
    /** @deprecated use `MigrationInfo$inboundSchema` instead. */
    export const inboundSchema = MigrationInfo$inboundSchema;
    /** @deprecated use `MigrationInfo$outboundSchema` instead. */
    export const outboundSchema = MigrationInfo$outboundSchema;
    /** @deprecated use `MigrationInfo$Outbound` instead. */
    export type Outbound = MigrationInfo$Outbound;
}
