/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    AccountType,
    AccountType$inboundSchema,
    AccountType$outboundSchema,
} from "./accounttype.js";
import * as z from "zod";

export type PaymentsAccountRaw = {};

export type PaymentsAccount = {
    id: string;
    createdAt: Date;
    reference: string;
    connectorID: string;
    provider?: string | undefined;
    /**
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    defaultCurrency: string;
    defaultAsset: string;
    accountName: string;
    type: AccountType;
    pools?: Array<string> | undefined;
    metadata: { [k: string]: string } | null;
    raw: PaymentsAccountRaw | null;
};

/** @internal */
export const PaymentsAccountRaw$inboundSchema: z.ZodType<
    PaymentsAccountRaw,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type PaymentsAccountRaw$Outbound = {};

/** @internal */
export const PaymentsAccountRaw$outboundSchema: z.ZodType<
    PaymentsAccountRaw$Outbound,
    z.ZodTypeDef,
    PaymentsAccountRaw
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentsAccountRaw$ {
    /** @deprecated use `PaymentsAccountRaw$inboundSchema` instead. */
    export const inboundSchema = PaymentsAccountRaw$inboundSchema;
    /** @deprecated use `PaymentsAccountRaw$outboundSchema` instead. */
    export const outboundSchema = PaymentsAccountRaw$outboundSchema;
    /** @deprecated use `PaymentsAccountRaw$Outbound` instead. */
    export type Outbound = PaymentsAccountRaw$Outbound;
}

/** @internal */
export const PaymentsAccount$inboundSchema: z.ZodType<PaymentsAccount, z.ZodTypeDef, unknown> =
    z.object({
        id: z.string(),
        createdAt: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v)),
        reference: z.string(),
        connectorID: z.string(),
        provider: z.string().optional(),
        defaultCurrency: z.string(),
        defaultAsset: z.string(),
        accountName: z.string(),
        type: AccountType$inboundSchema,
        pools: z.array(z.string()).optional(),
        metadata: z.nullable(z.record(z.string())),
        raw: z.nullable(z.lazy(() => PaymentsAccountRaw$inboundSchema)),
    });

/** @internal */
export type PaymentsAccount$Outbound = {
    id: string;
    createdAt: string;
    reference: string;
    connectorID: string;
    provider?: string | undefined;
    defaultCurrency: string;
    defaultAsset: string;
    accountName: string;
    type: string;
    pools?: Array<string> | undefined;
    metadata: { [k: string]: string } | null;
    raw: PaymentsAccountRaw$Outbound | null;
};

/** @internal */
export const PaymentsAccount$outboundSchema: z.ZodType<
    PaymentsAccount$Outbound,
    z.ZodTypeDef,
    PaymentsAccount
> = z.object({
    id: z.string(),
    createdAt: z.date().transform((v) => v.toISOString()),
    reference: z.string(),
    connectorID: z.string(),
    provider: z.string().optional(),
    defaultCurrency: z.string(),
    defaultAsset: z.string(),
    accountName: z.string(),
    type: AccountType$outboundSchema,
    pools: z.array(z.string()).optional(),
    metadata: z.nullable(z.record(z.string())),
    raw: z.nullable(z.lazy(() => PaymentsAccountRaw$outboundSchema)),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentsAccount$ {
    /** @deprecated use `PaymentsAccount$inboundSchema` instead. */
    export const inboundSchema = PaymentsAccount$inboundSchema;
    /** @deprecated use `PaymentsAccount$outboundSchema` instead. */
    export const outboundSchema = PaymentsAccount$outboundSchema;
    /** @deprecated use `PaymentsAccount$Outbound` instead. */
    export type Outbound = PaymentsAccount$Outbound;
}
