/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types/enums.js";
import * as z from "zod";

export const PaymentType = {
    PayIn: "PAY-IN",
    Payout: "PAYOUT",
    Transfer: "TRANSFER",
    Other: "OTHER",
} as const;
export type PaymentType = ClosedEnum<typeof PaymentType>;

/** @internal */
export const PaymentType$inboundSchema: z.ZodNativeEnum<typeof PaymentType> =
    z.nativeEnum(PaymentType);

/** @internal */
export const PaymentType$outboundSchema: z.ZodNativeEnum<typeof PaymentType> =
    PaymentType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentType$ {
    /** @deprecated use `PaymentType$inboundSchema` instead. */
    export const inboundSchema = PaymentType$inboundSchema;
    /** @deprecated use `PaymentType$outboundSchema` instead. */
    export const outboundSchema = PaymentType$outboundSchema;
}
