/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { TaskStatus, TaskStatus$inboundSchema, TaskStatus$outboundSchema } from "./taskstatus.js";
import * as z from "zod";

export type TaskBankingCircleState = {};

export type TaskBankingCircleDescriptor = {
    name?: string | undefined;
    key?: string | undefined;
};

export type TaskBankingCircle = {
    id: string;
    connectorID: string;
    createdAt: Date;
    updatedAt: Date;
    status: TaskStatus;
    state?: TaskBankingCircleState | null | undefined;
    error?: string | null | undefined;
    descriptor: TaskBankingCircleDescriptor;
};

/** @internal */
export const TaskBankingCircleState$inboundSchema: z.ZodType<
    TaskBankingCircleState,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type TaskBankingCircleState$Outbound = {};

/** @internal */
export const TaskBankingCircleState$outboundSchema: z.ZodType<
    TaskBankingCircleState$Outbound,
    z.ZodTypeDef,
    TaskBankingCircleState
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskBankingCircleState$ {
    /** @deprecated use `TaskBankingCircleState$inboundSchema` instead. */
    export const inboundSchema = TaskBankingCircleState$inboundSchema;
    /** @deprecated use `TaskBankingCircleState$outboundSchema` instead. */
    export const outboundSchema = TaskBankingCircleState$outboundSchema;
    /** @deprecated use `TaskBankingCircleState$Outbound` instead. */
    export type Outbound = TaskBankingCircleState$Outbound;
}

/** @internal */
export const TaskBankingCircleDescriptor$inboundSchema: z.ZodType<
    TaskBankingCircleDescriptor,
    z.ZodTypeDef,
    unknown
> = z.object({
    name: z.string().optional(),
    key: z.string().optional(),
});

/** @internal */
export type TaskBankingCircleDescriptor$Outbound = {
    name?: string | undefined;
    key?: string | undefined;
};

/** @internal */
export const TaskBankingCircleDescriptor$outboundSchema: z.ZodType<
    TaskBankingCircleDescriptor$Outbound,
    z.ZodTypeDef,
    TaskBankingCircleDescriptor
> = z.object({
    name: z.string().optional(),
    key: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskBankingCircleDescriptor$ {
    /** @deprecated use `TaskBankingCircleDescriptor$inboundSchema` instead. */
    export const inboundSchema = TaskBankingCircleDescriptor$inboundSchema;
    /** @deprecated use `TaskBankingCircleDescriptor$outboundSchema` instead. */
    export const outboundSchema = TaskBankingCircleDescriptor$outboundSchema;
    /** @deprecated use `TaskBankingCircleDescriptor$Outbound` instead. */
    export type Outbound = TaskBankingCircleDescriptor$Outbound;
}

/** @internal */
export const TaskBankingCircle$inboundSchema: z.ZodType<TaskBankingCircle, z.ZodTypeDef, unknown> =
    z.object({
        id: z.string(),
        connectorID: z.string(),
        createdAt: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v)),
        updatedAt: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v)),
        status: TaskStatus$inboundSchema,
        state: z.nullable(z.lazy(() => TaskBankingCircleState$inboundSchema)).optional(),
        error: z.nullable(z.string()).optional(),
        descriptor: z.lazy(() => TaskBankingCircleDescriptor$inboundSchema),
    });

/** @internal */
export type TaskBankingCircle$Outbound = {
    id: string;
    connectorID: string;
    createdAt: string;
    updatedAt: string;
    status: string;
    state?: TaskBankingCircleState$Outbound | null | undefined;
    error?: string | null | undefined;
    descriptor: TaskBankingCircleDescriptor$Outbound;
};

/** @internal */
export const TaskBankingCircle$outboundSchema: z.ZodType<
    TaskBankingCircle$Outbound,
    z.ZodTypeDef,
    TaskBankingCircle
> = z.object({
    id: z.string(),
    connectorID: z.string(),
    createdAt: z.date().transform((v) => v.toISOString()),
    updatedAt: z.date().transform((v) => v.toISOString()),
    status: TaskStatus$outboundSchema,
    state: z.nullable(z.lazy(() => TaskBankingCircleState$outboundSchema)).optional(),
    error: z.nullable(z.string()).optional(),
    descriptor: z.lazy(() => TaskBankingCircleDescriptor$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TaskBankingCircle$ {
    /** @deprecated use `TaskBankingCircle$inboundSchema` instead. */
    export const inboundSchema = TaskBankingCircle$inboundSchema;
    /** @deprecated use `TaskBankingCircle$outboundSchema` instead. */
    export const outboundSchema = TaskBankingCircle$outboundSchema;
    /** @deprecated use `TaskBankingCircle$Outbound` instead. */
    export type Outbound = TaskBankingCircle$Outbound;
}
