/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Trigger = {
    event: string;
    workflowID: string;
    version?: string | undefined;
    filter?: string | undefined;
    vars?: { [k: string]: any } | undefined;
    name?: string | undefined;
    id: string;
    createdAt: Date;
};

/** @internal */
export const Trigger$inboundSchema: z.ZodType<Trigger, z.ZodTypeDef, unknown> = z.object({
    event: z.string(),
    workflowID: z.string(),
    version: z.string().optional(),
    filter: z.string().optional(),
    vars: z.record(z.any()).optional(),
    name: z.string().optional(),
    id: z.string(),
    createdAt: z
        .string()
        .datetime({ offset: true })
        .transform((v) => new Date(v)),
});

/** @internal */
export type Trigger$Outbound = {
    event: string;
    workflowID: string;
    version?: string | undefined;
    filter?: string | undefined;
    vars?: { [k: string]: any } | undefined;
    name?: string | undefined;
    id: string;
    createdAt: string;
};

/** @internal */
export const Trigger$outboundSchema: z.ZodType<Trigger$Outbound, z.ZodTypeDef, Trigger> = z.object({
    event: z.string(),
    workflowID: z.string(),
    version: z.string().optional(),
    filter: z.string().optional(),
    vars: z.record(z.any()).optional(),
    name: z.string().optional(),
    id: z.string(),
    createdAt: z.date().transform((v) => v.toISOString()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Trigger$ {
    /** @deprecated use `Trigger$inboundSchema` instead. */
    export const inboundSchema = Trigger$inboundSchema;
    /** @deprecated use `Trigger$outboundSchema` instead. */
    export const outboundSchema = Trigger$outboundSchema;
    /** @deprecated use `Trigger$Outbound` instead. */
    export type Outbound = Trigger$Outbound;
}
