/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    V2Transaction,
    V2Transaction$inboundSchema,
    V2Transaction$Outbound,
    V2Transaction$outboundSchema,
} from "./v2transaction.js";
import * as z from "zod";

export type V2BulkElementResultError = {
    responseType: string;
    logID: number;
    errorCode: string;
    errorDescription: string;
    errorDetails?: string | undefined;
};

export type V2BulkElementResultDeleteMetadata = {
    responseType: string;
    logID: number;
};

export type V2BulkElementResultRevertTransaction = {
    responseType: string;
    logID: number;
    data: V2Transaction;
};

export type V2BulkElementResultAddMetadata = {
    responseType: string;
    logID: number;
};

export type V2BulkElementResultCreateTransaction = {
    responseType: string;
    logID: number;
    data: V2Transaction;
};

export type V2BulkElementResult =
    | (V2BulkElementResultAddMetadata & { responseType: "ADD_METADATA" })
    | (V2BulkElementResultDeleteMetadata & { responseType: "DELETE_METADATA" })
    | (V2BulkElementResultCreateTransaction & { responseType: "CREATE_TRANSACTION" })
    | (V2BulkElementResultRevertTransaction & { responseType: "REVERT_TRANSACTION" })
    | (V2BulkElementResultError & { responseType: "ERROR" });

/** @internal */
export const V2BulkElementResultError$inboundSchema: z.ZodType<
    V2BulkElementResultError,
    z.ZodTypeDef,
    unknown
> = z.object({
    responseType: z.string(),
    logID: z.number().int(),
    errorCode: z.string(),
    errorDescription: z.string(),
    errorDetails: z.string().optional(),
});

/** @internal */
export type V2BulkElementResultError$Outbound = {
    responseType: string;
    logID: number;
    errorCode: string;
    errorDescription: string;
    errorDetails?: string | undefined;
};

/** @internal */
export const V2BulkElementResultError$outboundSchema: z.ZodType<
    V2BulkElementResultError$Outbound,
    z.ZodTypeDef,
    V2BulkElementResultError
> = z.object({
    responseType: z.string(),
    logID: z.number().int(),
    errorCode: z.string(),
    errorDescription: z.string(),
    errorDetails: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2BulkElementResultError$ {
    /** @deprecated use `V2BulkElementResultError$inboundSchema` instead. */
    export const inboundSchema = V2BulkElementResultError$inboundSchema;
    /** @deprecated use `V2BulkElementResultError$outboundSchema` instead. */
    export const outboundSchema = V2BulkElementResultError$outboundSchema;
    /** @deprecated use `V2BulkElementResultError$Outbound` instead. */
    export type Outbound = V2BulkElementResultError$Outbound;
}

/** @internal */
export const V2BulkElementResultDeleteMetadata$inboundSchema: z.ZodType<
    V2BulkElementResultDeleteMetadata,
    z.ZodTypeDef,
    unknown
> = z.object({
    responseType: z.string(),
    logID: z.number().int(),
});

/** @internal */
export type V2BulkElementResultDeleteMetadata$Outbound = {
    responseType: string;
    logID: number;
};

/** @internal */
export const V2BulkElementResultDeleteMetadata$outboundSchema: z.ZodType<
    V2BulkElementResultDeleteMetadata$Outbound,
    z.ZodTypeDef,
    V2BulkElementResultDeleteMetadata
> = z.object({
    responseType: z.string(),
    logID: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2BulkElementResultDeleteMetadata$ {
    /** @deprecated use `V2BulkElementResultDeleteMetadata$inboundSchema` instead. */
    export const inboundSchema = V2BulkElementResultDeleteMetadata$inboundSchema;
    /** @deprecated use `V2BulkElementResultDeleteMetadata$outboundSchema` instead. */
    export const outboundSchema = V2BulkElementResultDeleteMetadata$outboundSchema;
    /** @deprecated use `V2BulkElementResultDeleteMetadata$Outbound` instead. */
    export type Outbound = V2BulkElementResultDeleteMetadata$Outbound;
}

/** @internal */
export const V2BulkElementResultRevertTransaction$inboundSchema: z.ZodType<
    V2BulkElementResultRevertTransaction,
    z.ZodTypeDef,
    unknown
> = z.object({
    responseType: z.string(),
    logID: z.number().int(),
    data: V2Transaction$inboundSchema,
});

/** @internal */
export type V2BulkElementResultRevertTransaction$Outbound = {
    responseType: string;
    logID: number;
    data: V2Transaction$Outbound;
};

/** @internal */
export const V2BulkElementResultRevertTransaction$outboundSchema: z.ZodType<
    V2BulkElementResultRevertTransaction$Outbound,
    z.ZodTypeDef,
    V2BulkElementResultRevertTransaction
> = z.object({
    responseType: z.string(),
    logID: z.number().int(),
    data: V2Transaction$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2BulkElementResultRevertTransaction$ {
    /** @deprecated use `V2BulkElementResultRevertTransaction$inboundSchema` instead. */
    export const inboundSchema = V2BulkElementResultRevertTransaction$inboundSchema;
    /** @deprecated use `V2BulkElementResultRevertTransaction$outboundSchema` instead. */
    export const outboundSchema = V2BulkElementResultRevertTransaction$outboundSchema;
    /** @deprecated use `V2BulkElementResultRevertTransaction$Outbound` instead. */
    export type Outbound = V2BulkElementResultRevertTransaction$Outbound;
}

/** @internal */
export const V2BulkElementResultAddMetadata$inboundSchema: z.ZodType<
    V2BulkElementResultAddMetadata,
    z.ZodTypeDef,
    unknown
> = z.object({
    responseType: z.string(),
    logID: z.number().int(),
});

/** @internal */
export type V2BulkElementResultAddMetadata$Outbound = {
    responseType: string;
    logID: number;
};

/** @internal */
export const V2BulkElementResultAddMetadata$outboundSchema: z.ZodType<
    V2BulkElementResultAddMetadata$Outbound,
    z.ZodTypeDef,
    V2BulkElementResultAddMetadata
> = z.object({
    responseType: z.string(),
    logID: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2BulkElementResultAddMetadata$ {
    /** @deprecated use `V2BulkElementResultAddMetadata$inboundSchema` instead. */
    export const inboundSchema = V2BulkElementResultAddMetadata$inboundSchema;
    /** @deprecated use `V2BulkElementResultAddMetadata$outboundSchema` instead. */
    export const outboundSchema = V2BulkElementResultAddMetadata$outboundSchema;
    /** @deprecated use `V2BulkElementResultAddMetadata$Outbound` instead. */
    export type Outbound = V2BulkElementResultAddMetadata$Outbound;
}

/** @internal */
export const V2BulkElementResultCreateTransaction$inboundSchema: z.ZodType<
    V2BulkElementResultCreateTransaction,
    z.ZodTypeDef,
    unknown
> = z.object({
    responseType: z.string(),
    logID: z.number().int(),
    data: V2Transaction$inboundSchema,
});

/** @internal */
export type V2BulkElementResultCreateTransaction$Outbound = {
    responseType: string;
    logID: number;
    data: V2Transaction$Outbound;
};

/** @internal */
export const V2BulkElementResultCreateTransaction$outboundSchema: z.ZodType<
    V2BulkElementResultCreateTransaction$Outbound,
    z.ZodTypeDef,
    V2BulkElementResultCreateTransaction
> = z.object({
    responseType: z.string(),
    logID: z.number().int(),
    data: V2Transaction$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2BulkElementResultCreateTransaction$ {
    /** @deprecated use `V2BulkElementResultCreateTransaction$inboundSchema` instead. */
    export const inboundSchema = V2BulkElementResultCreateTransaction$inboundSchema;
    /** @deprecated use `V2BulkElementResultCreateTransaction$outboundSchema` instead. */
    export const outboundSchema = V2BulkElementResultCreateTransaction$outboundSchema;
    /** @deprecated use `V2BulkElementResultCreateTransaction$Outbound` instead. */
    export type Outbound = V2BulkElementResultCreateTransaction$Outbound;
}

/** @internal */
export const V2BulkElementResult$inboundSchema: z.ZodType<
    V2BulkElementResult,
    z.ZodTypeDef,
    unknown
> = z.union([
    z
        .lazy(() => V2BulkElementResultAddMetadata$inboundSchema)
        .and(
            z
                .object({ responseType: z.literal("ADD_METADATA") })
                .transform((v) => ({ responseType: v.responseType }))
        ),
    z
        .lazy(() => V2BulkElementResultDeleteMetadata$inboundSchema)
        .and(
            z
                .object({ responseType: z.literal("DELETE_METADATA") })
                .transform((v) => ({ responseType: v.responseType }))
        ),
    z
        .lazy(() => V2BulkElementResultCreateTransaction$inboundSchema)
        .and(
            z
                .object({ responseType: z.literal("CREATE_TRANSACTION") })
                .transform((v) => ({ responseType: v.responseType }))
        ),
    z
        .lazy(() => V2BulkElementResultRevertTransaction$inboundSchema)
        .and(
            z
                .object({ responseType: z.literal("REVERT_TRANSACTION") })
                .transform((v) => ({ responseType: v.responseType }))
        ),
    z
        .lazy(() => V2BulkElementResultError$inboundSchema)
        .and(
            z
                .object({ responseType: z.literal("ERROR") })
                .transform((v) => ({ responseType: v.responseType }))
        ),
]);

/** @internal */
export type V2BulkElementResult$Outbound =
    | (V2BulkElementResultAddMetadata$Outbound & { responseType: "ADD_METADATA" })
    | (V2BulkElementResultDeleteMetadata$Outbound & { responseType: "DELETE_METADATA" })
    | (V2BulkElementResultCreateTransaction$Outbound & { responseType: "CREATE_TRANSACTION" })
    | (V2BulkElementResultRevertTransaction$Outbound & { responseType: "REVERT_TRANSACTION" })
    | (V2BulkElementResultError$Outbound & { responseType: "ERROR" });

/** @internal */
export const V2BulkElementResult$outboundSchema: z.ZodType<
    V2BulkElementResult$Outbound,
    z.ZodTypeDef,
    V2BulkElementResult
> = z.union([
    z
        .lazy(() => V2BulkElementResultAddMetadata$outboundSchema)
        .and(
            z
                .object({ responseType: z.literal("ADD_METADATA") })
                .transform((v) => ({ responseType: v.responseType }))
        ),
    z
        .lazy(() => V2BulkElementResultDeleteMetadata$outboundSchema)
        .and(
            z
                .object({ responseType: z.literal("DELETE_METADATA") })
                .transform((v) => ({ responseType: v.responseType }))
        ),
    z
        .lazy(() => V2BulkElementResultCreateTransaction$outboundSchema)
        .and(
            z
                .object({ responseType: z.literal("CREATE_TRANSACTION") })
                .transform((v) => ({ responseType: v.responseType }))
        ),
    z
        .lazy(() => V2BulkElementResultRevertTransaction$outboundSchema)
        .and(
            z
                .object({ responseType: z.literal("REVERT_TRANSACTION") })
                .transform((v) => ({ responseType: v.responseType }))
        ),
    z
        .lazy(() => V2BulkElementResultError$outboundSchema)
        .and(
            z
                .object({ responseType: z.literal("ERROR") })
                .transform((v) => ({ responseType: v.responseType }))
        ),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2BulkElementResult$ {
    /** @deprecated use `V2BulkElementResult$inboundSchema` instead. */
    export const inboundSchema = V2BulkElementResult$inboundSchema;
    /** @deprecated use `V2BulkElementResult$outboundSchema` instead. */
    export const outboundSchema = V2BulkElementResult$outboundSchema;
    /** @deprecated use `V2BulkElementResult$Outbound` instead. */
    export type Outbound = V2BulkElementResult$Outbound;
}
