/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    V2Exporter,
    V2Exporter$inboundSchema,
    V2Exporter$Outbound,
    V2Exporter$outboundSchema,
} from "./v2exporter.js";
import * as z from "zod";

export type V2CreateExporterResponse = {
    data: V2Exporter;
};

/** @internal */
export const V2CreateExporterResponse$inboundSchema: z.ZodType<
    V2CreateExporterResponse,
    z.ZodTypeDef,
    unknown
> = z.object({
    data: V2Exporter$inboundSchema,
});

/** @internal */
export type V2CreateExporterResponse$Outbound = {
    data: V2Exporter$Outbound;
};

/** @internal */
export const V2CreateExporterResponse$outboundSchema: z.ZodType<
    V2CreateExporterResponse$Outbound,
    z.ZodTypeDef,
    V2CreateExporterResponse
> = z.object({
    data: V2Exporter$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2CreateExporterResponse$ {
    /** @deprecated use `V2CreateExporterResponse$inboundSchema` instead. */
    export const inboundSchema = V2CreateExporterResponse$inboundSchema;
    /** @deprecated use `V2CreateExporterResponse$outboundSchema` instead. */
    export const outboundSchema = V2CreateExporterResponse$outboundSchema;
    /** @deprecated use `V2CreateExporterResponse$Outbound` instead. */
    export type Outbound = V2CreateExporterResponse$Outbound;
}
