/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as b64$ from "../../lib/base64.js";
import * as z from "zod";

export type V2ImportLogsRequest = {
    file: Uint8Array | string;
};

/** @internal */
export const V2ImportLogsRequest$inboundSchema: z.ZodType<
    V2ImportLogsRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    file: b64$.zodInbound,
});

/** @internal */
export type V2ImportLogsRequest$Outbound = {
    file: Uint8Array;
};

/** @internal */
export const V2ImportLogsRequest$outboundSchema: z.ZodType<
    V2ImportLogsRequest$Outbound,
    z.ZodTypeDef,
    V2ImportLogsRequest
> = z.object({
    file: b64$.zodOutbound,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2ImportLogsRequest$ {
    /** @deprecated use `V2ImportLogsRequest$inboundSchema` instead. */
    export const inboundSchema = V2ImportLogsRequest$inboundSchema;
    /** @deprecated use `V2ImportLogsRequest$outboundSchema` instead. */
    export const outboundSchema = V2ImportLogsRequest$outboundSchema;
    /** @deprecated use `V2ImportLogsRequest$Outbound` instead. */
    export type Outbound = V2ImportLogsRequest$Outbound;
}
