/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    V2Exporter,
    V2Exporter$inboundSchema,
    V2Exporter$Outbound,
    V2Exporter$outboundSchema,
} from "./v2exporter.js";
import * as z from "zod";

export type V2ListExportersResponseCursorCursor = {
    pageSize: number;
    hasMore: boolean;
    previous?: string | undefined;
    next?: string | undefined;
    data: Array<V2Exporter>;
};

export type V2ListExportersResponseCursor = {
    cursor: V2ListExportersResponseCursorCursor;
    data?: Array<V2Exporter> | undefined;
};

export type V2ListExportersResponse = {
    cursor?: V2ListExportersResponseCursor | undefined;
};

/** @internal */
export const V2ListExportersResponseCursorCursor$inboundSchema: z.ZodType<
    V2ListExportersResponseCursorCursor,
    z.ZodTypeDef,
    unknown
> = z.object({
    pageSize: z.number().int(),
    hasMore: z.boolean(),
    previous: z.string().optional(),
    next: z.string().optional(),
    data: z.array(V2Exporter$inboundSchema),
});

/** @internal */
export type V2ListExportersResponseCursorCursor$Outbound = {
    pageSize: number;
    hasMore: boolean;
    previous?: string | undefined;
    next?: string | undefined;
    data: Array<V2Exporter$Outbound>;
};

/** @internal */
export const V2ListExportersResponseCursorCursor$outboundSchema: z.ZodType<
    V2ListExportersResponseCursorCursor$Outbound,
    z.ZodTypeDef,
    V2ListExportersResponseCursorCursor
> = z.object({
    pageSize: z.number().int(),
    hasMore: z.boolean(),
    previous: z.string().optional(),
    next: z.string().optional(),
    data: z.array(V2Exporter$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2ListExportersResponseCursorCursor$ {
    /** @deprecated use `V2ListExportersResponseCursorCursor$inboundSchema` instead. */
    export const inboundSchema = V2ListExportersResponseCursorCursor$inboundSchema;
    /** @deprecated use `V2ListExportersResponseCursorCursor$outboundSchema` instead. */
    export const outboundSchema = V2ListExportersResponseCursorCursor$outboundSchema;
    /** @deprecated use `V2ListExportersResponseCursorCursor$Outbound` instead. */
    export type Outbound = V2ListExportersResponseCursorCursor$Outbound;
}

/** @internal */
export const V2ListExportersResponseCursor$inboundSchema: z.ZodType<
    V2ListExportersResponseCursor,
    z.ZodTypeDef,
    unknown
> = z.object({
    cursor: z.lazy(() => V2ListExportersResponseCursorCursor$inboundSchema),
    data: z.array(V2Exporter$inboundSchema).optional(),
});

/** @internal */
export type V2ListExportersResponseCursor$Outbound = {
    cursor: V2ListExportersResponseCursorCursor$Outbound;
    data?: Array<V2Exporter$Outbound> | undefined;
};

/** @internal */
export const V2ListExportersResponseCursor$outboundSchema: z.ZodType<
    V2ListExportersResponseCursor$Outbound,
    z.ZodTypeDef,
    V2ListExportersResponseCursor
> = z.object({
    cursor: z.lazy(() => V2ListExportersResponseCursorCursor$outboundSchema),
    data: z.array(V2Exporter$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2ListExportersResponseCursor$ {
    /** @deprecated use `V2ListExportersResponseCursor$inboundSchema` instead. */
    export const inboundSchema = V2ListExportersResponseCursor$inboundSchema;
    /** @deprecated use `V2ListExportersResponseCursor$outboundSchema` instead. */
    export const outboundSchema = V2ListExportersResponseCursor$outboundSchema;
    /** @deprecated use `V2ListExportersResponseCursor$Outbound` instead. */
    export type Outbound = V2ListExportersResponseCursor$Outbound;
}

/** @internal */
export const V2ListExportersResponse$inboundSchema: z.ZodType<
    V2ListExportersResponse,
    z.ZodTypeDef,
    unknown
> = z.object({
    cursor: z.lazy(() => V2ListExportersResponseCursor$inboundSchema).optional(),
});

/** @internal */
export type V2ListExportersResponse$Outbound = {
    cursor?: V2ListExportersResponseCursor$Outbound | undefined;
};

/** @internal */
export const V2ListExportersResponse$outboundSchema: z.ZodType<
    V2ListExportersResponse$Outbound,
    z.ZodTypeDef,
    V2ListExportersResponse
> = z.object({
    cursor: z.lazy(() => V2ListExportersResponseCursor$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2ListExportersResponse$ {
    /** @deprecated use `V2ListExportersResponse$inboundSchema` instead. */
    export const inboundSchema = V2ListExportersResponse$inboundSchema;
    /** @deprecated use `V2ListExportersResponse$outboundSchema` instead. */
    export const outboundSchema = V2ListExportersResponse$outboundSchema;
    /** @deprecated use `V2ListExportersResponse$Outbound` instead. */
    export type Outbound = V2ListExportersResponse$Outbound;
}
