/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    V3BankAccount,
    V3BankAccount$inboundSchema,
    V3BankAccount$Outbound,
    V3BankAccount$outboundSchema,
} from "./v3bankaccount.js";
import * as z from "zod";

export type V3BankAccountsCursorResponseCursor = {
    pageSize: number;
    hasMore: boolean;
    previous?: string | undefined;
    next?: string | undefined;
    data: Array<V3BankAccount>;
};

export type V3BankAccountsCursorResponse = {
    cursor: V3BankAccountsCursorResponseCursor;
};

/** @internal */
export const V3BankAccountsCursorResponseCursor$inboundSchema: z.ZodType<
    V3BankAccountsCursorResponseCursor,
    z.ZodTypeDef,
    unknown
> = z.object({
    pageSize: z.number().int(),
    hasMore: z.boolean(),
    previous: z.string().optional(),
    next: z.string().optional(),
    data: z.array(V3BankAccount$inboundSchema),
});

/** @internal */
export type V3BankAccountsCursorResponseCursor$Outbound = {
    pageSize: number;
    hasMore: boolean;
    previous?: string | undefined;
    next?: string | undefined;
    data: Array<V3BankAccount$Outbound>;
};

/** @internal */
export const V3BankAccountsCursorResponseCursor$outboundSchema: z.ZodType<
    V3BankAccountsCursorResponseCursor$Outbound,
    z.ZodTypeDef,
    V3BankAccountsCursorResponseCursor
> = z.object({
    pageSize: z.number().int(),
    hasMore: z.boolean(),
    previous: z.string().optional(),
    next: z.string().optional(),
    data: z.array(V3BankAccount$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3BankAccountsCursorResponseCursor$ {
    /** @deprecated use `V3BankAccountsCursorResponseCursor$inboundSchema` instead. */
    export const inboundSchema = V3BankAccountsCursorResponseCursor$inboundSchema;
    /** @deprecated use `V3BankAccountsCursorResponseCursor$outboundSchema` instead. */
    export const outboundSchema = V3BankAccountsCursorResponseCursor$outboundSchema;
    /** @deprecated use `V3BankAccountsCursorResponseCursor$Outbound` instead. */
    export type Outbound = V3BankAccountsCursorResponseCursor$Outbound;
}

/** @internal */
export const V3BankAccountsCursorResponse$inboundSchema: z.ZodType<
    V3BankAccountsCursorResponse,
    z.ZodTypeDef,
    unknown
> = z.object({
    cursor: z.lazy(() => V3BankAccountsCursorResponseCursor$inboundSchema),
});

/** @internal */
export type V3BankAccountsCursorResponse$Outbound = {
    cursor: V3BankAccountsCursorResponseCursor$Outbound;
};

/** @internal */
export const V3BankAccountsCursorResponse$outboundSchema: z.ZodType<
    V3BankAccountsCursorResponse$Outbound,
    z.ZodTypeDef,
    V3BankAccountsCursorResponse
> = z.object({
    cursor: z.lazy(() => V3BankAccountsCursorResponseCursor$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3BankAccountsCursorResponse$ {
    /** @deprecated use `V3BankAccountsCursorResponse$inboundSchema` instead. */
    export const inboundSchema = V3BankAccountsCursorResponse$inboundSchema;
    /** @deprecated use `V3BankAccountsCursorResponse$outboundSchema` instead. */
    export const outboundSchema = V3BankAccountsCursorResponse$outboundSchema;
    /** @deprecated use `V3BankAccountsCursorResponse$Outbound` instead. */
    export type Outbound = V3BankAccountsCursorResponse$Outbound;
}
