/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types/enums.js";
import * as z from "zod";

export const V3OpenBankingConnectionAttemptStatusEnum = {
    Pending: "pending",
    Completed: "completed",
    Exited: "exited",
} as const;
export type V3OpenBankingConnectionAttemptStatusEnum = ClosedEnum<
    typeof V3OpenBankingConnectionAttemptStatusEnum
>;

/** @internal */
export const V3OpenBankingConnectionAttemptStatusEnum$inboundSchema: z.ZodNativeEnum<
    typeof V3OpenBankingConnectionAttemptStatusEnum
> = z.nativeEnum(V3OpenBankingConnectionAttemptStatusEnum);

/** @internal */
export const V3OpenBankingConnectionAttemptStatusEnum$outboundSchema: z.ZodNativeEnum<
    typeof V3OpenBankingConnectionAttemptStatusEnum
> = V3OpenBankingConnectionAttemptStatusEnum$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3OpenBankingConnectionAttemptStatusEnum$ {
    /** @deprecated use `V3OpenBankingConnectionAttemptStatusEnum$inboundSchema` instead. */
    export const inboundSchema = V3OpenBankingConnectionAttemptStatusEnum$inboundSchema;
    /** @deprecated use `V3OpenBankingConnectionAttemptStatusEnum$outboundSchema` instead. */
    export const outboundSchema = V3OpenBankingConnectionAttemptStatusEnum$outboundSchema;
}
