/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    V3PaymentInitiationStatusEnum,
    V3PaymentInitiationStatusEnum$inboundSchema,
    V3PaymentInitiationStatusEnum$outboundSchema,
} from "./v3paymentinitiationstatusenum.js";
import {
    V3PaymentInitiationTypeEnum,
    V3PaymentInitiationTypeEnum$inboundSchema,
    V3PaymentInitiationTypeEnum$outboundSchema,
} from "./v3paymentinitiationtypeenum.js";
import * as z from "zod";

export type V3PaymentInitiation = {
    id: string;
    connectorID: string;
    provider: string;
    reference: string;
    createdAt: Date;
    scheduledAt: Date;
    description: string;
    type: V3PaymentInitiationTypeEnum;
    amount: bigint;
    asset: string;
    status: V3PaymentInitiationStatusEnum;
    sourceAccountID?: string | undefined;
    destinationAccountID?: string | undefined;
    error?: string | null | undefined;
    metadata?: { [k: string]: string } | null | undefined;
};

/** @internal */
export const V3PaymentInitiation$inboundSchema: z.ZodType<
    V3PaymentInitiation,
    z.ZodTypeDef,
    unknown
> = z.object({
    id: z.string(),
    connectorID: z.string(),
    provider: z.string(),
    reference: z.string(),
    createdAt: z
        .string()
        .datetime({ offset: true })
        .transform((v) => new Date(v)),
    scheduledAt: z
        .string()
        .datetime({ offset: true })
        .transform((v) => new Date(v)),
    description: z.string(),
    type: V3PaymentInitiationTypeEnum$inboundSchema,
    amount: z.number().transform((v) => BigInt(v)),
    asset: z.string(),
    status: V3PaymentInitiationStatusEnum$inboundSchema,
    sourceAccountID: z.string().optional(),
    destinationAccountID: z.string().optional(),
    error: z.nullable(z.string()).optional(),
    metadata: z.nullable(z.record(z.string())).optional(),
});

/** @internal */
export type V3PaymentInitiation$Outbound = {
    id: string;
    connectorID: string;
    provider: string;
    reference: string;
    createdAt: string;
    scheduledAt: string;
    description: string;
    type: string;
    amount: number;
    asset: string;
    status: string;
    sourceAccountID?: string | undefined;
    destinationAccountID?: string | undefined;
    error?: string | null | undefined;
    metadata?: { [k: string]: string } | null | undefined;
};

/** @internal */
export const V3PaymentInitiation$outboundSchema: z.ZodType<
    V3PaymentInitiation$Outbound,
    z.ZodTypeDef,
    V3PaymentInitiation
> = z.object({
    id: z.string(),
    connectorID: z.string(),
    provider: z.string(),
    reference: z.string(),
    createdAt: z.date().transform((v) => v.toISOString()),
    scheduledAt: z.date().transform((v) => v.toISOString()),
    description: z.string(),
    type: V3PaymentInitiationTypeEnum$outboundSchema,
    amount: z.bigint().transform((v) => Number(v)),
    asset: z.string(),
    status: V3PaymentInitiationStatusEnum$outboundSchema,
    sourceAccountID: z.string().optional(),
    destinationAccountID: z.string().optional(),
    error: z.nullable(z.string()).optional(),
    metadata: z.nullable(z.record(z.string())).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3PaymentInitiation$ {
    /** @deprecated use `V3PaymentInitiation$inboundSchema` instead. */
    export const inboundSchema = V3PaymentInitiation$inboundSchema;
    /** @deprecated use `V3PaymentInitiation$outboundSchema` instead. */
    export const outboundSchema = V3PaymentInitiation$outboundSchema;
    /** @deprecated use `V3PaymentInitiation$Outbound` instead. */
    export type Outbound = V3PaymentInitiation$Outbound;
}
