/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type V3PaymentServiceUserUpdateLinkRequest = {
    /**
     * The name of the application to be displayed to the user when they click the link (depending on the open banking provider). Note that this field might be mandatory for some open banking providers.
     */
    applicationName?: string | undefined;
    clientRedirectURL: string;
};

/** @internal */
export const V3PaymentServiceUserUpdateLinkRequest$inboundSchema: z.ZodType<
    V3PaymentServiceUserUpdateLinkRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    applicationName: z.string().optional(),
    clientRedirectURL: z.string(),
});

/** @internal */
export type V3PaymentServiceUserUpdateLinkRequest$Outbound = {
    applicationName?: string | undefined;
    clientRedirectURL: string;
};

/** @internal */
export const V3PaymentServiceUserUpdateLinkRequest$outboundSchema: z.ZodType<
    V3PaymentServiceUserUpdateLinkRequest$Outbound,
    z.ZodTypeDef,
    V3PaymentServiceUserUpdateLinkRequest
> = z.object({
    applicationName: z.string().optional(),
    clientRedirectURL: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3PaymentServiceUserUpdateLinkRequest$ {
    /** @deprecated use `V3PaymentServiceUserUpdateLinkRequest$inboundSchema` instead. */
    export const inboundSchema = V3PaymentServiceUserUpdateLinkRequest$inboundSchema;
    /** @deprecated use `V3PaymentServiceUserUpdateLinkRequest$outboundSchema` instead. */
    export const outboundSchema = V3PaymentServiceUserUpdateLinkRequest$outboundSchema;
    /** @deprecated use `V3PaymentServiceUserUpdateLinkRequest$Outbound` instead. */
    export type Outbound = V3PaymentServiceUserUpdateLinkRequest$Outbound;
}
