/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type V3ReversePaymentInitiationRequest = {
    reference: string;
    description: string;
    amount: bigint;
    asset: string;
    metadata?: { [k: string]: string } | null | undefined;
};

/** @internal */
export const V3ReversePaymentInitiationRequest$inboundSchema: z.ZodType<
    V3ReversePaymentInitiationRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    reference: z.string(),
    description: z.string(),
    amount: z.number().transform((v) => BigInt(v)),
    asset: z.string(),
    metadata: z.nullable(z.record(z.string())).optional(),
});

/** @internal */
export type V3ReversePaymentInitiationRequest$Outbound = {
    reference: string;
    description: string;
    amount: number;
    asset: string;
    metadata?: { [k: string]: string } | null | undefined;
};

/** @internal */
export const V3ReversePaymentInitiationRequest$outboundSchema: z.ZodType<
    V3ReversePaymentInitiationRequest$Outbound,
    z.ZodTypeDef,
    V3ReversePaymentInitiationRequest
> = z.object({
    reference: z.string(),
    description: z.string(),
    amount: z.bigint().transform((v) => Number(v)),
    asset: z.string(),
    metadata: z.nullable(z.record(z.string())).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3ReversePaymentInitiationRequest$ {
    /** @deprecated use `V3ReversePaymentInitiationRequest$inboundSchema` instead. */
    export const inboundSchema = V3ReversePaymentInitiationRequest$inboundSchema;
    /** @deprecated use `V3ReversePaymentInitiationRequest$outboundSchema` instead. */
    export const outboundSchema = V3ReversePaymentInitiationRequest$outboundSchema;
    /** @deprecated use `V3ReversePaymentInitiationRequest$Outbound` instead. */
    export type Outbound = V3ReversePaymentInitiationRequest$Outbound;
}
