/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteAppVariableRequest = {
    id: string;
    variableId: string;
};

/** @internal */
export const DeleteAppVariableRequest$inboundSchema: z.ZodType<
    DeleteAppVariableRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    id: z.string(),
    variableId: z.string(),
});

/** @internal */
export type DeleteAppVariableRequest$Outbound = {
    id: string;
    variableId: string;
};

/** @internal */
export const DeleteAppVariableRequest$outboundSchema: z.ZodType<
    DeleteAppVariableRequest$Outbound,
    z.ZodTypeDef,
    DeleteAppVariableRequest
> = z.object({
    id: z.string(),
    variableId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteAppVariableRequest$ {
    /** @deprecated use `DeleteAppVariableRequest$inboundSchema` instead. */
    export const inboundSchema = DeleteAppVariableRequest$inboundSchema;
    /** @deprecated use `DeleteAppVariableRequest$outboundSchema` instead. */
    export const outboundSchema = DeleteAppVariableRequest$outboundSchema;
    /** @deprecated use `DeleteAppVariableRequest$Outbound` instead. */
    export type Outbound = DeleteAppVariableRequest$Outbound;
}
