/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as b64$ from "../../lib/base64.js";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type DeployAppConfigurationRawRequest = {
    id: string;
    requestBody: Uint8Array | string;
};

export type DeployAppConfigurationRawResponse = components.RunResponse | components.ErrorT;

/** @internal */
export const DeployAppConfigurationRawRequest$inboundSchema: z.ZodType<
    DeployAppConfigurationRawRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        id: z.string(),
        RequestBody: b64$.zodInbound,
    })
    .transform((v) => {
        return remap$(v, {
            RequestBody: "requestBody",
        });
    });

/** @internal */
export type DeployAppConfigurationRawRequest$Outbound = {
    id: string;
    RequestBody: Uint8Array;
};

/** @internal */
export const DeployAppConfigurationRawRequest$outboundSchema: z.ZodType<
    DeployAppConfigurationRawRequest$Outbound,
    z.ZodTypeDef,
    DeployAppConfigurationRawRequest
> = z
    .object({
        id: z.string(),
        requestBody: b64$.zodOutbound,
    })
    .transform((v) => {
        return remap$(v, {
            requestBody: "RequestBody",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeployAppConfigurationRawRequest$ {
    /** @deprecated use `DeployAppConfigurationRawRequest$inboundSchema` instead. */
    export const inboundSchema = DeployAppConfigurationRawRequest$inboundSchema;
    /** @deprecated use `DeployAppConfigurationRawRequest$outboundSchema` instead. */
    export const outboundSchema = DeployAppConfigurationRawRequest$outboundSchema;
    /** @deprecated use `DeployAppConfigurationRawRequest$Outbound` instead. */
    export type Outbound = DeployAppConfigurationRawRequest$Outbound;
}

/** @internal */
export const DeployAppConfigurationRawResponse$inboundSchema: z.ZodType<
    DeployAppConfigurationRawResponse,
    z.ZodTypeDef,
    unknown
> = z.union([components.RunResponse$inboundSchema, components.ErrorT$inboundSchema]);

/** @internal */
export type DeployAppConfigurationRawResponse$Outbound =
    | components.RunResponse$Outbound
    | components.ErrorT$Outbound;

/** @internal */
export const DeployAppConfigurationRawResponse$outboundSchema: z.ZodType<
    DeployAppConfigurationRawResponse$Outbound,
    z.ZodTypeDef,
    DeployAppConfigurationRawResponse
> = z.union([components.RunResponse$outboundSchema, components.ErrorT$outboundSchema]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeployAppConfigurationRawResponse$ {
    /** @deprecated use `DeployAppConfigurationRawResponse$inboundSchema` instead. */
    export const inboundSchema = DeployAppConfigurationRawResponse$inboundSchema;
    /** @deprecated use `DeployAppConfigurationRawResponse$outboundSchema` instead. */
    export const outboundSchema = DeployAppConfigurationRawResponse$outboundSchema;
    /** @deprecated use `DeployAppConfigurationRawResponse$Outbound` instead. */
    export type Outbound = DeployAppConfigurationRawResponse$Outbound;
}
