/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type UpdateAppRequest = {
    id: string;
    updateAppRequest: components.UpdateAppRequest;
};

/** @internal */
export const UpdateAppRequest$inboundSchema: z.ZodType<UpdateAppRequest, z.ZodTypeDef, unknown> = z
    .object({
        id: z.string(),
        UpdateAppRequest: components.UpdateAppRequest$inboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            UpdateAppRequest: "updateAppRequest",
        });
    });

/** @internal */
export type UpdateAppRequest$Outbound = {
    id: string;
    UpdateAppRequest: components.UpdateAppRequest$Outbound;
};

/** @internal */
export const UpdateAppRequest$outboundSchema: z.ZodType<
    UpdateAppRequest$Outbound,
    z.ZodTypeDef,
    UpdateAppRequest
> = z
    .object({
        id: z.string(),
        updateAppRequest: components.UpdateAppRequest$outboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            updateAppRequest: "UpdateAppRequest",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateAppRequest$ {
    /** @deprecated use `UpdateAppRequest$inboundSchema` instead. */
    export const inboundSchema = UpdateAppRequest$inboundSchema;
    /** @deprecated use `UpdateAppRequest$outboundSchema` instead. */
    export const outboundSchema = UpdateAppRequest$outboundSchema;
    /** @deprecated use `UpdateAppRequest$Outbound` instead. */
    export type Outbound = UpdateAppRequest$Outbound;
}
