/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { SDKHooks } from "../hooks/hooks.js";
import { SDKOptions, serverURLFromOptions } from "../lib/config.js";
import {
    encodeFormQuery as encodeFormQuery$,
    encodeJSON as encodeJSON$,
    encodeJSONQuery as encodeJSONQuery$,
    encodeSimple as encodeSimple$,
    queryJoin as queryJoin$,
} from "../lib/encodings.js";
import { HTTPClient } from "../lib/http.js";
import * as schemas$ from "../lib/schemas.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { extractSecurity } from "../lib/security.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";

export class SDKReconciliationV1 extends ClientSDK {
    private readonly options$: SDKOptions & { hooks?: SDKHooks };

    constructor(options: SDKOptions = {}) {
        const opt = options as unknown;
        let hooks: SDKHooks;
        if (
            typeof opt === "object" &&
            opt != null &&
            "hooks" in opt &&
            opt.hooks instanceof SDKHooks
        ) {
            hooks = opt.hooks;
        } else {
            hooks = new SDKHooks();
        }

        super({
            client: options.httpClient || new HTTPClient(),
            baseURL: serverURLFromOptions(options),
            hooks,
        });

        this.options$ = { ...options, hooks };
        void this.options$;
    }

    /**
     * Get server info
     */
    async reconciliationgetServerInfo(
        options?: RequestOptions
    ): Promise<operations.ReconciliationgetServerInfoResponse> {
        const path$ = this.templateURLComponent("/api/reconciliation/_info")();

        const query$ = "";

        const headers$ = new Headers({
            Accept: "application/json",
        });

        const security$ = await extractSecurity(this.options$.security);
        const context = {
            operationID: "reconciliationgetServerInfo",
            oAuth2Scopes: ["auth:read", "reconciliation:read"],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const response = await this.do$(request$, {
            context,
            errorCodes: ["4XX", "5XX"],
            retryConfig: options?.retries || this.options$.retryConfig,
            retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
        });

        const [result$] = await this.matcher<operations.ReconciliationgetServerInfoResponse>()
            .json(200, operations.ReconciliationgetServerInfoResponse$inboundSchema)
            .fail(["4XX", "5XX"])
            .json("default", operations.ReconciliationgetServerInfoResponse$inboundSchema)
            .match(response);

        return result$;
    }

    /**
     * Create a policy
     *
     * @remarks
     * Create a policy
     */
    async createPolicy(
        request: components.PolicyRequest,
        options?: RequestOptions
    ): Promise<operations.CreatePolicyResponse> {
        const input$ = request;

        const payload$ = schemas$.parse(
            input$,
            (value$) => components.PolicyRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = encodeJSON$("body", payload$, { explode: true });

        const path$ = this.templateURLComponent("/api/reconciliation/policies")();

        const query$ = "";

        const headers$ = new Headers({
            "Content-Type": "application/json",
            Accept: "application/json",
        });

        const security$ = await extractSecurity(this.options$.security);
        const context = {
            operationID: "createPolicy",
            oAuth2Scopes: ["auth:read", "reconciliation:write"],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "POST",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const response = await this.do$(request$, {
            context,
            errorCodes: ["4XX", "5XX"],
            retryConfig: options?.retries || this.options$.retryConfig,
            retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
        });

        const [result$] = await this.matcher<operations.CreatePolicyResponse>()
            .json(201, operations.CreatePolicyResponse$inboundSchema)
            .fail(["4XX", "5XX"])
            .json("default", operations.CreatePolicyResponse$inboundSchema)
            .match(response);

        return result$;
    }

    /**
     * List policies
     */
    async listPolicies(
        request: operations.ListPoliciesRequest,
        options?: RequestOptions
    ): Promise<operations.ListPoliciesResponse> {
        const input$ = typeof request === "undefined" ? {} : request;

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.ListPoliciesRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const path$ = this.templateURLComponent("/api/reconciliation/policies")();

        const query$ = queryJoin$(
            encodeFormQuery$({
                cursor: payload$.cursor,
                pageSize: payload$.pageSize,
            }),
            encodeJSONQuery$(
                {
                    query: payload$.query,
                },
                { explode: false }
            )
        );

        const headers$ = new Headers({
            Accept: "application/json",
        });

        const security$ = await extractSecurity(this.options$.security);
        const context = {
            operationID: "listPolicies",
            oAuth2Scopes: ["auth:read", "reconciliation:read"],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const response = await this.do$(request$, {
            context,
            errorCodes: ["4XX", "5XX"],
            retryConfig: options?.retries || this.options$.retryConfig,
            retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
        });

        const [result$] = await this.matcher<operations.ListPoliciesResponse>()
            .json(200, operations.ListPoliciesResponse$inboundSchema)
            .fail(["4XX", "5XX"])
            .json("default", operations.ListPoliciesResponse$inboundSchema)
            .match(response);

        return result$;
    }

    /**
     * Delete a policy
     *
     * @remarks
     * Delete a policy by its id.
     */
    async deletePolicy(
        request: operations.DeletePolicyRequest,
        options?: RequestOptions
    ): Promise<components.ReconciliationErrorResponse | undefined> {
        const input$ = request;

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.DeletePolicyRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            policyID: encodeSimple$("policyID", payload$.policyID, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent("/api/reconciliation/policies/{policyID}")(
            pathParams$
        );

        const query$ = "";

        const headers$ = new Headers({
            Accept: "application/json",
        });

        const security$ = await extractSecurity(this.options$.security);
        const context = {
            operationID: "deletePolicy",
            oAuth2Scopes: ["auth:read", "reconciliation:write"],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "DELETE",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const response = await this.do$(request$, {
            context,
            errorCodes: ["4XX", "5XX"],
            retryConfig: options?.retries || this.options$.retryConfig,
            retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
        });

        const [result$] = await this.matcher<components.ReconciliationErrorResponse | undefined>()
            .void(204, components.ReconciliationErrorResponse$inboundSchema.optional())
            .fail(["4XX", "5XX"])
            .json("default", components.ReconciliationErrorResponse$inboundSchema.optional())
            .match(response);

        return result$;
    }

    /**
     * Get a policy
     */
    async getPolicy(
        request: operations.GetPolicyRequest,
        options?: RequestOptions
    ): Promise<operations.GetPolicyResponse> {
        const input$ = request;

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.GetPolicyRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            policyID: encodeSimple$("policyID", payload$.policyID, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent("/api/reconciliation/policies/{policyID}")(
            pathParams$
        );

        const query$ = "";

        const headers$ = new Headers({
            Accept: "application/json",
        });

        const security$ = await extractSecurity(this.options$.security);
        const context = {
            operationID: "getPolicy",
            oAuth2Scopes: ["auth:read", "reconciliation:read"],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const response = await this.do$(request$, {
            context,
            errorCodes: ["4XX", "5XX"],
            retryConfig: options?.retries || this.options$.retryConfig,
            retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
        });

        const [result$] = await this.matcher<operations.GetPolicyResponse>()
            .json(200, operations.GetPolicyResponse$inboundSchema)
            .fail(["4XX", "5XX"])
            .json("default", operations.GetPolicyResponse$inboundSchema)
            .match(response);

        return result$;
    }

    /**
     * Reconcile using a policy
     *
     * @remarks
     * Reconcile using a policy
     */
    async reconcile(
        request: operations.ReconcileRequest,
        options?: RequestOptions
    ): Promise<operations.ReconcileResponse> {
        const input$ = request;

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.ReconcileRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = encodeJSON$("body", payload$.ReconciliationRequest, { explode: true });

        const pathParams$ = {
            policyID: encodeSimple$("policyID", payload$.policyID, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent(
            "/api/reconciliation/policies/{policyID}/reconciliation"
        )(pathParams$);

        const query$ = "";

        const headers$ = new Headers({
            "Content-Type": "application/json",
            Accept: "application/json",
        });

        const security$ = await extractSecurity(this.options$.security);
        const context = {
            operationID: "reconcile",
            oAuth2Scopes: ["auth:read", "reconciliation:write"],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "POST",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const response = await this.do$(request$, {
            context,
            errorCodes: ["4XX", "5XX"],
            retryConfig: options?.retries || this.options$.retryConfig,
            retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
        });

        const [result$] = await this.matcher<operations.ReconcileResponse>()
            .json(200, operations.ReconcileResponse$inboundSchema)
            .fail(["4XX", "5XX"])
            .json("default", operations.ReconcileResponse$inboundSchema)
            .match(response);

        return result$;
    }

    /**
     * List reconciliations
     */
    async listReconciliations(
        request: operations.ListReconciliationsRequest,
        options?: RequestOptions
    ): Promise<operations.ListReconciliationsResponse> {
        const input$ = typeof request === "undefined" ? {} : request;

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.ListReconciliationsRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const path$ = this.templateURLComponent("/api/reconciliation/reconciliations")();

        const query$ = queryJoin$(
            encodeFormQuery$({
                cursor: payload$.cursor,
                pageSize: payload$.pageSize,
            }),
            encodeJSONQuery$(
                {
                    query: payload$.query,
                },
                { explode: false }
            )
        );

        const headers$ = new Headers({
            Accept: "application/json",
        });

        const security$ = await extractSecurity(this.options$.security);
        const context = {
            operationID: "listReconciliations",
            oAuth2Scopes: ["auth:read", "reconciliation:read"],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const response = await this.do$(request$, {
            context,
            errorCodes: ["4XX", "5XX"],
            retryConfig: options?.retries || this.options$.retryConfig,
            retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
        });

        const [result$] = await this.matcher<operations.ListReconciliationsResponse>()
            .json(200, operations.ListReconciliationsResponse$inboundSchema)
            .fail(["4XX", "5XX"])
            .json("default", operations.ListReconciliationsResponse$inboundSchema)
            .match(response);

        return result$;
    }

    /**
     * Get a reconciliation
     */
    async getReconciliation(
        request: operations.GetReconciliationRequest,
        options?: RequestOptions
    ): Promise<operations.GetReconciliationResponse> {
        const input$ = request;

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.GetReconciliationRequest$outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            reconciliationID: encodeSimple$("reconciliationID", payload$.reconciliationID, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent(
            "/api/reconciliation/reconciliations/{reconciliationID}"
        )(pathParams$);

        const query$ = "";

        const headers$ = new Headers({
            Accept: "application/json",
        });

        const security$ = await extractSecurity(this.options$.security);
        const context = {
            operationID: "getReconciliation",
            oAuth2Scopes: ["auth:read", "reconciliation:read"],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
                timeoutMs: options?.timeoutMs || this.options$.timeoutMs || -1,
            },
            options
        );

        const response = await this.do$(request$, {
            context,
            errorCodes: ["4XX", "5XX"],
            retryConfig: options?.retries || this.options$.retryConfig,
            retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
        });

        const [result$] = await this.matcher<operations.GetReconciliationResponse>()
            .json(200, operations.GetReconciliationResponse$inboundSchema)
            .fail(["4XX", "5XX"])
            .json("default", operations.GetReconciliationResponse$inboundSchema)
            .match(response);

        return result$;
    }
}
